PACK_ID = 3
TEXT_MOD_NAME = "Blue Archive Vol " .. PACK_ID

-- ================================================================
-- Custom Models
-- ================================================================
-- ================
-- Trinity
-- ================
E_MODEL_SPMARI = smlua_model_util_get_id("spmari_geo")
E_MODEL_MARI = smlua_model_util_get_id("mari_geo")
E_MODEL_IMARI = smlua_model_util_get_id("imari_geo")
E_MODEL_KAZUSA = smlua_model_util_get_id("kazusa_geo")
E_MODEL_AZUSA = smlua_model_util_get_id("azusa_geo")
E_MODEL_AZUSA2 = smlua_model_util_get_id("azusa2_geo")
E_MODEL_AZUSA3 = smlua_model_util_get_id("azusa3_geo")
E_MODEL_NATSU = smlua_model_util_get_id("natsu_geo")
E_MODEL_KAZUSA2 = smlua_model_util_get_id("kazusa2_geo")
E_MODEL_NATSU2 = smlua_model_util_get_id("natsu2_geo")
E_MODEL_JTF = smlua_model_util_get_id("jtf_geo")
E_MODEL_MINE = smlua_model_util_get_id("mine_geo")
E_MODEL_TSURUGI = smlua_model_util_get_id("tsurugi_geo")
E_MODEL_ICHIKA = smlua_model_util_get_id("ichika_geo")
E_MODEL_NAGISA = smlua_model_util_get_id("nagisa_geo")
E_MODEL_NAGISA2 = smlua_model_util_get_id("nagisa2_geo")
E_MODEL_NAGISA3 = smlua_model_util_get_id("nagisa_swim_geo")
E_MODEL_MIKA = smlua_model_util_get_id("mika_geo")
E_MODEL_MIKA2 = smlua_model_util_get_id("mika_swim_geo")
E_MODEL_HIFUMI = smlua_model_util_get_id("hifumi_geo")
E_MODEL_HIFUMI2 = smlua_model_util_get_id("hifumi_swim_geo")
E_MODEL_KOHARU = smlua_model_util_get_id("koharu_geo")
E_MODEL_KOHARU_SWIM = smlua_model_util_get_id("koharu2_geo")
E_MODEL_HANAKO = smlua_model_util_get_id("hanako_geo")
E_MODEL_HANAKO2 = smlua_model_util_get_id("hanako_swim_geo")
E_MODEL_AIRI = smlua_model_util_get_id("airi_geo")
E_MODEL_AIRI2 = smlua_model_util_get_id("airi2_geo")
E_MODEL_YOSHIMI = smlua_model_util_get_id("yoshimi_geo")
E_MODEL_YOSHIMI2 = smlua_model_util_get_id("yoshimi2_geo")
E_MODEL_HASUMI = smlua_model_util_get_id("hasumi_geo")
E_MODEL_SEIA = smlua_model_util_get_id("seia_geo")
E_MODEL_SEIA2 = smlua_model_util_get_id("seia2_geo")
E_MODEL_SUZUMI = smlua_model_util_get_id("suzumi_geo")
E_MODEL_SUZUMI2 = smlua_model_util_get_id("suzumi2_geo")
E_MODEL_SAKURAKO = smlua_model_util_get_id("sakurako_geo")
E_MODEL_REISA = smlua_model_util_get_id("reisa_geo")
E_MODEL_REISA2 = smlua_model_util_get_id("reisa2_geo")
E_MODEL_HANAE = smlua_model_util_get_id("hanae_geo")
E_MODEL_HANAE2 = smlua_model_util_get_id("hanae2_geo")
E_MODEL_UI = smlua_model_util_get_id("ui_geo")
E_MODEL_UI2 = smlua_model_util_get_id("ui2_geo")
E_MODEL_HINATA = smlua_model_util_get_id("hinata_geo")
E_MODEL_SHIMIKO = smlua_model_util_get_id("shimiko_geo")
E_MODEL_RABU = smlua_model_util_get_id("rabu_geo")
E_MODEL_SERINA = smlua_model_util_get_id("serina_geo")
E_MODEL_SERINA2 = smlua_model_util_get_id("serina2_geo")

-- ================================================================
-- Custom Texture Icons
-- ================================================================
-- ================
-- Trinity
-- ================
TEX_MARI = get_texture_info("Mari_Icon")
TEX_SPMARI = get_texture_info("Mari_Gym_Icon")
TEX_IMARI = get_texture_info("imari_icon")
TEX_KAZUSA = get_texture_info("Kazusa_Icon")
TEX_AZUSA = get_texture_info("Azusa_Icon")
TEX_AZUSA2 = get_texture_info("azusa_swim_icon")
TEX_NATSU = get_texture_info("Natsu_Icon")
TEX_NATSU2 = get_texture_info("bnatsuicon")
TEX_JTF = get_texture_info("Jtf_Icon")
TEX_MINE = get_texture_info("Mine_Icon")
TEX_TSURUGI = get_texture_info("Tsurugi_Icon")
TEX_ICHIKA = get_texture_info("Ichika_Icon")
TEX_NAGISA = get_texture_info("nagisaicon")
TEX_NAGISA2 = get_texture_info("nagisaswimicon")
TEX_MIKA = get_texture_info("mikaicon")
TEX_MIKA2 = get_texture_info("mikaswimicon")
TEX_HIFUMI = get_texture_info('hifumi_icon')
TEX_HIFUMI2 = get_texture_info('HifumiSwimsuit_Icon')
TEX_KOHARU = get_texture_info('koharu_icon')
TEX_KOHARU_SWIM = get_texture_info("koharu2_icon")
TEX_HANAKO = get_texture_info('hanako_icon')
TEX_HANAKO2 = get_texture_info('hanakoswimicon')
TEX_AIRI = get_texture_info('airi_icon')
TEX_AIRI2 = get_texture_info('airi2icon')
TEX_YOSH = get_texture_info('yosh_icon')
TEX_YOSH2 = get_texture_info('byosh_icon')
TEX_HASUMI = get_texture_info('hasumi_icon')
TEX_SEIA = get_texture_info('seiaicon')
TEX_SEIA2 = get_texture_info('seiaswimicon')
TEX_SUZUMI = get_texture_info('suzumi_icon')
TEX_SUZUMI2 = get_texture_info('suzumi2_icon')
TEX_SAKURAKO = get_texture_info("sakurakoicon")
TEX_REISA = get_texture_info("Reisa_Icon")
TEX_REISA2 = get_texture_info("Reisa2_Icon")
TEX_HANAE = get_texture_info("hanae_icon")
TEX_HANAE2 = get_texture_info("christmashanae_icon")
TEX_UI = get_texture_info("uiicon")
TEX_UI2 = get_texture_info("Ui_Swimsuit_Icon")
TEX_HINATA = get_texture_info("hinataicon")
TEX_SHIMIKO = get_texture_info("shimiko_icon")
TEX_RABU = get_texture_info("Rabu_Icon")
TEX_SERINA = get_texture_info("serina_icon")
TEX_SERINA2 = get_texture_info("christmasserina_icon")