PACK_ID = 4
TEXT_MOD_NAME = "Blue Archive Vol " .. PACK_ID

-- ================================================================
-- Custom Models
-- ================================================================
E_MODEL_FUBUKI = smlua_model_util_get_id("fubuki_geo")
E_MODEL_FUBUKI2 = smlua_model_util_get_id("fubuki2_geo")
E_MODEL_KIRINO = smlua_model_util_get_id("kirino_geo")
E_MODEL_KIRINO_SW = smlua_model_util_get_id("kirino_sw_geo")
E_MODEL_KANNA = smlua_model_util_get_id("kanna_geo")
E_MODEL_KANNA2 = smlua_model_util_get_id("kanna_swim_geo")
E_MODEL_MOE = smlua_model_util_get_id("moe_geo")
E_MODEL_MOE2 = smlua_model_util_get_id("moe_swim_geo")
E_MODEL_MIYAKO = smlua_model_util_get_id("miyako_geo")
E_MODEL_MIYAKO2 = smlua_model_util_get_id("miyako2_geo")
E_MODEL_SAKI = smlua_model_util_get_id("saki_geo")
E_MODEL_SAKI2 = smlua_model_util_get_id("saki_swim_geo")
E_MODEL_MIYU = smlua_model_util_get_id("miyu_geo")
E_MODEL_MIYU_GOMI = smlua_model_util_get_id("miyu_gomi_geo")
E_MODEL_MIYU2 = smlua_model_util_get_id("miyu2_geo")
E_MODEL_SSMG = smlua_model_util_get_id("sukeban_smg_geo")
E_MODEL_SHMG = smlua_model_util_get_id("skbhmg_geo")
E_MODEL_HG01 = smlua_model_util_get_id("HG01_geo")
E_MODEL_AKIRA = smlua_model_util_get_id("akira_geo")
E_MODEL_AKIRA2 = smlua_model_util_get_id("akira2_geo")
E_MODEL_RABU = smlua_model_util_get_id("rabu_geo")
E_MODEL_SENSEI = smlua_model_util_get_id("sensei_geo")
E_MODEL_VALK = smlua_model_util_get_id("valk_geo")
-- ================================================================
-- Custom Texture Icons
-- ================================================================
TEX_FUBUKI = get_texture_info("Fubuki_Icon")
TEX_FUBUKI2 = get_texture_info("fubukiswimsuit_icon")
TEX_KIRINO = get_texture_info("kirinoicon")
TEX_SKIRINO = get_texture_info("skirinoicon")
TEX_KANNA = get_texture_info("kannaicon")
TEX_KANNA2 = get_texture_info("kannaswimicon")
TEX_MOE = get_texture_info("moeicon")
TEX_MOE2 = get_texture_info("moeswimicon")
TEX_MIYAKO = get_texture_info("miyakoicon")
TEX_MIYAKO2 = get_texture_info("miyakoswimicon")
TEX_MIYU = get_texture_info("Miyu_Icon")
TEX_MIYU2 = get_texture_info("MiyuSwimsuit_Icon")
TEX_SAKI = get_texture_info("sakiicon")
TEX_SAKI2 = get_texture_info("sakiswimicon")
TEX_SSMG = get_texture_info("ssmgicon")
TEX_SHMG = get_texture_info("Sukeban_HMG1")
TEX_HG01 = get_texture_info("hg01icon")
TEX_AKIRA = get_texture_info("Akira_Icon")
TEX_RABU = get_texture_info("Rabu_Icon")
TEX_SENSEI = get_texture_info('senseiicon')
TEX_VALK = get_texture_info('valkicon')
