-- BA Pack 2
-- Character Voice Tables

VT_FUUKA = {
  [CHAR_SOUND_ATTACKED] = { 'fuuka_eh1.mp3' },
  [CHAR_SOUND_DOH] = 'fuuka_eh1.mp3', -- Bonk into walls
  -- [CHAR_SOUND_DYING] = {'.mp3'},
  -- [CHAR_SOUND_EEUH] = {'.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'.mp3'},
  [CHAR_SOUND_HAHA] = { 'fuuka_laugh.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'fuuka_star1.mp3', 'fuuka_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'fuuka_jump2.mp3' },                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'fuuka_grab.mp3',                               -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = '.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'fuuka_ls1.mp3', 'fuuka_ls2.mp3' },      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'fuuka_levelexit.mp3' },                  -- Getting up after thrown out of level
  -- [CHAR_SOUND_ON_FIRE] = {'.mp3'}, -- Touch Fire
  [CHAR_SOUND_OOOF] = 'fuuka_eh2.mp3',                                -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'fuuka_eh1.mp3',                               -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'fuuka_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'fuuka_jump1.mp3',    -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'fuuka_atk2.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'fuuka_bthrow1.mp3', 'fuuka_bthrow2.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'fuuka_jump4.mp3',                                         -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'fuuka_atk2.mp3' },                                     -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = '.mp3', -- Falling
  [CHAR_SOUND_WAH2] = { 'fuuka_atk3.mp3' },                           -- Throw Object
  [CHAR_SOUND_WHOA] = 'fuuka_are1.mp3',                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'fuuka_grab.mp3' },                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'fuuka_atk3.mp3' },              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'fuuka_jump3.mp3', 'fuuka_atk1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'silent.mp3'},
}

VT_NERU = {
  [CHAR_SOUND_ATTACKED] = { 'neru_dmg1.mp3', 'neru_dmg2.mp3' },
  [CHAR_SOUND_DYING] = 'neru_dying.mp3',
  [CHAR_SOUND_DOH] = 'neru_dmg2.mp3',
  [CHAR_SOUND_PUNCH_HOO] = 'neru_kick.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = 'neru_groundPound.mp3',
  [CHAR_SOUND_HAHA] = 'neru_laugh.mp3',
  [CHAR_SOUND_HAHA_2] = 'neru_laugh.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'neru_letsGo.mp3', 'neru_letsGo2.mp3' },
  [CHAR_SOUND_HOOHOO] = { 'neru_jump2.mp3', 'neru_jump2_2.mp3' },
  [CHAR_SOUND_YAHOO] = 'neru_kick.mp3',
  [CHAR_SOUND_MAMA_MIA] = { 'neru_levelFail.mp3', 'neru_levelFail2.mp3' },
  [CHAR_SOUND_HRMM] = 'neru_grab.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'neru_star.mp3', 'neru_star2.mp3' },
  [CHAR_SOUND_UH] = 'neru_eh.mp3',
  [CHAR_SOUND_OOOF] = 'neru_dmg1.mp3',
  [CHAR_SOUND_YAH_WAH_HOO] = { 'neru_punch1.mp3' },
  [CHAR_SOUND_OOOF2] = 'neru_dmg1.mp3',
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = 'neru_jump3.mp3',
  [CHAR_SOUND_PUNCH_YAH] = 'neru_punch1.mp3',
  [CHAR_SOUND_PUNCH_WAH] = 'neru_punch2.mp3',
  [CHAR_SOUND_WAAAOOOW] = 'neru_falling.mp3',
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'neru_bowser.mp3' },
  [CHAR_SOUND_WHOA] = 'neru_ledgeGrab.mp3',
  [CHAR_SOUND_ON_FIRE] = 'neru_falling.mp3',
  [CHAR_SOUND_IMA_TIRED] = 'neru_sleepy.mp3',
}
VT_TOKI = {
  [CHAR_SOUND_ATTACKED] = { 'toki_dmg1.mp3', 'toki_dmg2.mp3', 'toki_dmg3.mp3' },
  [CHAR_SOUND_DYING] = 'toki_dying.mp3',
  [CHAR_SOUND_DOH] = 'toki_dmg1.mp3',
  [CHAR_SOUND_PUNCH_HOO] = 'toki_kick.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = 'toki_groundPound.mp3',
  [CHAR_SOUND_HAHA] = 'toki_pyon.mp3',
  [CHAR_SOUND_HAHA_2] = 'toki_pyon.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'toki_letsGo.mp3' },
  [CHAR_SOUND_HOOHOO] = { 'toki_jump2.mp3' },
  [CHAR_SOUND_YAHOO] = 'toki_longjump.mp3',
  [CHAR_SOUND_MAMA_MIA] = { 'toki_levelFail.mp3' },
  [CHAR_SOUND_HRMM] = 'toki_grab.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'toki_star.mp3', 'toki_star2.mp3' },
  [CHAR_SOUND_UH] = 'toki_ah.mp3',
  [CHAR_SOUND_OOOF] = 'toki_dmg2.mp3',
  [CHAR_SOUND_YAH_WAH_HOO] = { 'toki_jump1.mp3' },
  [CHAR_SOUND_OOOF2] = 'toki_dmg2.mp3',
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = 'toki_yahoo.mp3',
  [CHAR_SOUND_PUNCH_YAH] = 'toki_punch1.mp3',
  [CHAR_SOUND_PUNCH_WAH] = 'toki_punch2.mp3',
  [CHAR_SOUND_WAAAOOOW] = 'toki_falling.mp3',
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'toki_bowser.mp3' },
  [CHAR_SOUND_WHOA] = 'toki_ledgeGrab.mp3',
  [CHAR_SOUND_ON_FIRE] = 'toki_falling.mp3',
  [CHAR_SOUND_IMA_TIRED] = 'toki_sleepy.mp3',
}

VT_SHIROKO = {
  [CHAR_SOUND_ATTACKED] = { 'srk_dmg1.mp3', 'srk_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'srk_eh.mp3',         -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'srk_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'srk_climb.mp3' }, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'.mp3'},
  [CHAR_SOUND_HAHA] = { 'srk_ok.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'srk_star1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'srk_atk1.mp3' },      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'srk_ok.mp3',              -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'srk_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'srk_ls1.mp3' },    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'srk_getup.mp3' },   -- Getting up after thrown out of level
  -- [CHAR_SOUND_ON_FIRE] = {'wkm_dmg4.mp3'}, -- Touch Fire
  [CHAR_SOUND_OOOF] = 'srk_eh.mp3',              -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'srk_dmg1.mp3',           -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'srk_atk6.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'srk_atk4.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'srk_atk1.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'srk_bthrow1.mp3', 'srk_bthrow2.mp3' }, -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'srk_nn1.mp3' },                           -- Boing
  [CHAR_SOUND_UH] = 'srk_nn2.mp3',                                         -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'srk_nn1.mp3' },                                    -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = '.mp3', -- Falling
  [CHAR_SOUND_WAH2] = { 'srk_throw1.mp3', 'srk_throw2.mp3' },    -- Throw Object
  [CHAR_SOUND_WHOA] = 'srk_nn2.mp3',                             -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'srk_atk3.mp3' },                       -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'srk_atk3.mp3' },           -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'srk_atk2.mp3', 'srk_atk5.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'shun_yawn.mp3'},
}

VT_SHIROKOTERROR = {
  [CHAR_SOUND_ATTACKED] = { 'srk_dmg1.mp3', 'srk_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'srk_eh.mp3',         -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'srkt_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'srk_climb.mp3' }, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'.mp3'},
  [CHAR_SOUND_HAHA] = { 'srk_ok.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'srkt_star1.mp3', 'srkt_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'srk_atk1.mp3' },                         -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'srk_ok.mp3',                                 -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'srkt_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'srk_ls1.mp3' },                       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'srkt_getup.mp3' },                     -- Getting up after thrown out of level
  -- [CHAR_SOUND_ON_FIRE] = {'wkm_dmg4.mp3'}, -- Touch Fire
  [CHAR_SOUND_OOOF] = 'srk_eh.mp3',                                 -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'srk_dmg1.mp3',                              -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'srkt_atk1.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'srk_atk4.mp3',      -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'srk_atk1.mp3',      -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'srk_bthrow1.mp3', 'srk_bthrow2.mp3' }, -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'srk_nn1.mp3' },                           -- Boing
  [CHAR_SOUND_UH] = 'srk_nn2.mp3',                                         -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'srk_nn1.mp3' },                                    -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = '.mp3', -- Falling
  [CHAR_SOUND_WAH2] = { 'srk_throw1.mp3', 'srk_throw2.mp3' },    -- Throw Object
  [CHAR_SOUND_WHOA] = 'srk_nn2.mp3',                             -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'srk_atk3.mp3' },                       -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'srk_atk3.mp3' },           -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'srk_atk2.mp3', 'srk_atk5.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'shun_yawn.mp3'},
}

VT_KASUMI = {
  [CHAR_SOUND_ATTACKED] = { 'ksm_dmg1.mp3', 'ksm_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'ksm_oh1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'ksm_getup.mp3' },
  -- [CHAR_SOUND_EEUH] = {'srk_climb.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'ksm_bagon.mp3' },
  [CHAR_SOUND_HAHA] = { 'ksm_wonderful.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'ksm_laugh2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'ksm_jump1.mp3' },      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'ksm_grab.mp3',             -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'ksm_sigh.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'ksm_ls1.mp3' },     -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'ksm_getup.mp3' },    -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'ksm_dmg4.mp3' },      -- Touch Fire
  [CHAR_SOUND_OOOF] = 'ksm_hm2.mp3',              -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'ksm_dmg3.mp3',            -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'ksm_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'ksm_atk4.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'ksm_atk2.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'ksm_bthrow1.mp3' }, -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'ksm_boing.mp3' },      -- Boing
  [CHAR_SOUND_UH] = 'ksm_oh1.mp3',                      -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'ksm_jump1.mp3' },               -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = '.mp3', -- Falling
  [CHAR_SOUND_WAH2] = { 'ksm_surprise.mp3' },                    -- Throw Object
  [CHAR_SOUND_WHOA] = 'ksm_ledgegrab.mp3',                       -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'ksm_longjump.mp3' },                   -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'ksm_atk3.mp3' },           -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'ksm_atk5.mp3', 'ksm_atk1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'shun_yawn.mp3'},
}
VT_MUTSUKI = {
  [CHAR_SOUND_ATTACKED] = { 'mutsuki_dmg1.mp3', 'mutsuki_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'mutsuki_dmg1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'mutsuki_dying.mp3' },
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'mutsuki_groundPound.mp3' },
  [CHAR_SOUND_HAHA] = { 'mutsuki_laugh.mp3' },                                     -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'mutsuki_star.mp3', 'mutsuki_star2.mp3' },           -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'mutsuki_jump2.mp3' },                                   -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'mutsuki_grab.mp3',                                          -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'srk_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'mutsuki_letsGo.mp3' },                               -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'mutsuki_levelFail.mp3', 'mutsuki_levelFail2.mp3' },   -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = 'mutsuki_nani.mp3',                                       -- Touch Fire
  [CHAR_SOUND_OOOF] = 'mutsuki_ah.mp3',                                            -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'mutsuki_dmg3.mp3',                                         -- Landing After a Bonk + Thrown out of level
  [CHAR_SOUND_PUNCH_HOO] = { 'mutsuki_kick.mp3' },                                 -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'mutsuki_punch2.mp3',                                   -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'mutsuki_punch1.mp3',                                   -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'mutsuki_bowser1.mp3', 'mutsuki_bowser2.mp3' }, -- Bowser Throw
  [CHAR_SOUND_UH] = 'mutsuki_uh.mp3',                                              -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'mutsuki_nani.mp3',                                      -- Falling
  [CHAR_SOUND_WHOA] = 'mutsuki_ah.mp3',                                            -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'mutsuki_kufufu.mp3' },                                   -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'mutsuki_jump3.mp3' },                        -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'mutsuki_jump1.mp3' },                              -- 1st Jump(s)
}
VT_KAYOKO = {
  [CHAR_SOUND_ATTACKED] = { 'kayoko_dmg1.mp3', 'kayoko_dmg2.mp3', 'kayoko_dmg3.mp3' },
  [CHAR_SOUND_DOH] = 'kayoko_dmg1.mp3',                                   -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'kayoko_dying.mp3' },
  [CHAR_SOUND_EEUH] = { 'kayoko_ledgeUp.mp3' },                           -- Slow Get up from ledge
  [CHAR_SOUND_GROUND_POUND_WAH] = 'kayoko_groundPound.mp3',
  [CHAR_SOUND_HAHA] = { 'kayoko_sigh.mp3' },                              -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'kayoko_star.mp3', 'kayoko_star2.mp3' },    -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'kayoko_jump2.mp3' },                           -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'kayoko_grab.mp3',                                  -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'kayoko_yawn.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'kayoko_letsGo.mp3', 'kayoko_letsGo2.mp3' }, -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'kayoko_levelFail.mp3' },                     -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'kayoko_burn.mp3' },                           -- Touch Fire
  [CHAR_SOUND_OOOF] = 'srk_eh.mp3',                                       -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'kayoko_dmg3.mp3',                                 -- Landing After a Bonk + Thrown out of level
  [CHAR_SOUND_PUNCH_HOO] = { 'kayoko_kick.mp3' },                         -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'kayoko_punch2.mp3',                           -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'kayoko_jump1.mp3',                            -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'kayoko_bowser.mp3' },                 -- Bowser Throw
  [CHAR_SOUND_UH] = 'kayoko_uh.mp3',                                      -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'kayoko_burn.mp3',                              -- Falling
  [CHAR_SOUND_WHOA] = 'kayoko_eh.mp3',                                    -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'kayoko_yahoo.mp3' },                            -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'kayoko_yahoo.mp3' },                -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'kayoko_jump1.mp3' },                      -- 1st Jump(s)
}
VT_HARUKA = {
  [CHAR_SOUND_ATTACKED] = { 'haruka_dmg1.mp3', 'haruka_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'haruka_eh.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'haruka_dying.mp3' },
  -- [CHAR_SOUND_EEUH] = {'srk_climb.mp3'}, -- Slow Get up from ledge
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'haruka_yahoo.mp3' },
  [CHAR_SOUND_HAHA] = { 'haruka_laugh.mp3' },                                   -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'haruka_star.mp3' },                              -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'haruka_jump2.mp3' },                                 -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'haruka_jump2.mp3',                                       -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'srk_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'haruka_letsGo.mp3' },                             -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'haruka_levelFail.mp3' },                           -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'haruka_falling.mp3' },                              -- Touch Fire
  [CHAR_SOUND_OOOF] = 'haruka_eh.mp3',                                          -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'haruka_dmg2.mp3',                                       -- Landing After a Bonk + Thrown out of level
  [CHAR_SOUND_PUNCH_HOO] = { 'haruka_kick.mp3' },                               -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'haruka_punch2.mp3',                                 -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'haruka_jump1.mp3',                                  -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'haruka_bowser2.mp3' }, -- Bowser Throw
  [CHAR_SOUND_UH] = 'haruka_eh.mp3',                                            -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'haruka_falling.mp3',                                 -- Falling
  [CHAR_SOUND_WHOA] = 'haruka_ledgeGrab.mp3',                                   -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'haruka_yahoo.mp3' },                                  -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'haruka_yahoo.mp3' },                      -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'haruka_jump1.mp3', 'haruka_jump1_1.mp3' },      -- 1st Jump(s)
}

VT_AKO = {
  [CHAR_SOUND_ATTACKED] = { 'ako_dmg2.mp3', 'ako_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'ako_eh1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'ako_dead1.mp3', 'ako_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {'srk_climb.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'ksm_bagon.mp3'},
  [CHAR_SOUND_HAHA] = { 'ako_laugh1.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'ako_star1.mp3', 'ako_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'ako_jump4.mp3' },                      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'ako_pickup.mp3',                           -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'ksm_sigh.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'ako_ls1.mp3' },                     -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'ako_getup.mp3', 'ako_dmg3.mp3' },    -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'ako_onfire.mp3' },                    -- Touch Fire
  [CHAR_SOUND_OOOF] = 'ako_ara1.mp3',                             -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'ako_dmg2.mp3',                            -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'ako_atk2.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'ako_atk3.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'ako_atk4.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'ako_bthrow1.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'ksm_boing.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'ako_eh2.mp3',                      -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'ako_jump2.mp3' },               -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = '.mp3', -- Falling
  [CHAR_SOUND_WAH2] = { 'ako_throw1.mp3' },                       -- Throw Object
  [CHAR_SOUND_WHOA] = 'ako_huh1.mp3',                             -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'ako_atk2.mp3' },                        -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'ako_laugh1.mp3' },          -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'ako_atk1.mp3', 'ako_jump4.mp3' }, -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'ako_yawn.mp3' },
}

VT_MIMORI = {
  [CHAR_SOUND_ATTACKED] = { 'mmr_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'mmr_ah2.mp3',            -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'mmr_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'mmr_slowclimb.mp3' }, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'ksm_bagon.mp3'},
  [CHAR_SOUND_HAHA] = { 'mmr_laugh1.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'mmr_star1.mp3', 'mmr_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'mmr_jump3.mp3' },                      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'mmr_grab1.mp3',                            -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'ksm_sigh.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'mmr_ls1.mp3' },                     -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'mmr_getup1.mp3', 'mmr_getup2.mp3' }, -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'mmr_dmg1.mp3' },                      -- Touch Fire
  [CHAR_SOUND_OOOF] = 'mmr_ah2.mp3',                              -- Grabbed by Chuckya
  -- [CHAR_SOUND_OOOF2] = 'ako_dmg2.mp3', -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'mmr_jump3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'mmr_atk1.mp3',      -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'mmr_atk2.mp3',      -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'mmr_throw1.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'ksm_boing.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'mmr_ah2.mp3',                     -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'mmr_jump1.mp3' },              -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = '.mp3', -- Falling
  [CHAR_SOUND_WAH2] = { 'mmr_throw1.mp3' },                        -- Throw Object
  [CHAR_SOUND_WHOA] = 'mmr_ah1.mp3',                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'mmr_yo.mp3' },                           -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'mmr_laugh1.mp3' },           -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'mmr_jump2.mp3', 'mmr_jump4.mp3' }, -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'mmr_yawn.mp3' },
}

VT_HIBIKI = {
  [CHAR_SOUND_ATTACKED] = { 'hibiki_dmg1.mp3', 'hibiki_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'hibiki_huh.mp3',                                     -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'hibiki_dying.mp3' },
  [CHAR_SOUND_EEUH] = { 'hibiki_ledgeUp.mp3' },                            -- Slow Get up from ledge
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'hibiki_groundPound.mp3' },
  [CHAR_SOUND_HAHA] = { 'hibiki_hmm.mp3' },                                -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'hibiki_star.mp3' },                         -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'hibiki_jump2.mp3' },                            -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'hibiki_hmm.mp3',                                    -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'srk_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'hibiki_letsGo.mp3' },                        -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'hibiki_levelFail.mp3' },                      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'hibiki_falling.mp3' },                         -- Touch Fire
  [CHAR_SOUND_OOOF] = 'hibiki_huh.mp3',                                    -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'hibiki_dmg3.mp3',                                  -- Landing After a Bonk + Thrown out of level
  [CHAR_SOUND_PUNCH_HOO] = { 'hibiki_kick.mp3' },                          -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'hibiki_punch2.mp3',                            -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'hibiki_punch1.mp3',                            -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'hibiki_bowser.mp3' },                  -- Bowser Throw
  [CHAR_SOUND_UH] = 'hibiki_huh.mp3',                                      -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'hibiki_falling.mp3',                            -- Falling
  [CHAR_SOUND_WHOA] = 'hibiki_huh.mp3',                                    -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'hibiki_iko.mp3' },                               -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'hibiki_kick.mp3' },                  -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'hibiki_jump1.mp3', 'hibiki_jump1_1.mp3' }, -- 1st Jump(s)
}

VT_MINE = {
  [CHAR_SOUND_ATTACKED] = { 'mine_dmg1.mp3', 'mine_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'mine_ah1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'mine_dead1.mp3', 'mine_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {'mmr_slowclimb.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'ksm_bagon.mp3'},
  -- [CHAR_SOUND_HAHA] = {'mmr_laugh1.mp3'}, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'mine_star1.mp3', 'mine_star2.mp3', 'mine_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'mine_atk1.mp3' },                                          -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                       -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'ksm_sigh.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'mine_ls1.mp3' },                                        -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'mine_getup1.mp3', 'mine_getup2.mp3' },                   -- Getting up after thrown out of level
  -- [CHAR_SOUND_ON_FIRE] = {'mmr_dmg1.mp3'}, -- Touch Fire
  [CHAR_SOUND_OOOF] = 'mine_ah1.mp3',                                                 -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'mine_dmg1.mp3',                                               -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'mine_atk2.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'mine_atk1.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'mine_atk3.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'mine_bthrow1.mp3' }, -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },  -- Boing
  -- [CHAR_SOUND_UH] = 'mmr_ah2.mp3', -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'mine_atk3.mp3' },                -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = '.mp3', -- Falling
  [CHAR_SOUND_WAH2] = { 'mine_atk1.mp3' },              -- Throw Object
  -- [CHAR_SOUND_WHOA] = 'mmr_ah1.mp3', -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'mine_atk4.mp3' },             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'mine_atk4.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'mine_jump1.mp3' },      -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'mmr_yawn.mp3'},
}

VT_TSURUGI = {
  [CHAR_SOUND_ATTACKED] = { 'tsurugi_dmg1.mp3', 'tsurugi_dmg2.mp3', 'tsurugi_dmg3.mp3' },
  [CHAR_SOUND_DOH] = 'tsurugi_dmg2.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'tsurugi_dying.mp3' },
  [CHAR_SOUND_HRMM] = 'tsurugi_eh.mp3',  -- Object Pick-up
  -- [CHAR_SOUND_EEUH] = {'mmr_slowclimb.mp3'}, -- Slow Get up from ledge
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'tsurugi_groundPound.mp3' },
  [CHAR_SOUND_HAHA] = { 'tsurugi_laugh.mp3' },              -- Landing after backflip
  [CHAR_SOUND_HAHA_2] = { 'tsurugi_laugh.mp3' },
  [CHAR_SOUND_HERE_WE_GO] = { 'tsurugi_star.mp3' },         -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'tsurugi_jump2.mp3' },            -- 2nd Jump + Dive Attack
  [CHAR_SOUND_IMA_TIRED] = 'tsurugi_sleepy.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'tsurugi_letsGo.mp3' },        -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'tsurugi_levelFail.mp3' },      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'tsurugi_burn.mp3' },            -- Touch Fire
  [CHAR_SOUND_OOOF] = 'tsurugi_dmg3.mp3',                   -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'tsurugi_dmg3.mp3',                  -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'tsurugi_kick.mp3' },          -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'tsurugi_punch2.mp3',            -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'tsurugi_punch1.mp3',            -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'tsurugi_bowser.mp3' },  -- Bowser Throw
  [CHAR_SOUND_UH] = 'tsurugi_eh.mp3',                       -- Drop off of ledge + Fall off Ledge
  -- [CHAR_SOUND_UH2] = {'tsurugi_atk3.mp3'}, -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'tsurugi_burn.mp3',               -- Falling
  [CHAR_SOUND_WHOA] = 'tsurugi_ledge.mp3',                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'tsurugi_yahoo.mp3' },             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'tsurugi_yahoo.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'tsurugi_jump1.mp3' },       -- 1st Jump(s)
}

VT_ICHIKA = {
  [CHAR_SOUND_ATTACKED] = { 'ichika_dmg2.mp3', 'ichika_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'ichika_oh1.mp3',             -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'sfx_smb3_down.mp3' },
  [CHAR_SOUND_EEUH] = { 'ichika_ledgeclimb.mp3' }, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'ksm_bagon.mp3'},
  [CHAR_SOUND_HAHA] = { 'ichika_jajan.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'ichika_star1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'ichika_atk1.mp3' },      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',     -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'ichika_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'ichika_ls1.mp3' },    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'ichika_getup.mp3' },   -- Getting up after thrown out of level
  -- [CHAR_SOUND_ON_FIRE] = {'mmr_dmg1.mp3'}, -- Touch Fire
  [CHAR_SOUND_OOOF] = 'ichika_woah.mp3',            -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'ichika_dmg1.mp3',           -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'ichika_atk1.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'ichika_atk3.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'ichika_atk2.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'ichika_bthrow.mp3' }, -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },   -- Boing
  [CHAR_SOUND_UH] = 'ichika_oh1.mp3',                     -- Drop off of ledge + Fall off Ledge
  -- [CHAR_SOUND_UH2] = {'mine_atk3.mp3'}, -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = '.mp3', -- Falling
  [CHAR_SOUND_WAH2] = { 'sfx_ssb64_itemthrow.mp3' },          -- Throw Object
  [CHAR_SOUND_WHOA] = 'ichika_ledgegrab.mp3',                 -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'ichika_longjump.mp3' },             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'ichika_longjump.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'ichika_jump1.mp3' },          -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'mmr_yawn.mp3'},
}

VT_HARUNA = {
  [CHAR_SOUND_ATTACKED] = { 'haruna_dmg1.mp3', 'haruna_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'haruna_dmg1.mp3',  -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'haruna_dying.mp3' },
  [CHAR_SOUND_HRMM] = 'haruna_grab.mp3', -- Object Pick-up
  -- [CHAR_SOUND_EEUH] = {'mmr_slowclimb.mp3'}, -- Slow Get up from ledge
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'haruna_punch2.mp3' },
  [CHAR_SOUND_HAHA] = { 'haruna_laugh.mp3' },              -- Landing after backflip
  [CHAR_SOUND_HAHA_2] = 'haruna_laugh.mp3',                -- Landing on Water after a fall
  [CHAR_SOUND_HERE_WE_GO] = { 'haruna_star.mp3' },         -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'haruna_punch2.mp3' },           -- 2nd Jump + Dive Attack
  [CHAR_SOUND_IMA_TIRED] = 'haruna_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'haruna_letsGo.mp3' },        -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'haruna_levelFail.mp3' },      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'haruna_burn.mp3' },            -- Touch Fire
  [CHAR_SOUND_OOOF] = 'haruna_eh.mp3',                     -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'haruna_dmg2.mp3',                  -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'haruna_punch1.mp3' },        -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'haruna_punch2.mp3',            -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'haruna_punch1.mp3',            -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'haruna_bowser.mp3' },  -- Bowser Throw
  [CHAR_SOUND_UH] = 'haruna_eh.mp3',                       -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'haruna_jump1.mp3' },               -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'haruna_burn.mp3',               -- Falling
  [CHAR_SOUND_WAH2] = { 'haruna_punch1.mp3' },             -- Throw Object
  [CHAR_SOUND_WHOA] = 'haruna_grab.mp3',                   -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'haruna_yahoo.mp3' },             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'haruna_jump3.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'haruna_jump1.mp3' },       -- 1st Jump(s)
}

VT_NOVOICE = {
  [CHAR_SOUND_ATTACKED] = { 'sfx_smrpg_hit1.mp3', 'sfx_smrpg_shell.mp3', 'sfx_smw_bossstun.mp3' },
  [CHAR_SOUND_DOH] = 'sfx_ml_bump.mp3',                                              -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'sfx_smb3_down.mp3' },
  [CHAR_SOUND_HERE_WE_GO] = { 'sfx_alttp_item.mp3', 'sfx_smrpg_specialflower.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_LETS_A_GO] = { 'sfx_smb3_levelselect.mp3' },                           -- Level Select
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                      -- Object Pick-up
  [CHAR_SOUND_HOOHOO] = { 'sfx_smw_jump.mp3' },                                      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                                    -- Touch Fire
  [CHAR_SOUND_OOOF] = 'sfx_pm64_what.mp3',                                           -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'sfx_smrpg_drop.mp3',                                         -- Landing After a Bonk + Thrown out of level + Also Bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'sfx_ssb64_atk3.mp3' },                                 -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'sfx_ssb64_atk2.mp3',                                     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'sfx_ssb64_atk1.mp3',                                     -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'sfx_smrpg_fireball.mp3' },                       -- Bowser Throw
  [CHAR_SOUND_WAH2] = { 'sfx_ssb64_itemthrow.mp3' },                                 -- Throw Object
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                                           -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                                   -- Falling
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                              -- Boing
  [CHAR_SOUND_WHOA] = 'sfx_ssb64_ledge.mp3',                                         -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'sfx_ssb64_superjump.mp3' },                                -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'sfx_ssb64_superjump.mp3' },                    -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'sfx_smw_jump.mp3' },                                 -- 1st Jump(s)
}

VT_KIRINO = {
  [CHAR_SOUND_ATTACKED] = { 'kirino_dmg1.mp3', 'kirino_dmg2.mp3', 'kirino_dmg3.mp3' },
  [CHAR_SOUND_DOH] = 'kirino_dmg1.mp3',  -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'kirino_dying.mp3' },
  [CHAR_SOUND_HRMM] = 'kirino_grab.mp3', -- Object Pick-up
  -- [CHAR_SOUND_EEUH] = {'mmr_slowclimb.mp3'}, -- Slow Get up from ledge
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'kirino_groundPound.mp3' },
  [CHAR_SOUND_HAHA] = { 'kirino_laugh.mp3' },                  -- Landing after backflip
  [CHAR_SOUND_HAHA_2] = 'kirino_laugh.mp3',                    -- Landing on Water after a fall
  [CHAR_SOUND_HERE_WE_GO] = { 'kirino_star.mp3' },             -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'kirino_jump2.mp3' },                -- 2nd Jump + Dive Attack
  -- [CHAR_SOUND_IMA_TIRED] = 'haruna_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'kirino_letsGo.mp3' },            -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'kirino_levelFail.mp3' },          -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'kirino_burn.mp3' },                -- Touch Fire
  [CHAR_SOUND_OOOF] = 'kirino_eh.mp3',                         -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'kirino_dmg2.mp3',                      -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'kirino_kick.mp3' },              -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'kirino_punch2.mp3',                -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'kirino_punch1.mp3',                -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'kirino_groundPound.mp3' }, -- Bowser Throw
  [CHAR_SOUND_UH] = 'kirino_eh.mp3',                           -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'kirino_jump1.mp3' },                   -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'kirino_burn.mp3',                   -- Falling
  [CHAR_SOUND_WAH2] = { 'kirino_jump1.mp3' },                  -- Throw Object
  [CHAR_SOUND_WHOA] = 'kirino_grab.mp3',                       -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'kirino_yahoo.mp3' },                 -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'kirino_yahoo.mp3' },     -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'kirino_jump1.mp3' },           -- 1st Jump(s)
}

VT_KANNA = {
  [CHAR_SOUND_ATTACKED] = { 'kanna_dmg3.mp3', 'kanna_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'kanna_bonk.mp3',                                -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'kanna_dead1.mp3' },
  [CHAR_SOUND_HERE_WE_GO] = { 'kanna_star1.mp3' },                    -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'kanna_atk2.mp3' },                         -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                       -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'kanna_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'kanna_ls1.mp3' },                       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'kanna_getup.mp3' },                      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                     -- Touch Fire
  [CHAR_SOUND_OOOF] = 'kanna_dmg2.mp3',                               -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'kanna_dmg1.mp3',                              -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'kanna_atk3.mp3' },                      -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'kanna_atk2.mp3',                          -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'kanna_atk1.mp3',                          -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'kanna_bthrow1.mp3' },             -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },               -- Boing
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                            -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                    -- Falling
  [CHAR_SOUND_WAH2] = { 'kanna_throw.mp3' },                          -- Throw Object
  [CHAR_SOUND_WHOA] = 'sfx_ssb64_ledge.mp3',                          -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'kanna_longjump.mp3' },                      -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'kanna_atk3.mp3' },              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'kanna_atk1.mp3', 'kanna_jump1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'mmr_yawn.mp3'},
}

VT_MOE = {
  [CHAR_SOUND_ATTACKED] = { 'moe_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'moe_are1.mp3',                                               -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'moe_dead1.mp3', 'moe_dead2.mp3' },
  [CHAR_SOUND_HAHA] = { 'moe_laugh2.mp3', 'moe_laugh1.mp3' },                      -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'moe_star1.mp3', 'moe_star2.mp3', 'moe_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'moe_atk3.mp3' },                                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                    -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'moe_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'moe_ls1.mp3' },                                      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'moe_levelexit.mp3' },                                 -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'moe_burn.mp3' },                                       -- Touch Fire
  [CHAR_SOUND_OOOF] = 'moe_huh.mp3',                                               -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'moe_dmg1.mp3',                                             -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'moe_atk3.mp3' },                                     -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'moe_atk2.mp3',                                         -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'moe_atk1.mp3',                                         -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'moe_bthrow.mp3' },                             -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'moe_laugh3.mp3' },                                -- Boing
  [CHAR_SOUND_UH] = 'moe_ah1.mp3',                                                 -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'moe_falling.mp3',                                       -- Falling
  [CHAR_SOUND_WAH2] = { 'moe_bthrow.mp3' },                                        -- Throw Object
  [CHAR_SOUND_WHOA] = 'moe_huh.mp3',                                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'moe_atk3.mp3', 'moe_laugh3.mp3' },                       -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'moe_atk3.mp3' },                             -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'moe_jump1.mp3', 'moe_atk1.mp3' },                  -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'moe_yawn.mp3' },
}

VT_MIYAKO = {
  [CHAR_SOUND_ATTACKED] = { 'miyako_dmg1.mp3', 'miyako_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'miyako_bonk.mp3',                                 -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'miyako_dead1.mp3' },
  [CHAR_SOUND_HAHA] = { 'miyako_laugh.mp3' },                           -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'miyako_star1.mp3', 'miyako_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'miyako_atk1.mp3' },                          -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                         -- Object Pick-up
  [CHAR_SOUND_LETS_A_GO] = { 'miyako_ls1.mp3' },                        -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'miyako_levelexit.mp3' },                   -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'miyako_burn.mp3' },                         -- Touch Fire
  [CHAR_SOUND_OOOF] = 'miyako_eh1.mp3',                                 -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'miyako_dmg3.mp3',                               -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'miyako_atk4.mp3' },                       -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'miyako_atk2.mp3',                           -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'miyako_atk1.mp3',                           -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'miyako_throw.mp3' },                -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                 -- Boing
  [CHAR_SOUND_UH] = 'miyako_eh1.mp3',                                   -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'miyako_atk1.mp3' },                             -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                      -- Falling
  [CHAR_SOUND_WAH2] = { 'miyako_throw.mp3' },                           -- Throw Object
  [CHAR_SOUND_WHOA] = 'sfx_ssb64_ledge.mp3',                            -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'miyako_atk4.mp3' },                           -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'miyako_atk4.mp3' },               -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'miyako_atk3.mp3' },                     -- 1st Jump(s)
}

VT_SAKI = {
  [CHAR_SOUND_ATTACKED] = { 'saki_dmg1.mp3', 'saki_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'saki_bonk.mp3',                               -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'saki_dead.mp3' },
  [CHAR_SOUND_HERE_WE_GO] = { 'saki_star1.mp3', 'saki_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'saki_atk5.mp3' },                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                     -- Object Pick-up
  [CHAR_SOUND_LETS_A_GO] = { 'saki_ls1.mp3' },                      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'saki_levelexit.mp3' },                 -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'saki_dmg3.mp3' },                       -- Touch Fire
  [CHAR_SOUND_OOOF] = 'saki_bonk.mp3',                              -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'saki_dmg1.mp3',                             -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'saki_atk2.mp3' },                     -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'saki_atk4.mp3',                         -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'saki_atk1.mp3',                         -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'saki_throw2.mp3' },             -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },             -- Boing
  [CHAR_SOUND_UH] = 'saki_drop.mp3',                                -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'saki_atk3.mp3' },                           -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'saki_drop.mp3',                          -- Falling
  [CHAR_SOUND_WAH2] = { 'saki_throw1.mp3' },                        -- Throw Object
  [CHAR_SOUND_WHOA] = 'saki_ledgegrab.mp3',                         -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'saki_atk2.mp3' },                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'saki_atk2.mp3' },             -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'saki_atk3.mp3', 'saki_atk1.mp3' },  -- 1st Jump(s)
}

VT_MOMIJI = {
  [CHAR_SOUND_ATTACKED] = { 'momiji_uu.mp3', 'momiji_hidoi.mp3' },
  [CHAR_SOUND_DOH] = 'momiji_wah.mp3',                                  -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'momiji_dead.mp3' },
  [CHAR_SOUND_HAHA] = { 'momiji_desu1.mp3' },                           -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'momiji_star1.mp3' },                     -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'momiji_atk3.mp3' },                          -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                         -- Object Pick-up
  [CHAR_SOUND_LETS_A_GO] = { 'momiji_levelselect.mp3' },                -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'momiji_mou.mp3', 'momiji_levelexit.mp3' }, -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'momiji_fire.mp3' },                         -- Touch Fire
  [CHAR_SOUND_OOOF] = 'momiji_wah.mp3',                                 -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'momiji_uu.mp3',                                 -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'momiji_atk1.mp3' },                       -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'momiji_atk2.mp3',                           -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'momiji_atk5.mp3',                           -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'momiji_bthrow.mp3' },               -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                 -- Boing
  [CHAR_SOUND_UH] = 'momiji_wah.mp3',                                   -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'momiji_atk3.mp3' },                             -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'momiji_fall.mp3',                            -- Falling
  [CHAR_SOUND_WAH2] = { 'momiji_bthrow.mp3' },                          -- Throw Object
  [CHAR_SOUND_WHOA] = 'momiji_ledgegrab.mp3',                           -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'momiji_atk3.mp3' },                           -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'momiji_atk3.mp3' },               -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'momiji_atk5.mp3', 'momiji_atk4.mp3' },  -- 1st Jump(s)
}

VT_IBUKI = {
  [CHAR_SOUND_ATTACKED] = { 'ibuki_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'ibuki_ledge.mp3',                                                 -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'ibuki_dead2.mp3', 'ibuki_dead1.mp3' },
  [CHAR_SOUND_HAHA] = { 'ibuki_jaan.mp3' },                                             -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'ibuki_star1.mp3', 'ibuki_star2.mp3' },                   -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'ibuki_atk2.mp3' },                                           -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                         -- Object Pick-up
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'ibuki_atk3.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'ibuki_ls.mp3' },                                          -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'ibuki_levelexit.mp3' },                                    -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'ibuki_fire.mp3' },                                          -- Touch Fire
  [CHAR_SOUND_OOOF] = 'ibuki_hm.mp3',                                                   -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'ibuki_dmg1.mp3',                                                -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'ibuki_atk3.mp3' },                                        -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'ibuki_atk4.mp3',                                            -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'ibuki_atk1.mp3',                                            -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'ibuki_bthrow.mp3' },                                -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                                 -- Boing
  [CHAR_SOUND_UH] = 'ibuki_ledge.mp3',                                                  -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'ibuki_jump1.mp3' },                                             -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'ibuki_dmg2.mp3',                                             -- Falling
  [CHAR_SOUND_WAH2] = { 'ibuki_throw.mp3' },                                            -- Throw Object
  [CHAR_SOUND_WHOA] = 'ibuki_ah1.mp3',                                                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'ibuki_longjump.mp3' },                                        -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'ibuki_longjump.mp3' },                            -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'ibuki_jump1.mp3', 'ibuki_atk1.mp3', 'ibuki_atk4.mp3' }, -- 1st Jump(s)
}

VT_NAGISA = {
  [CHAR_SOUND_ATTACKED] = { 'nagisa_dmg3.mp3', 'nagisa_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'nagisa_eh1.mp3',                                                    -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'nagisa_dead1.mp3', 'nagisa_dead2.mp3' },
  [CHAR_SOUND_HAHA] = { 'nagisa_laugh1.mp3' },                                            -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'nagisa_star2.mp3', 'nagisa_star1.mp3' },                   -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'nagisa_atk5.mp3' },                                            -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                           -- Object Pick-up
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'nagisa_atk4.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'nagisa_ls1.mp3' },                                          -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'nagisa_levelexit.mp3' },                                     -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'nagisa_burn.mp3' },                                           -- Touch Fire
  [CHAR_SOUND_OOOF] = 'nagisa_ara1.mp3',                                                  -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'nagisa_dmg1.mp3',                                                 -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'nagisa_atk3.mp3' },                                         -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'nagisa_atk2.mp3',                                             -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'nagisa_atk1.mp3',                                             -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'nagisa_bthrow1.mp3' },                                -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                                   -- Boing
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                                                -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'nagisa_atk1.mp3' },                                               -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                                        -- Falling
  [CHAR_SOUND_WAH2] = { 'nagisa_throw1.mp3', 'nagisa_throw2.mp3' },                       -- Throw Object
  [CHAR_SOUND_WHOA] = 'nagisa_ara2.mp3',                                                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'nagisa_longjump.mp3' },                                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'nagisa_atk4.mp3', 'nagisa_longjump.mp3' },          -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'nagisa_atk1.mp3', 'nagisa_atk6.mp3', 'nagisa_atk7.mp3' }, -- 1st Jump(s)
}

VT_MIKA = {
  [CHAR_SOUND_ATTACKED] = { 'mika_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'mika_are2.mp3',                                               -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'mika_dead1.mp3' },
  [CHAR_SOUND_HAHA] = { 'mika_laugh.mp3' },                                         -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'mika_star1.mp3', 'mika_star2.mp3' },                 -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'mika_atk5.mp3' },                                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                     -- Object Pick-up
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'mika_atk2.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'mika_ls1.mp3' },                                      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'mika_wow.mp3' },                                       -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'mika_burn.mp3' },                                       -- Touch Fire
  [CHAR_SOUND_OOOF] = 'mika_hmm.mp3',                                               -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'mika_dmg2.mp3',                                             -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'mika_atk2.mp3' },                                     -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'mika_atk3.mp3',                                         -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'mika_atk1.mp3',                                         -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'mika_useless.mp3' },                            -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                             -- Boing
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                                          -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'mika_atk1.mp3' },                                           -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'mika_burn.mp3',                                          -- Falling
  [CHAR_SOUND_WAH2] = { 'mika_throw.mp3' },                                         -- Throw Object
  [CHAR_SOUND_WHOA] = 'mika_are1.mp3',                                              -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'mika_longjump.mp3' },                                     -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'mika_longjump.mp3' },                         -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'mika_atk1.mp3', 'mika_atk3.mp3', 'mika_atk4.mp3' }, -- 1st Jump(s)
}

VT_MIYU = {
  [CHAR_SOUND_ATTACKED] = { 'miyu_dmg.mp3', 'miyu_dmg2.mp3' },
  [CHAR_SOUND_DYING] = 'miyu_dying.mp3',
  [CHAR_SOUND_DOH] = 'miyu_dmg3.mp3',
  [CHAR_SOUND_PUNCH_HOO] = 'miyu_kick.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = 'miyu_kick.mp3',
  [CHAR_SOUND_HAHA] = 'miyu_laugh.mp3',
  [CHAR_SOUND_HAHA_2] = 'miyu_laugh.mp3',
  [CHAR_SOUND_LETS_A_GO] = 'miyu_letsGo.mp3',
  [CHAR_SOUND_HOOHOO] = 'miyu_jump2.mp3',
  [CHAR_SOUND_YAHOO] = 'miyu_kick.mp3',
  [CHAR_SOUND_MAMA_MIA] = 'miyu_levelFail.mp3',
  [CHAR_SOUND_HRMM] = 'miyu_hmm.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'miyu_star.mp3' },
  [CHAR_SOUND_UH] = 'miyu_huh.mp3',
  [CHAR_SOUND_OOOF] = 'miyu_dmg2.mp3',
  [CHAR_SOUND_YAH_WAH_HOO] = { 'miyu_jump1.mp3', "miyu_jump1_1.mp3" },
  [CHAR_SOUND_OOOF2] = 'miyu_dmg2.mp3',
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = 'miyu_hyuu.mp3',
  [CHAR_SOUND_PUNCH_YAH] = 'miyu_punch1.mp3',
  [CHAR_SOUND_PUNCH_WAH] = 'miyu_punch2.mp3',
  [CHAR_SOUND_WAAAOOOW] = 'miyu_falling.mp3',
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'miyu_bowser.mp3', "miyu_bowser2.mp3" },
  [CHAR_SOUND_WHOA] = 'miyu_ledgeGrab.mp3',
  [CHAR_SOUND_ON_FIRE] = 'miyu_burn.mp3',
  [CHAR_SOUND_IMA_TIRED] = 'miyu_yawn.mp3',
}

VT_FUBUKI = {
  [CHAR_SOUND_ATTACKED] = { 'fubuki_hurt1.mp3', 'fubuki_hurt2.mp3' },
  [CHAR_SOUND_DOH] = 'fubuki_eh2.mp3',             -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'fubuki_donothing.mp3' },
  [CHAR_SOUND_EEUH] = { 'fubuki_ledgegetup.mp3' }, -- Slow Get up from ledge
  [CHAR_SOUND_HAHA] = 'fubuki_laugh.mp3',                -- Landing after backflip
  [CHAR_SOUND_HAHA_2] = 'fubuki_laugh.mp3',              -- Landing on Water after a fall
  [CHAR_SOUND_HERE_WE_GO] = { 'fubuki_chocodonut.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'fubuki_jump2.mp3',              -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'fubuki_pickup.mp3',               -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'fubuki_nemu.mp3',
  [CHAR_SOUND_LETS_A_GO] = 'fubuki_levelselect.mp3',     -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'fubuki_annoying1.mp3',        -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'fubuki_hurt1.mp3' },         -- Touch Fire
  [CHAR_SOUND_OOOF] = 'fubuki_hurt2.mp3',
  [CHAR_SOUND_OOOF2] = 'fubuki_hurt1.mp3',               -- Landing After a Bonk + Thrown out of level
  [CHAR_SOUND_PUNCH_HOO] = { 'fubuki_attack1.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'fubuki_attack4.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'fubuki_attack6.mp3',     -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'fubuki_bowserthrow.mp3' }, -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'fubuki_laugh.mp3' },          -- Boing
  [CHAR_SOUND_UH] = 'fubuki_eh3.mp3',                          -- Drop off of ledge
  [CHAR_SOUND_UH2] = { 'fubuki_attack7.mp3' },                 -- Quick Ledge Get-Up
  [CHAR_SOUND_UH2_2] = 'fubuki_te.mp3',                        -- Landing after Long Jump
  --[CHAR_SOUND_WAAAOOOW] = nil, -- Falling
  [CHAR_SOUND_WAH2] = 'fubuki_attack1.mp3',                    -- Throw Object
  [CHAR_SOUND_WHOA] = 'fubuki_ledgegrab.mp3',                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'fubuki_donut.mp3' },                 -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'fubuki_laugh.mp3' },     -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = {'fubuki_jump1.mp3', 'fubuki_attack2.mp3', 'fubuki_attack4.mp3'}, -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = 'fubuki_yawn.mp3'
}