-- BA Pack 4
-- Character Voice Tables

VT_RENGE = {
  [CHAR_SOUND_ATTACKED] = { 'renge_dmg2.mp3', 'renge_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'renge_oh.mp3',              -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'renge_dying.mp3' },
  [CHAR_SOUND_HAHA] = { 'renge_laugh.mp3' },      -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'renge_star.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'renge_jump2.mp3' },    -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'renge_grab.mp3',           -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'renge_sleepy.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'renge_yahoo.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'renge_letsGo.mp3' },       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'renge_levelFail.mp3' },     -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'renge_falling.mp3' },        -- Touch Fire
  [CHAR_SOUND_OOOF] = 'renge_dmg3.mp3',                  -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'renge_dmg1.mp3',                 -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'renge_kick.mp3' },         -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'renge_punch2.mp3',           -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'renge_punch1.mp3',           -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'renge_bowser.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                 -- Boing
  -- [CHAR_SOUND_UH] = 'renge_are.mp3', 								-- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'renge_punch1.mp3' },                                                -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'renge_falling.mp3',                                              -- Falling
  [CHAR_SOUND_WAH2] = { 'renge_throw.mp3' },                                                -- Throw Object
  [CHAR_SOUND_WHOA] = 'renge_grab.mp3',                                                     -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'renge_yahoo.mp3' },                                               -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'renge_yahoo.mp3', 'renge_kick.mp3' },                 -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'renge_punch1.mp3', 'renge_punch2.mp3', 'renge_jump2.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'renge_sleepy.mp3'},
}

VT_KIKYOU = {
  [CHAR_SOUND_ATTACKED] = { 'kikyou_dmg2.mp3', 'kikyou_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'kikyou_ugh.mp3',             -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'kikyou_dying.mp3' },
  [CHAR_SOUND_HAHA] = { 'kikyou_laugh.mp3' },      -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'kikyou_star.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'kikyou_punch2.mp3' },   -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'kikyou_grab.mp3',           -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'kikyou_sleepy.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'kikyou_yahoo.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'kikyou_letsGo.mp3' },                      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'kikyou_levelFail.mp3' },                    -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'kikyou_ugh.mp3' },                           -- Touch Fire
  [CHAR_SOUND_OOOF] = 'kikyou_ugh.mp3',                                  -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'kikyou_dmg1.mp3',                                -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'kikyou_yahoo.mp3' },                       -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'kikyou_punch2.mp3',                          -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'kikyou_kick.mp3',                            -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'kikyou_bowser.mp3' },                -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                 -- Boing
  [CHAR_SOUND_UH] = 'kikyou_dmg2.mp3',                                   -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'kikyou_jump1.mp3' },                             -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'kikyou_dmg1.mp3',                             -- Falling
  [CHAR_SOUND_WAH2] = { 'kikyou_throw.mp3' },                            -- Throw Object
  [CHAR_SOUND_WHOA] = 'kikyou_grab.mp3',                                 -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'kikyou_yahoo.mp3' },                           -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'kikyou_yahoo.mp3' },               -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'kikyou_jump1.mp3', 'kikyou_jump2.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'kikyou_yawn.mp3'},
}

VT_NAGUSA = {
  [CHAR_SOUND_ATTACKED] = { 'nagusa_dmg1.mp3', 'nagusa_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'nagusa_ah.mp3',                                   -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'nagusa_KO1.mp3' },
  [CHAR_SOUND_HAHA] = { 'nagusa_laugh.mp3' },                           -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'nagusa_star1.mp3', 'nagusa_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'nagusa_atk5.mp3' },                          -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                         -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'nagusa_rest.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'nagusa_atk5.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'nagusa_levelselect.mp3' }, -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'nagusa_levelexit.mp3' },    -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },        -- Touch Fire
  [CHAR_SOUND_OOOF] = 'nagusa_huh.mp3',                  -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'nagusa_dmg1.mp3',                -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'nagusa_atk2.mp3' },        -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'nagusa_atk4.mp3',            -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'nagusa_atk3.mp3',            -- 1st Punch
  ---[CHAR_SOUND_SO_LONGA_BOWSER] = { 'nothing' },                -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = { 'nothing' },                 -- Boing
  [CHAR_SOUND_UH] = 'nagusa_huh.mp3',                                                     -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'nagusa_atk4.mp3' },                                               -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'nagusa_dmg1.mp3',                                              -- Falling
  [CHAR_SOUND_WAH2] = { 'sfx_ssb64_itemthrow.mp3' },                                      -- Throw Object
  [CHAR_SOUND_WHOA] = 'nagusa_ah.mp3',                                                    -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'nagusa_atk2.mp3' },                                             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'nagusa_atk2.mp3' },                                 -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'nagusa_atk3.mp3', 'nagusa_atk6.mp3', 'nagusa_atk1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'nothing'},
}

VT_YUKARI = {
  [CHAR_SOUND_ATTACKED] = { 'yukari_dmg3.mp3', 'yukari_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'yukari_bonk.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'yukari_dead1.mp3', 'yukari_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {'ichika_ledgeclimb.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'ksm_bagon.mp3'},
  [CHAR_SOUND_HAHA] = { 'yukari_desuno.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'yukari_star1.mp3', 'yukari_star2.mp3', 'yukari_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'yukari_atk1.mp3' },                                              -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'yukari_objectgrab.mp3',                                              -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'ichika_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'yukari_ls1.mp3' },                                            -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'yukari_getup.mp3' },                                           -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'yukari_burn.mp3' },                                             -- Touch Fire
  [CHAR_SOUND_OOOF] = 'yukari_huh.mp3',                                                     -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'yukari_dmg3.mp3',                                                   -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'yukari_atk2.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'yukari_atk1.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'yukari_atk4.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'yukari_throw2.mp3', 'yukari_throw1.mp3' }, -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'yukari_huhun.mp3' },                          -- Boing
  [CHAR_SOUND_UH] = 'yukari_huh.mp3',                                          -- Drop off of ledge + Fall off Ledge
  -- [CHAR_SOUND_UH2] = {'mine_atk3.mp3'}, -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'yukari_dmg2.mp3',                           -- Falling
  [CHAR_SOUND_WAH2] = { 'yukari_throw1.mp3' },                         -- Throw Object
  [CHAR_SOUND_WHOA] = 'sfx_ssb64_ledge.mp3',                           -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'yukari_atk3.mp3' },                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'yukari_atk2.mp3' },              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'yukari_atk4.mp3', 'yukari_atk1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'mmr_yawn.mp3'},
}

VT_HINA = {
  [CHAR_SOUND_ATTACKED] = { 'hina_dmg2.mp3', 'hina_dmg5.mp3' },
  [CHAR_SOUND_DOH] = 'hina_dmg1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'hina_dead1.mp3', 'hina_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {nil,}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = nil, -- Game Over Voiceline
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'hina_atk3.mp3' },
  -- [CHAR_SOUND_HAHA] = nil, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = nil, -- Intro Voiceline
  [CHAR_SOUND_HERE_WE_GO] = { 'hina_starget1.mp3', 'hina_starget2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'hina_atk3.mp3',                                  -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'hina_grab.mp3',                                    -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'hina_sigh.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'hina_levelselect.mp3' },                    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'hina_annoying1.mp3' },                       -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'hina_what.mp3' },                             -- Touch Fire
  [CHAR_SOUND_OOOF] = 'hina_dmg1.mp3',                                    -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'hina_dmg1.mp3',                                   -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {nil,}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = nil,
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = nil,
  [CHAR_SOUND_PUNCH_HOO] = { 'hina_atk4.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'hina_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'hina_atk1.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = nil,
  -- [CHAR_SOUND_SNORING2] = nil,
  -- [CHAR_SOUND_SNORING3] = nil,
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'hina_nomercy.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = nil, -- Boing
  [CHAR_SOUND_UH] = 'hina_nn.mp3',                       -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'hina_atk3.mp3' },                -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = nil, -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = nil, -- Falling
  [CHAR_SOUND_WAH2] = 'hina_throw.mp3',                 -- Throw Object
  [CHAR_SOUND_WHOA] = 'hina_ledgegrab.mp3',             -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'hina_atk5.mp3' },             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'hina_atk5.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'hina_atk2.mp3' }        -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = nil,
}

VT_REISA = {
  [CHAR_SOUND_ATTACKED] = { 'reisa_dmg2.mp3', 'reisa_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'reisa_huh1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'reisa_dead.mp3' },
  --[CHAR_SOUND_EEUH] = nil, -- Slow Get up from ledge
  --[CHAR_SOUND_GAME_OVER] = nil,
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'reisa_atk6.mp3' },
  [CHAR_SOUND_HAHA] = 'reisa_desu.mp3', -- Landing after backflip
  --[CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  --[CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'reisa_starget1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'reisa_jump1.mp3',            -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'reisa_pickup.mp3',             -- Object Pick-up
  --[CHAR_SOUND_IMA_TIRED] = nil,
  [CHAR_SOUND_LETS_A_GO] = 'reisa_levelselect.mp3',   -- Level Select
  --[CHAR_SOUND_MAMA_MIA] = nil, -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'reisa_dmg3.mp3' },        -- Touch Fire
  [CHAR_SOUND_OOOF] = 'reisa_ah1.mp3',
  [CHAR_SOUND_OOOF2] = 'reisa_dmg1.mp3',              -- Landing After a Bonk + Thrown out of level
  --[CHAR_SOUND_PANTING] = nil, -- Low Health
  --[CHAR_SOUND_PANTING_COLD] = nil,
  --[CHAR_SOUND_PRESS_START_TO_PLAY] = nil,
  [CHAR_SOUND_PUNCH_HOO] = { 'reisa_atk1.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'reisa_atk4.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'reisa_atk2.mp3',     -- 1st Punch
  --[CHAR_SOUND_SNORING1] = nil,
  --[CHAR_SOUND_SNORING2] = nil,
  --[CHAR_SOUND_SNORING3] = nil,
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'reisa_bowserthrow2.mp3', 'reisa_bowserthrow1.mp3' }, -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'reisa_hisatsu.mp3' },                                   -- Boing
  [CHAR_SOUND_UH] = 'reisa_ah1.mp3',                                                     -- Drop off of ledge
  [CHAR_SOUND_UH2] = { 'reisa_atk7.mp3' },                                               -- Quick Ledge Get-Up
  --[CHAR_SOUND_UH2_2] = nil, -- Landing after Long Jump
  --[CHAR_SOUND_WAAAOOOW] = nil, -- Falling
  [CHAR_SOUND_WAH2] = 'reisa_throw.mp3',                                                 -- Throw Object
  [CHAR_SOUND_WHOA] = 'reisa_ledgegrab.mp3',                                             -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'reisa_longjump.mp3' },                                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'reisa_jump4.mp3' },                                -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'reisa_jump3.mp3', 'reisa_jump2.mp3', 'reisa_atk5.mp3' }, -- 1st Jump(s)
  --[CHAR_SOUND_YAWNING] = nil,
}

VT_SAKURAKO = {
  [CHAR_SOUND_ATTACKED] = { 'sakurako_dmg5.mp3', 'sakurako_dmg1.mp3', 'sakurako_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'sakurako_bonk.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'sakurako_dead1.mp3' },
  --[CHAR_SOUND_EEUH] = nil, -- Slow Get up from ledge
  --[CHAR_SOUND_GAME_OVER] = nil,
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'sakurako_jump3.mp3' },
  [CHAR_SOUND_HAHA] = 'sakurako_heehee.mp3', -- Landing after backflip
  --[CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  --[CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'sakurako_star2.mp3' },                        -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'sakurako_jump3.mp3',                                -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                              -- Object Pick-up
  --[CHAR_SOUND_IMA_TIRED] = nil,
  [CHAR_SOUND_LETS_A_GO] = 'reisa_levelselect.mp3',                          -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'sakurako_levelexit.mp3',                          -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'sakurako_dmg3.mp3' },                            -- Touch Fire
  [CHAR_SOUND_OOOF] = 'sakurako_huh.mp3',
  [CHAR_SOUND_OOOF2] = 'sakurako_dmg4.mp3',                                  -- Landing After a Bonk + Thrown out of level
  [CHAR_SOUND_PUNCH_HOO] = { 'sakurako_atk1.mp3' },                          -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'sakurako_atk2.mp3',                              -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'sakurako_atk3.mp3',                              -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'sakurako_bthrow.mp3' },                  -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                      -- Boing
  [CHAR_SOUND_UH] = 'sakurako_drop.mp3',                                     -- Drop off of ledge
  [CHAR_SOUND_UH2] = { 'sakurako_atk2.mp3' },                                -- Quick Ledge Get-Up
  --[CHAR_SOUND_UH2_2] = nil, -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'sakurako_fall.mp3',                               -- Falling
  [CHAR_SOUND_WAH2] = 'sakurako_atk1.mp3',                                   -- Throw Object
  [CHAR_SOUND_WHOA] = 'sakurako_ledge.mp3',                                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'sakurako_longjump.mp3' },                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'sakurako_atk1.mp3' },                  -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'sakurako_jump1.mp3', 'sakurako_jump2.mp3' }, -- 1st Jump(s)
  --[CHAR_SOUND_YAWNING] = nil,
}

VT_WAKAMO = {
  [CHAR_SOUND_ATTACKED] = { 'wkm_dmg1.mp3', 'wkm_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'wkm_ara1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'wkm_dead1.mp3' },
  -- [CHAR_SOUND_EEUH] = {'young_slowclimb.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'.mp3'},
  [CHAR_SOUND_HAHA] = { 'wkm_laugh3.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'wkm_star1.mp3', 'wkm_star2.mp3', 'wkm_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'wkm_atk4.mp3' },                                        -- 2nd Jump + Dive Attack
  -- [CHAR_SOUND_HRMM] = 'young_heavy.mp3', -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'young_imatired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'wkm_ls1.mp3' },  -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'wkm_getup.mp3' }, -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'wkm_dmg4.mp3' },   -- Touch Fire
  [CHAR_SOUND_OOOF] = 'wkm_ara2.mp3',          -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'wkm_dmg6.mp3',         -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'wkm_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'wkm_atk1.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'wkm_atk2.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'wkm_bthrow1.mp3', 'wkm_bthrow2.mp3' }, -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'wkm_laugh2.mp3' },                        -- Boing
  -- [CHAR_SOUND_UH] = 'young_idk.mp3', -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'wkm_atk2.mp3' },                                   -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = '.mp3', -- Falling
  [CHAR_SOUND_WAH2] = { 'wkm_throw1.mp3' },            -- Throw Object
  [CHAR_SOUND_WHOA] = 'wkm_ara1.mp3',                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'wkm_atk3.mp3' },             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'wkm_atk3.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'wkm_atk2.mp3' },       -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'shun_yawn.mp3'},
}

VT_HANAE = {
  [CHAR_SOUND_ATTACKED] = { 'Hanae_ATTACKED1.ogg', 'Hanae_ATTACKED2.ogg' },
  [CHAR_SOUND_DOH] = 'Hanae_BONK.ogg',                                       -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'Hanae_DYING.ogg' },
  [CHAR_SOUND_HAHA] = { 'Hanae_HAHA.ogg' },                                  -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'Hanae_HEREWEGO.ogg', 'Hanae_HEREWEGO2.ogg' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'Hanae_HOOHOO.ogg' },                              -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                              -- Object Pick-up
  --[CHAR_SOUND_IMA_TIRED] = '',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'Hanae_GROUND_POUND_WAH.ogg' },
  [CHAR_SOUND_LETS_A_GO] = { 'Hanae_LETSAGO.ogg' },                              -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'Hanae_MAMA_MIA.ogg' },                              -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'Hanae_OOOF2.ogg' },                                  -- Touch Fire
  [CHAR_SOUND_OOOF] = 'Hanae_OOOF.ogg',                                          -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'Hanae_OOOF2.ogg',                                        -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'Hanae_PUNCH_HOO.ogg' },                            -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'Hanae_PUNCH_WAH.ogg',                                -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'Hanae_PUNCH_YAH.ogg',                                -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'Hanae_SO_LONGA_BOWSER.ogg' },                -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'Hanae_TWIRL_BOUNCE.ogg' },                      -- Boing
  [CHAR_SOUND_UH] = 'Hanae_UH.ogg',                                              -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'Hanae_UH.ogg' },                                         -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'Hanae_WAAAOOOW.ogg',                                  -- Falling
  [CHAR_SOUND_WAH2] = { 'Hanae_WAH2.ogg' },                                      -- Throw Object
  [CHAR_SOUND_WHOA] = 'Hanae_WHOA.ogg',                                          -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'Hanae_YAHOO.ogg' },                                    -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'Hanae_TWIRL_BOUNCE.ogg' },                 -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'Hanae_PUNCH_YAH.ogg', 'Hanae_YAH_WAH_HOO.ogg' }, -- 1st Jump(s)
  --[CHAR_SOUND_YAWNING] = {''},
}

VT_UI = {
  [CHAR_SOUND_ATTACKED] = { 'ui_dmg1.mp3', 'ui_dmg2.mp3', 'ui_dmg3.mp3' },
  [CHAR_SOUND_DOH] = 'ui_eh.mp3',    -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'ui_dying.mp3' },
  [CHAR_SOUND_HRMM] = 'ui_grab.mp3', -- Object Pick-up
  -- [CHAR_SOUND_EEUH] = {'mmr_slowclimb.mp3'}, -- Slow Get up from ledge
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'ui_punch2.mp3' },
  [CHAR_SOUND_HAHA] = { 'ui_oh.mp3' },                                             -- Landing after backflip
  [CHAR_SOUND_HAHA_2] = 'ui_oh.mp3',                                               -- Landing on Water after a fall
  [CHAR_SOUND_HERE_WE_GO] = { 'ui_star.mp3' },                                     -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'ui_jump2.mp3' },                                        -- 2nd Jump + Dive Attack
  -- [CHAR_SOUND_IMA_TIRED] = 'ksm_sigh.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'ui_letsGo.mp3' },                                    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'ui_levelFail.mp3' },                                  -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'ui_groundPound.mp3' },                                 -- Touch Fire
  [CHAR_SOUND_OOOF] = 'ui_eh.mp3',                                                 -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'ui_dmg3.mp3',                                              -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'ui_kick.mp3' },                                      -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'ui_punch2.mp3',                                        -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'ui_punch1.mp3',                                        -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'ui_jump3.mp3' },                               -- Bowser Throw
  [CHAR_SOUND_UH] = 'ui_eh.mp3',                                                   -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'ui_jump1.mp3' },                                           -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'ui_dmg2.mp3',                                           -- Falling
  [CHAR_SOUND_WAH2] = { 'ui_punch1.mp3' },                                         -- Throw Object
  [CHAR_SOUND_WHOA] = 'ui_ledge.mp3',                                              -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'ui_yahoo.mp3' },                                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'ui_jump3.mp3' },                             -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'ui_punch1.mp3', 'ui_jump2.mp3', 'ui_punch2.mp3' }, -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'ui_burn.mp3' },
}

VT_PINA = {
  [CHAR_SOUND_ATTACKED] = { 'Pina_kh.ogg', 'Pina_Damage_3.ogg' },
  [CHAR_SOUND_DOH] = 'Pina_kh.ogg',                                                                    -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'Pina_defeat.ogg' },
  [CHAR_SOUND_HERE_WE_GO] = { 'Pina_hashimemashte.ogg', 'Pina_Victory_2.ogg', 'Pina_Victory_3.ogg', }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_LETS_A_GO] = { 'Pina_hashimemashte.ogg' },                                               -- Level Select
  [CHAR_SOUND_HRMM] = 'Pina_kh2.ogg',                                                                  -- Object Pick-up
  [CHAR_SOUND_HOOHOO] = { 'Pina_hai.ogg' },                                                            -- 2nd Jump + Dive Attack
  [CHAR_SOUND_ON_FIRE] = { 'Pina_Damage_2.ogg' },                                                      -- Touch Fire
  [CHAR_SOUND_OOOF] = 'Pina_ah.ogg',                                                                   -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'Pina_ah2.ogg',                                                                 -- Landing After a Bonk + Thrown out of level + Also Bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'Pina_hasha.ogg' },                                                       -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'Pina_hey.ogg',                                                             -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'Pina_yah.ogg',                                                             -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'Pina_Koki.ogg' },                                                  -- Bowser Throw
  [CHAR_SOUND_WAH2] = { 'Pina_hasha.ogg' },                                                            -- Throw Object
  [CHAR_SOUND_UH] = 'Pina_ah.ogg',                                                                     -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'Pina_Damage_3.ogg',                                                         -- Falling
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'Pina_laugh.ogg' },                                                    -- Boing
  [CHAR_SOUND_WHOA] = 'Pina_ah.ogg',                                                                   -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'Pina_hey.ogg' },                                                             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'Pina_hey.ogg' },                                                 -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'Pina_ha.ogg' },                                                        -- 1st Jump(s)
  [CHAR_SOUND_HAHA] = 'Pina_laugh.ogg',
  [CHAR_SOUND_MAMA_MIA] = 'Pina_Damage_1.ogg',
  [CHAR_SOUND_YAWNING] = 'Pina_yawn.ogg',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'Pina_skiai.ogg' },
}

VT_KANOE = {
  [CHAR_SOUND_ATTACKED] = { 'Kanoe_ATTACKED1.ogg', 'Kanoe_ATTACKED2.ogg' },
  [CHAR_SOUND_DOH] = 'Kanoe_ATTACKED1.ogg',                                                      -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'Kanoe_DYING.ogg' },
  [CHAR_SOUND_HERE_WE_GO] = { 'kanoe_star1.ogg', 'Kanoe_HEREWEGO.ogg' },                         -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                                  -- Object Pick-up
  [CHAR_SOUND_HOOHOO] = { 'Kanoe_HOOHOO.ogg' },                                                  -- 2nd Jump + Dive Attack
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'Kanoe_YAHOO.ogg' },
  [CHAR_SOUND_HAHA] = { 'Kanoe_HAHA.ogg' },                                                      -- Landing after backflip
  [CHAR_SOUND_HAHA_2] = 'Kanoe_HAHA.ogg',                                                        -- Landing on Water after a fall
  [CHAR_SOUND_LETS_A_GO] = { 'kanoe_levelselect.ogg' },                                          -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'kanoe_levelexit.ogg', 'Kanoe_DYING.ogg' },                          -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'Kanoe_ATTACKED2.ogg' },                                              -- Touch Fire
  [CHAR_SOUND_OOOF] = 'Kanoe_OOOF2.ogg',                                                         -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'Kanoe_OOOF2.ogg',                                                        -- Landing After a Bonk + Thrown out of level + Also Bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'Kanoe_HAHA.ogg' },                                                 -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'Kanoe_YAH_WAH_HOO2.ogg',                                             -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'kanoe_jump2.ogg',                                                    -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'Kanoe_HAHA.ogg' },                                           -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'Kanoe_YAHOO_WAHA_YIPPEE.ogg' },                                 -- Boing
  [CHAR_SOUND_UH] = 'Kanoe_ATTACKED1.ogg',                                                       -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'Kanoe_YAH_WAH_HOO2.ogg' },                                               -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                                               -- Falling
  [CHAR_SOUND_WAH2] = { 'Kanoe_WAH2.ogg' },                                                      -- Throw Object
  [CHAR_SOUND_WHOA] = 'Kanoe_OOOF2.ogg',                                                         -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'Kanoe_YAHOO.ogg' },                                                    -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'Kanoe_YAHOO_WAHA_YIPPEE.ogg', 'Kanoe_YAH_WAH_HOO.ogg' },   -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'kanoe_jump1.ogg', 'kanoe_jump2.ogg', 'Kanoe_YAH_WAH_HOO.ogg' }, -- 1st Jump(s)
}

VT_UMIKA = {
  [CHAR_SOUND_ATTACKED] = { 'umika_dmg1.ogg', 'umika_dmg2.ogg' }, --
  [CHAR_SOUND_DOH] = 'umika_bonk.ogg',                            -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'umika_dying.ogg' },
  --[CHAR_SOUND_EEUH] = nil, -- Slow Ledge Climb
  --[CHAR_SOUND_GAME_OVER] = nil,
  --[CHAR_SOUND_GROUND_POUND_WAH] = { 'umika_jump3.mp3' },
  [CHAR_SOUND_HAHA] = 'umika_festival.ogg', -- Landing after backflip/triple jump
  --[CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  --[CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'umika_star1.ogg', 'umika_star1.ogg' }, -- Star Get + Obtaining Power-up --
  [CHAR_SOUND_HOOHOO] = 'umika_atk1.ogg',                             -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                       -- Object Pick-up
  --[CHAR_SOUND_IMA_TIRED] = nil,
  [CHAR_SOUND_LETS_A_GO] = 'umika_levelselect.ogg',                   -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'umika_levelexit.ogg',                      -- Getting up after thrown out of level --
  [CHAR_SOUND_ON_FIRE] = { 'umika_burn.ogg' },                        -- Touch Fire --
  [CHAR_SOUND_OOOF] = 'umika_dmg1.ogg',                               --
  [CHAR_SOUND_OOOF2] = 'umika_dmg2.ogg',                              -- Landing After a Bonk + Thrown out of level --
  [CHAR_SOUND_PUNCH_HOO] = { 'umika_atk2.ogg' },                      -- Kick --
  [CHAR_SOUND_PUNCH_WAH] = 'umika_atk1.ogg',                          -- 2nd Punch --
  [CHAR_SOUND_PUNCH_YAH] = 'umika_atk4.ogg',                          -- 1st Punch --
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'umika_firework.ogg' },            -- Bowser Throw --
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },               -- Boing
  [CHAR_SOUND_UH] = 'umika_dmg1.ogg',                                 -- Let go off of ledge
  [CHAR_SOUND_UH2] = { 'umika_atk1.ogg' },                            -- Quick Ledge Climb
  [CHAR_SOUND_WAAAOOOW] = 'umika_fall.ogg',                           -- Falling
  [CHAR_SOUND_WAH2] = 'umika_firework.ogg',                           -- Throw Object --
  [CHAR_SOUND_WHOA] = 'umika_ledge.ogg',                              -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'umika_longjump.ogg' },                      -- Long Jump --
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'umika_longjump.ogg' },          -- 3rd Jump(s) --
  [CHAR_SOUND_YAH_WAH_HOO] = { 'umika_atk1.ogg', 'umika_atk3.ogg' },  -- 1st Jump(s) --
  --[CHAR_SOUND_YAWNING] = nil,
}

VT_ERI = {
  [CHAR_SOUND_ATTACKED] = { 'eri_dmg1.ogg', 'eri_dmg2.ogg' },
  [CHAR_SOUND_DOH] = 'eri_nyuhu.ogg', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'eri_dead1.ogg' },
  --[CHAR_SOUND_EEUH] = nil, -- Slow Get up from ledge
  --[CHAR_SOUND_GAME_OVER] = nil,
  --[CHAR_SOUND_GROUND_POUND_WAH] = { 'eri_jump3.mp3' },
  [CHAR_SOUND_HAHA] = 'eri_jajan.ogg', -- Landing after backflip
  --[CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  --[CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'eri_star1.ogg', 'eri_star2.ogg', 'eri_laugh2.ogg' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'eri_jump.ogg' },                                         -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                     -- Object Pick-up
  --[CHAR_SOUND_IMA_TIRED] = nil,
  [CHAR_SOUND_LETS_A_GO] = 'eri_levelselect.ogg',                                   -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'eri_uu.ogg',                                             -- Getting up after thrown out of level --
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                                   -- Touch Fire --
  [CHAR_SOUND_OOOF] = 'eri_nyuhu.ogg',                                              -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'eri_dmg1.ogg',                                              -- Landing After a Bonk + Thrown out of level
  [CHAR_SOUND_PUNCH_HOO] = { 'eri_longjump.ogg' },                                  -- Kick --
  [CHAR_SOUND_PUNCH_WAH] = 'eri_atk3.ogg',                                          -- 2nd Punch --
  [CHAR_SOUND_PUNCH_YAH] = 'eri_atk1.ogg',                                          -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'eri_bowserthrow.ogg' },                         -- Bowser Throw --
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                             -- Boing
  [CHAR_SOUND_UH] = 'eri_drop.ogg',                                                 -- Drop off of ledge
  [CHAR_SOUND_UH2] = { 'eri_atk1.ogg' },                                            -- Quick Ledge Get-Up
  --[CHAR_SOUND_UH2_2] = nil, 															-- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'eri_fall.ogg',                                           -- Falling
  [CHAR_SOUND_WAH2] = { 'eri_throw.ogg', 'eri_bowserthrow.ogg' },                   -- Throw Object
  [CHAR_SOUND_WHOA] = 'eri_oh.ogg',                                                 -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'eri_longjump.ogg' },                                      -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'eri_laugh3.ogg' },                            -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'eri_atk1.ogg', 'eri_atk2.ogg', 'eri_atk3.ogg' },    -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'eri_yawn.ogg' },
}

VT_HINATA = {
  [CHAR_SOUND_ATTACKED] = { 'hinata_dmg1.ogg', 'hinata_surprised.ogg', 'hinata_wah3.ogg' }, --
  [CHAR_SOUND_DOH] = 'hinata_surprised2.ogg',                                               -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'hinata_dead1.ogg', 'hinata_dead2.ogg' },
  --[CHAR_SOUND_EEUH] = nil, -- Slow Get up from ledge
  --[CHAR_SOUND_GAME_OVER] = nil,
  --[CHAR_SOUND_GROUND_POUND_WAH] = { 'hinata_jump3.mp3' },
  [CHAR_SOUND_HAHA] = 'hinata_great.ogg', -- Landing after backflip
  --[CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  --[CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'hinata_star1.ogg' },       -- Star Get + Obtaining Power-up --
  [CHAR_SOUND_HOOHOO] = 'hinata_atk2.ogg',                -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',           -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = { 'hinata_tired.ogg' },
  [CHAR_SOUND_LETS_A_GO] = 'hinata_levelselect.ogg',      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'hinata_levelexit.ogg',         -- Getting up after thrown out of level --
  [CHAR_SOUND_ON_FIRE] = { 'hinata_wah2.ogg' },           -- Touch Fire --
  [CHAR_SOUND_OOOF] = 'hinata_wah.ogg',
  [CHAR_SOUND_OOOF2] = 'hinata_dmg1.ogg',                 -- Landing After a Bonk + Thrown out of level --
  [CHAR_SOUND_PUNCH_HOO] = { 'hinata_atk3.ogg' },         -- Kick --
  [CHAR_SOUND_PUNCH_WAH] = 'hinata_atk1.ogg',             -- 2nd Punch --
  [CHAR_SOUND_PUNCH_YAH] = 'hinata_atk1.ogg',             -- 1st Punch --
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'hinata_bthrow.ogg' }, -- Bowser Throw --
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },   -- Boing
  [CHAR_SOUND_UH] = 'hinata_wah.ogg',                     -- Drop off of ledge
  [CHAR_SOUND_UH2] = { 'hinata_atk1.ogg' },               -- Quick Ledge Get-Up
  --[CHAR_SOUND_UH2_2] = nil, -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'hinata_fall.ogg',              -- Falling
  [CHAR_SOUND_WAH2] = 'sfx_ssb64_itemthrow.mp3',          -- Throw Object --
  [CHAR_SOUND_WHOA] = 'hinata_huh.ogg',                   -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'hinata_longjump.ogg' },         -- Long Jump --
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'hinata_atk3.ogg' }, -- 3rd Jump(s) --
  [CHAR_SOUND_YAH_WAH_HOO] = { 'hinata_atk1.ogg' },       -- 1st Jump(s) --
  --[CHAR_SOUND_YAWNING] = nil,
}
