PACK_ID = 3
TEXT_MOD_NAME = "Blue Archive Vol " .. PACK_ID

-- ================================================================
-- Custom Models
-- ================================================================
E_MODEL_SPMARI = smlua_model_util_get_id("spmari_geo")
E_MODEL_MARI = smlua_model_util_get_id("mari_geo")
E_MODEL_IMARI = smlua_model_util_get_id("imari_geo")
E_MODEL_KAZUSA = smlua_model_util_get_id("kazusa_geo")
E_MODEL_AZUSA = smlua_model_util_get_id("azusa_geo")
E_MODEL_AZUSA2 = smlua_model_util_get_id("azusa2_geo")
E_MODEL_AZUSA3 = smlua_model_util_get_id("azusa3_geo")
E_MODEL_HIYORI = smlua_model_util_get_id("hiyori_geo")
E_MODEL_HIYORI2 = smlua_model_util_get_id("hiyori2_geo")
E_MODEL_HIYORI3 = smlua_model_util_get_id("hiyori3_geo")
E_MODEL_ATSUKO = smlua_model_util_get_id("atsuko_geo")
E_MODEL_ATSUKO2 = smlua_model_util_get_id("atsuko2_geo")
E_MODEL_ATSUKO3 = smlua_model_util_get_id("atsuko3_geo")
E_MODEL_MISAKI = smlua_model_util_get_id("misaki_geo")
E_MODEL_SAORI = smlua_model_util_get_id("saori_geo")
E_MODEL_SAORI2 = smlua_model_util_get_id("saori2_geo")
E_MODEL_NATSU = smlua_model_util_get_id("natsu_geo")
E_MODEL_KAZUSA2 = smlua_model_util_get_id("kazusa2_geo")
E_MODEL_NATSU2 = smlua_model_util_get_id("natsu2_geo")
E_MODEL_JTF = smlua_model_util_get_id("jtf_geo")
E_MODEL_MINE = smlua_model_util_get_id("mine_geo")
E_MODEL_TSURUGI = smlua_model_util_get_id("tsurugi_geo")
E_MODEL_ICHIKA = smlua_model_util_get_id("ichika_geo")
E_MODEL_NAGISA = smlua_model_util_get_id("nagisa_geo")
E_MODEL_NAGISA2 = smlua_model_util_get_id("nagisa2_geo")
E_MODEL_NAGISA3 = smlua_model_util_get_id("nagisa_swim_geo")
E_MODEL_MIKA = smlua_model_util_get_id("mika_geo")
E_MODEL_MIKA2 = smlua_model_util_get_id("mika_swim_geo")
-- ================================================================
-- Custom Texture Icons
-- ================================================================
TEX_MARI = get_texture_info("Mari_Icon")
TEX_SPMARI = get_texture_info("Mari_Gym_Icon")
TEX_IMARI = get_texture_info("imari_icon")
TEX_KAZUSA = get_texture_info("Kazusa_Icon")
TEX_AZUSA = get_texture_info("Azusa_Icon")
TEX_AZUSA2 = get_texture_info("azusa_swim_icon")
TEX_HIYORI = get_texture_info("Hiyori_Icon")
TEX_HIYORI2 = get_texture_info("hiyori_swim_icon")
TEX_ATSUKO = get_texture_info("Atsuko_Unmask_Icon")
TEX_MISAKI = get_texture_info("Misaki_Unmask_Icon")
TEX_SAORI = get_texture_info("Saori_Unmask_Icon")
TEX_NATSU = get_texture_info("Natsu_Icon")
TEX_NATSU2 = get_texture_info("bnatsuicon")
TEX_JTF = get_texture_info("Jtf_Icon")
TEX_MINE = get_texture_info("Mine_Icon")
TEX_TSURUGI = get_texture_info("Tsurugi_Icon")
TEX_ICHIKA = get_texture_info("Ichika_Icon")
TEX_NAGISA = get_texture_info("nagisaicon")
TEX_NAGISA2 = get_texture_info("nagisaswimicon")
TEX_MIKA = get_texture_info("mikaicon")
TEX_MIKA2 = get_texture_info("mikaswimicon")
