-- BA Pack 3 [Trinity-Arius]
-- Character Voice Tables

-- ================================================================
-- Example
-- ================================================================
-- local VT_CHARNAME = {
--   [CHAR_SOUND_OKEY_DOKEY] = 'CharStartGame.ogg',                                       -- Starting game
--   [CHAR_SOUND_LETS_A_GO] = 'CharStartLevel.ogg',                                       -- Starting level
--   [CHAR_SOUND_GAME_OVER] = 'CharGameOver.ogg',                                         -- Game Overed
--   [CHAR_SOUND_PUNCH_YAH] = 'CharPunch1.ogg',                                           -- Punch 1
--   [CHAR_SOUND_PUNCH_WAH] = 'CharPunch2.ogg',                                           -- Punch 2
--   [CHAR_SOUND_PUNCH_HOO] = 'CharPunch3.ogg',                                           -- Punch 3
--   [CHAR_SOUND_YAH_WAH_HOO] = { 'CharJump1.ogg', 'CharJump2.ogg', 'CharJump3.ogg' },    -- First Jump Sounds
--   [CHAR_SOUND_HOOHOO] = 'CharDoubleJump.ogg',                                          -- Second jump sound
--   [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'CharTripleJump1.ogg', 'CharTripleJump2.ogg' },   -- Triple jump sounds
--   [CHAR_SOUND_UH] = 'CharBonk.ogg',                                                    -- Soft wall bonk
--   [CHAR_SOUND_UH2] = 'CharLedgeGetUp.ogg',                                             -- Quick ledge get up
--   [CHAR_SOUND_UH2_2] = 'CharLongJumpLand.ogg',                                         -- Landing after long jump
--   [CHAR_SOUND_DOH] = 'CharBonk.ogg',                                                   -- Hard wall bonk
--   [CHAR_SOUND_OOOF] = 'CharBonk.ogg',                                                  -- Attacked in air
--   [CHAR_SOUND_OOOF2] = 'CharBonk.ogg',                                                 -- Land from hard bonk
--   [CHAR_SOUND_HAHA] = 'CharTripleJumpLand.ogg',                                        -- Landing triple jump
--   [CHAR_SOUND_HAHA_2] = 'CharWaterLanding.ogg',                                        -- Landing in water from big fall
--   [CHAR_SOUND_YAHOO] = 'CharLongJump.ogg',                                             -- Long jump
--   [CHAR_SOUND_DOH] = 'CharBonk.ogg',                                                   -- Long jump wall bonk
--   [CHAR_SOUND_WHOA] = 'CharGrabLedge.ogg',                                             -- Grabbing ledge
--   [CHAR_SOUND_EEUH] = 'CharClimbLedge.ogg',                                            -- Climbing over ledge
--   [CHAR_SOUND_WAAAOOOW] = 'CharFalling.ogg',                                           -- Falling a long distance
--   [CHAR_SOUND_TWIRL_BOUNCE] = 'CharFlowerBounce.ogg',                                  -- Bouncing off of a flower spring
--   [CHAR_SOUND_GROUND_POUND_WAH] = 'CharGroundPound.ogg',                               -- Ground Pound after startup
--   [CHAR_SOUND_WAH2] = 'CharThrow.ogg',                                                 -- Throwing something
--   [CHAR_SOUND_HRMM] = 'CharLift.ogg',                                                  -- Lifting something
--   [CHAR_SOUND_HERE_WE_GO] = 'CharGetStar.ogg',                                         -- Star get
--   [CHAR_SOUND_SO_LONGA_BOWSER] = 'CharThrowBowser.ogg',                                -- Throwing Bowser
--   --DAMAGE
--   [CHAR_SOUND_ATTACKED] = 'CharDamaged.ogg',                                           -- Damaged
--   [CHAR_SOUND_PANTING] = 'CharPanting.ogg',                                            -- Low health
--   [CHAR_SOUND_PANTING_COLD] = 'CharPanting.ogg',                                       -- Getting cold
--   [CHAR_SOUND_ON_FIRE] = 'CharBurned.ogg',                                             -- Burned
--   --SLEEP SOUNDS
--   [CHAR_SOUND_IMA_TIRED] = 'CharTired.ogg',                                            -- Mario feeling tired
--   [CHAR_SOUND_YAWNING] = 'CharYawn.ogg',                                               -- Mario yawning before he sits down to sleep
--   [CHAR_SOUND_SNORING1] = 'CharSnore.ogg',                                             -- Snore Inhale
--   [CHAR_SOUND_SNORING2] = 'CharExhale.ogg',                                            -- Exhale
--   [CHAR_SOUND_SNORING3] = 'CharSleepTalk.ogg',                                         -- Sleep talking / mumbling
--   --COUGHING (USED IN THE GAS MAZE)
--   [CHAR_SOUND_COUGHING1] = 'CharCough1.ogg',                                           -- Cough take 1
--   [CHAR_SOUND_COUGHING2] = 'CharCough2.ogg',                                           -- Cough take 2
--   [CHAR_SOUND_COUGHING3] = 'CharCough3.ogg',                                           -- Cough take 3
--   --DEATH
--   [CHAR_SOUND_DYING] = 'CharDying.ogg',                                                -- Dying from damage
--   [CHAR_SOUND_DROWNING] = 'CharDrowning.ogg',                                          -- Running out of air underwater
--   [CHAR_SOUND_MAMA_MIA] = 'CharLeaveLevel.ogg'                                         -- Booted out of level
-- }

-- ================================================================
-- NPC Voices
-- Files are in Main
-- ================================================================

VT_NOVOICE = {
  [CHAR_SOUND_ATTACKED] = { 'sfx_smrpg_hit1.mp3', 'sfx_smrpg_shell.mp3', 'sfx_smw_bossstun.mp3' },
  [CHAR_SOUND_DOH] = 'sfx_ml_bump.mp3',                                              -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'sfx_smb3_down.mp3' },
  [CHAR_SOUND_HERE_WE_GO] = { 'sfx_alttp_item.mp3', 'sfx_smrpg_specialflower.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_LETS_A_GO] = { 'sfx_smb3_levelselect.mp3' },                           -- Level Select
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                      -- Object Pick-up
  [CHAR_SOUND_HOOHOO] = { 'sfx_smw_jump.mp3' },                                      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                                    -- Touch Fire
  [CHAR_SOUND_OOOF] = 'sfx_pm64_what.mp3',                                           -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'sfx_smrpg_drop.mp3',                                         -- Landing After a Bonk + Thrown out of level + Also Bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'sfx_ssb64_atk3.mp3' },                                 -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'sfx_ssb64_atk2.mp3',                                     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'sfx_ssb64_atk1.mp3',                                     -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'sfx_smrpg_fireball.mp3' },                       -- Bowser Throw
  [CHAR_SOUND_WAH2] = { 'sfx_ssb64_itemthrow.mp3' },                                 -- Throw Object
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                                           -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                                   -- Falling
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                              -- Boing
  [CHAR_SOUND_WHOA] = 'sfx_ssb64_ledge.mp3',                                         -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'sfx_ssb64_superjump.mp3' },                                -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'sfx_ssb64_superjump.mp3' },                    -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'sfx_smw_jump.mp3' },                                 -- 1st Jump(s)
}

-- ================================================================
-- Voice Tables
-- ================================================================

VT_MARI = {
  [CHAR_SOUND_ATTACKED] = { 'spmari_hurt3.mp3', 'spmari_hurt5.mp3', 'spmari_hurt2.mp3' },
  [CHAR_SOUND_DOH] = 'spmari_ah.mp3',               -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'spmari_dead.mp3' },
  [CHAR_SOUND_EEUH] = { 'spmari_ledgegetup.mp3', }, -- Slow Get up from ledge
  --[CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  --[CHAR_SOUND_GROUND_POUND_WAH] = {'silent.mp3'},
  [CHAR_SOUND_HAHA] = 'spmari_laugh.mp3', -- Landing after backflip
  --[CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  --[CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'spmari_subarashi.mp3', }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'spmari_attack6.mp3',            -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'spmari_pickup.mp3',               -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'spmari_pant.mp3',
  [CHAR_SOUND_LETS_A_GO] = 'spmari_levelselect.mp3',     -- Level Select
  --[CHAR_SOUND_MAMA_MIA] = 'silent.mp3', -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'spmari_hurt1.mp3', },        -- Touch Fire
  [CHAR_SOUND_OOOF] = 'spmari_ah.mp3',
  [CHAR_SOUND_OOOF2] = 'spmari_hurt4.mp3',               -- Landing After a Bonk + Thrown out of level
  --[CHAR_SOUND_PANTING] = {'silent.mp3',}, -- Low Health
  --[CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  --[CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'spmari_attack5.mp3', }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'spmari_attack6.mp3',      --2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'spmari_attack1.mp3',      -- 1st Punch
  --[CHAR_SOUND_SNORING1] = 'silent.mp3',
  --[CHAR_SOUND_SNORING2] = 'silent.mp3',
  --[CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'spmari_rip.mp3' },                                             --Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'spmari_laugh.mp3' },                                              -- Boing
  [CHAR_SOUND_UH] = 'spmari_uh1.mp3',                                                              --Drop off of ledge
  [CHAR_SOUND_UH2] = { 'spmari_attack7.mp3', },                                                    -- Quick Ledge Get-Up
  [CHAR_SOUND_UH2_2] = 'spmari_attack9.mp3',                                                       -- Landing after Long Jump
  --[CHAR_SOUND_WAAAOOOW] = 'silent.mp3', -- Falling
  [CHAR_SOUND_WAH2] = 'spmari_attack5.mp3',                                                        -- Throw Object
  [CHAR_SOUND_WHOA] = 'spmari_uh1.mp3',                                                            -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'spmari_attack3.mp3', },                                                  -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'spmari_attack3.mp3', },                                      -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'spmari_attack7.mp3', 'spmari_attack1.mp3', 'spmari_attack8.mp3' }, -- 1st Jump(s)
  --[CHAR_SOUND_YAWNING] = 'silent.mp3',
}
VT_KAZUSA = {
  [CHAR_SOUND_ATTACKED] = { 'kazusa_dmg1.mp3', 'kazusa_dmg3.mp3' },
  [CHAR_SOUND_DOH] = 'kazusa_what.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'kazusa_dead.mp3' },
  --[CHAR_SOUND_EEUH] = nil, -- Slow Get up from ledge
  --[CHAR_SOUND_GAME_OVER] = nil,
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'kazusa_groundpound.mp3' },
  --[CHAR_SOUND_HAHA] = nil, -- Landing after backflip
  --[CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  --[CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'kazusa_sugoi.mp3', 'kazusa_star1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'kazusa_jump4.mp3',                             -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'kazusa_pickup.mp3',                              -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'kazusa_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = 'kazusa_levelselect.mp3',                    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'kazusa_levelexit.mp3',                       -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'kazusa_what.mp3' },                         -- Touch Fire
  [CHAR_SOUND_OOOF] = 'kazusa_eh1.mp3',                                 -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'kazusa_dmg2.mp3',                               -- Landing After a Bonk + Thrown out of level
  --[CHAR_SOUND_PANTING] = nil, -- Low Health
  --[CHAR_SOUND_PANTING_COLD] = nil,
  --[CHAR_SOUND_PRESS_START_TO_PLAY] = nil,
  [CHAR_SOUND_PUNCH_HOO] = { 'kazusa_ora.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'kazusa_atk4.mp3',    -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'kazusa_atk1.mp3',    -- 1st Punch
  --[CHAR_SOUND_SNORING1] = nil,
  --[CHAR_SOUND_SNORING2] = nil,
  --[CHAR_SOUND_SNORING3] = nil,
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'kazusa_bowserthrow.mp3' },       -- Bowser Throw
  --[CHAR_SOUND_TWIRL_BOUNCE] = nil, -- Boing
  [CHAR_SOUND_UH] = 'kazusa_eh2.mp3',                                -- Drop off of ledge
  [CHAR_SOUND_UH2] = { 'kazusa_jump2.mp3' },                         -- Quick Ledge Get-Up
  --[CHAR_SOUND_UH2_2] = nil, -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = { 'kazusa_fall.mp3', 'kazusa_fall2.mp3' }, -- Falling
  [CHAR_SOUND_WAH2] = 'kazusa_ora.mp3',                              -- Throw Object
  [CHAR_SOUND_WHOA] = 'kazusa_wah2.mp3',                             -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'kazusa_jump3.mp3' },                       -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'kazusa_jump3.mp3' },           -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = {
    'kazusa_jump1.mp3', 'kazusa_jump5.mp3', 'kazusa_jump2.mp3'
  }, -- 1st Jump(s)
  --[CHAR_SOUND_YAWNING] = nil,
}
VT_AZUSA = {
  [CHAR_SOUND_ATTACKED] = { 'azusa_dmg3.mp3', 'azusa_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'azusa_eh1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'azusa_dead1.mp3', 'azusa_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {'nil',}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'nil'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'azusa_atk3.mp3' },
  [CHAR_SOUND_HAHA] = 'azusa_grab.mp3', -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'hiyori_really.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'nil',
  [CHAR_SOUND_HERE_WE_GO] = { 'azusa_starget1.mp3', 'azusa_vanitas2.mp3' }, -- Star Get + Obtaining Power-up + Bowser Throw when not full speed
  [CHAR_SOUND_HOOHOO] = 'azusa_atk5.mp3',                                   -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'azusa_grab.mp3',                                     -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'nil',
  [CHAR_SOUND_LETS_A_GO] = { 'azusa_ls1.mp3', 'azusa_vanitas3.mp3' },       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'azusa_getup.mp3',                                -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'azusa_dmg4.mp3' },                              -- Touch Fire
  [CHAR_SOUND_OOOF] = 'azusa_ah1.mp3',                                      -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'azusa_dmg5.mp3',                                    -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'nil',}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'nil',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'nil', 'nil'},
  [CHAR_SOUND_PUNCH_HOO] = { 'azusa_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'azusa_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'azusa_atk1.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'nil',
  -- [CHAR_SOUND_SNORING2] = 'nil',
  -- [CHAR_SOUND_SNORING3] = {'nil', 'nil'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'azusa_bowserthrow1.mp3' },                        -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'nil'}, -- Boing
  [CHAR_SOUND_UH] = 'azusa_ah2.mp3',                                                  -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'azusa_atk6.mp3' },                                            -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'nil', -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = { 'azusa_falling1.mp3' },                                   -- Falling
  [CHAR_SOUND_WAH2] = 'azusa_throw.mp3',                                              -- Throw Object
  [CHAR_SOUND_WHOA] = 'azusa_are1.mp3',                                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'azusa_vanitas1.mp3' },                                      -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'azusa_atk3.mp3' },                              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'azusa_atk4.mp3', 'azusa_atk5.mp3', 'azusa_atk1.mp3' } -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = 'nil',
}
VT_HIYORI = {
  [CHAR_SOUND_ATTACKED] = { 'hiyori_hurt2.mp3', 'hiyori_hurt1.mp3' },
  [CHAR_SOUND_DOH] = 'hiyori_hai.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'hiyori_dead1.mp3', 'hiyori_dead2.mp3', 'hiyori_dead3.mp3' },
  -- [CHAR_SOUND_EEUH] = {'nil',}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'nil'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'hiyori_atk4.mp3' },
  [CHAR_SOUND_HAHA] = 'hiyori_laugh1.mp3',                                    -- Landing after backflip
  [CHAR_SOUND_HAHA_2] = 'hiyori_laugh2.mp3',                                  -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'nil',
  [CHAR_SOUND_HERE_WE_GO] = { 'hiyori_starget1.mp3', 'hiyori_starget2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'hiyori_atk5.mp3',                                    -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'hiyori_pickup.mp3',                                    -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'hiyori_um.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'hiyori_ls1.mp3' },                              -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'hiyori_sorry.mp3',                                 -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'hiyori_fire.mp3' },                               -- Touch Fire
  [CHAR_SOUND_OOOF] = 'hiyori_eh1.mp3',                                       -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'hiyori_hurt2.mp3',                                    -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'nil',}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'nil',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'nil', 'nil'},
  [CHAR_SOUND_PUNCH_HOO] = { 'hiyori_atk1.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'hiyori_atk6.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'hiyori_atk3.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'nil',
  -- [CHAR_SOUND_SNORING2] = 'nil',
  -- [CHAR_SOUND_SNORING3] = {'nil', 'nil'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'hiyori_bowserthrow1.mp3' },                            -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'hiyori_laugh1.mp3' },                                     -- Boing
  [CHAR_SOUND_UH] = 'hiyori_hurt3.mp3',                                                    -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'hiyori_atk5.mp3' },                                                -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'nil', -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'hiyori_falling1.mp3',                                           -- Falling
  [CHAR_SOUND_WAH2] = 'hiyori_throw.mp3',                                                  -- Throw Object
  [CHAR_SOUND_WHOA] = 'hiyori_eh1.mp3',                                                    -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'hiyori_longjump.mp3' },                                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'hiyori_longjump.mp3' },                              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'hiyori_note1.mp3', 'hiyori_atk7.mp3', 'hiyori_atk2.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = 'nil',
}
VT_ATSUKO = {
  [CHAR_SOUND_ATTACKED] = { 'atsk_dmg1.mp3', 'atsk_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'atsk_eh1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'atsk_dead1.mp3', 'atsk_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {'chise_slowclimb.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'chise_note1.mp3'},
  -- [CHAR_SOUND_HAHA] = {'saya_laugh2.mp3'}, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'atsk_star1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'atsk_jump1.mp3' },     -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'atsk_atk1.mp3',            -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'atsk_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'atsk_ls1.mp3' },    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'atsk_getup.mp3',       -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'atsk_dmg2.mp3' },     -- Touch Fire
  [CHAR_SOUND_OOOF] = 'atsk_hm1.mp3',             -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'atsk_dmg2.mp3',           -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3',}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'atsk_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'atsk_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'atsk_atk2.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'atsk_muda.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'atsk_ah1.mp3',                   -- Drop off of ledge + Fall off Ledge
  -- [CHAR_SOUND_UH2] = {'chise_uh3.mp3'}, -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = 'chise_fall.mp3', -- Falling
  [CHAR_SOUND_WAH2] = 'atsk_atk1.mp3',                                              -- Throw Object
  [CHAR_SOUND_WHOA] = 'atsk_ah1.mp3',                                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'atsk_atk3.mp3' },                                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'atsk_atk3.mp3' },                             -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'atsk_atk6.mp3', 'atsk_atk5.mp3', 'atsk_atk4.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'chise_yawn.mp3'},
}
VT_MISAKI = {
  [CHAR_SOUND_ATTACKED] = { 'misaki_hurt1.mp3', 'misaki_hurt2.mp3' },
  [CHAR_SOUND_DOH] = 'misaki_eh1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'misaki_dead1.mp3', 'misaki_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {'misaki_ledgeclimb.mp3',}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'misaki_atk5.mp3' },
  -- [CHAR_SOUND_HAHA] = {'silent.mp3'}, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'misaki_star1.mp3' },                   -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'misaki_atk2.mp3' },                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'misaki_grab.mp3',                              -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'silent.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'misaki_levelselect3.mp3' },             -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'misaki_sorry.mp3', 'misaki_getup.mp3' }, -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'misaki_hurt1.mp3' },                      -- Touch Fire
  [CHAR_SOUND_OOOF] = 'misaki_what.mp3',                              -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'misaki_hurt2.mp3',                            -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = 'misaki_atk3.mp3', -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'misaki_atk2.mp3', -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'misaki_atk4.mp3', -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'misaki_bthrow1.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'misaki_eh1.mp3',                      -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'misaki_atk2.mp3' },                -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = 'misaki_fall.mp3', -- Falling
  [CHAR_SOUND_WAH2] = 'misaki_atk5.mp3',                                -- Throw Object
  [CHAR_SOUND_WHOA] = 'misaki_eh1.mp3',                                 -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'misaki_atk3.mp3' },                           -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'misaki_atk3.mp3' },               -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'misaki_atk2.mp3', 'misaki_jump1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'silent.mp3'},
}
VT_SAORI = {
  [CHAR_SOUND_ATTACKED] = { 'saori_hurt1.mp3', 'saori_hurt2.mp3', 'saori_hurt3.mp3' },
  [CHAR_SOUND_DOH] = 'saori_hurt1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'saori_dead1.mp3' },
  -- [CHAR_SOUND_EEUH] = {'saori_naruhodo.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'saori_note2.mp3'},
  [CHAR_SOUND_HAHA] = { 'saori_omoshiroi.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'saori_starget1.mp3', 'saori_starget3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'saori_atk2.mp3' },                               -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'saori_yes.mp3',                                      -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'silent.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'saori_levelselect1.mp3' },                    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'saori_sorry.mp3',                                -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'saori_hurt3.mp3' },                             -- Touch Fire
  [CHAR_SOUND_OOOF] = 'saori_what.mp3',                                     -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'saori_hurt2.mp3',                                   -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'saori_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'saori_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'saori_atk1.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'saori_bthrow1.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'saori_drop.mp3',                     -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'saori_jump1.mp3' },               -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = 'saori_fall.mp3', -- Falling
  [CHAR_SOUND_WAH2] = 'saori_throw.mp3',                                   -- Throw Object
  [CHAR_SOUND_WHOA] = 'saori_ledgegrab.mp3',                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'saori_longjump1.mp3', 'saori_atk4.mp3' },        -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'saori_atk3.mp3', 'saori_atk4.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'saori_jump1.mp3', 'saori_atk1.mp3' },      -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'silent.mp3'},
}
VT_NATSU = {
  [CHAR_SOUND_ATTACKED] = { 'natsu_dmg1.mp3', 'natsu_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'natsu_are1.mp3',           -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'natsu_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'natsu_slowclimb.mp3' }, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'natsu_atk3.mp3' },
  [CHAR_SOUND_HAHA] = { 'natsu_sugoi.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'natsu_star1.mp3', 'natsu_star2.mp3', 'natsu_star3.mp3', 'natsu_star4.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'natsu_jump2.mp3' },                                                              -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'natsu_grab.mp3',                                                                     -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'natsu_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'natsu_ls1.mp3', 'natsu_ls2.mp3' },                                            -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'natsu_getup.mp3' },                                                            -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'natsu_dmg3.mp3' },                                                              -- Touch Fire
  [CHAR_SOUND_OOOF] = 'natsu_hm1.mp3',                                                                      -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'natsu_dmg2.mp3',                                                                    -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'natsu_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'natsu_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'natsu_atk1.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'natsu_bthrow1.mp3' },             -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'natsu_sugoi.mp3' },                  -- Boing
  [CHAR_SOUND_UH] = 'natsu_dmg1.mp3',                                 -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'natsu_atk2.mp3' },                            -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'natsu_falling.mp3',                        -- Falling
  [CHAR_SOUND_WAH2] = { 'natsu_bthrow1.mp3' },                        -- Throw Object
  [CHAR_SOUND_WHOA] = 'natsu_are1.mp3',                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'natsu_atk4.mp3' },                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'natsu_atk4.mp3' },              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'natsu_jump1.mp3', 'natsu_atk1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'silent.mp3'},
}

VT_MINE = {
  [CHAR_SOUND_ATTACKED] = { 'mine_dmg1.mp3', 'mine_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'mine_ah1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'mine_dead1.mp3', 'mine_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {'mmr_slowclimb.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'ksm_bagon.mp3'},
  -- [CHAR_SOUND_HAHA] = {'mmr_laugh1.mp3'}, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'mine_star1.mp3', 'mine_star2.mp3', 'mine_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'mine_atk1.mp3' },                                          -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                       -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'ksm_sigh.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'mine_ls1.mp3' },                                        -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'mine_getup1.mp3', 'mine_getup2.mp3' },                   -- Getting up after thrown out of level
  -- [CHAR_SOUND_ON_FIRE] = {'mmr_dmg1.mp3'}, -- Touch Fire
  [CHAR_SOUND_OOOF] = 'mine_ah1.mp3',                                                 -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'mine_dmg1.mp3',                                               -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'mine_atk2.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'mine_atk1.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'mine_atk3.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'mine_bthrow1.mp3' }, -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },  -- Boing
  -- [CHAR_SOUND_UH] = 'mmr_ah2.mp3', -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'mine_atk3.mp3' },                -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = '.mp3', -- Falling
  [CHAR_SOUND_WAH2] = { 'mine_atk1.mp3' },              -- Throw Object
  -- [CHAR_SOUND_WHOA] = 'mmr_ah1.mp3', -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'mine_atk4.mp3' },             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'mine_atk4.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'mine_jump1.mp3' },      -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'mmr_yawn.mp3'},
}

VT_TSURUGI = {
  [CHAR_SOUND_ATTACKED] = { 'tsurugi_dmg1.mp3', 'tsurugi_dmg2.mp3', 'tsurugi_dmg3.mp3' },
  [CHAR_SOUND_DOH] = 'tsurugi_dmg2.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'tsurugi_dying.mp3' },
  [CHAR_SOUND_HRMM] = 'tsurugi_eh.mp3',  -- Object Pick-up
  -- [CHAR_SOUND_EEUH] = {'mmr_slowclimb.mp3'}, -- Slow Get up from ledge
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'tsurugi_groundPound.mp3' },
  [CHAR_SOUND_HAHA] = { 'tsurugi_laugh.mp3' },              -- Landing after backflip
  [CHAR_SOUND_HAHA_2] = { 'tsurugi_laugh.mp3' },
  [CHAR_SOUND_HERE_WE_GO] = { 'tsurugi_star.mp3' },         -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'tsurugi_jump2.mp3' },            -- 2nd Jump + Dive Attack
  [CHAR_SOUND_IMA_TIRED] = 'tsurugi_sleepy.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'tsurugi_letsGo.mp3' },        -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'tsurugi_levelFail.mp3' },      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'tsurugi_burn.mp3' },            -- Touch Fire
  [CHAR_SOUND_OOOF] = 'tsurugi_dmg3.mp3',                   -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'tsurugi_dmg3.mp3',                  -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'tsurugi_kick.mp3' },          -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'tsurugi_punch2.mp3',            -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'tsurugi_punch1.mp3',            -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'tsurugi_bowser.mp3' },  -- Bowser Throw
  [CHAR_SOUND_UH] = 'tsurugi_eh.mp3',                       -- Drop off of ledge + Fall off Ledge
  -- [CHAR_SOUND_UH2] = {'tsurugi_atk3.mp3'}, -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'tsurugi_burn.mp3',               -- Falling
  [CHAR_SOUND_WHOA] = 'tsurugi_ledge.mp3',                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'tsurugi_yahoo.mp3' },             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'tsurugi_yahoo.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'tsurugi_jump1.mp3' },       -- 1st Jump(s)
}

VT_ICHIKA = {
  [CHAR_SOUND_ATTACKED] = { 'ichika_dmg2.mp3', 'ichika_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'ichika_oh1.mp3',             -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'sfx_smb3_down.mp3' },
  [CHAR_SOUND_EEUH] = { 'ichika_ledgeclimb.mp3' }, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'ksm_bagon.mp3'},
  [CHAR_SOUND_HAHA] = { 'ichika_jajan.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'ichika_star1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'ichika_atk1.mp3' },      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',     -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'ichika_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'ichika_ls1.mp3' },    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'ichika_getup.mp3' },   -- Getting up after thrown out of level
  -- [CHAR_SOUND_ON_FIRE] = {'mmr_dmg1.mp3'}, -- Touch Fire
  [CHAR_SOUND_OOOF] = 'ichika_woah.mp3',            -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'ichika_dmg1.mp3',           -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'ichika_atk1.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'ichika_atk3.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'ichika_atk2.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'ichika_bthrow.mp3' }, -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },   -- Boing
  [CHAR_SOUND_UH] = 'ichika_oh1.mp3',                     -- Drop off of ledge + Fall off Ledge
  -- [CHAR_SOUND_UH2] = {'mine_atk3.mp3'}, -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = '.mp3', -- Falling
  [CHAR_SOUND_WAH2] = { 'sfx_ssb64_itemthrow.mp3' },          -- Throw Object
  [CHAR_SOUND_WHOA] = 'ichika_ledgegrab.mp3',                 -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'ichika_longjump.mp3' },             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'ichika_longjump.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'ichika_jump1.mp3' },          -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'mmr_yawn.mp3'},
}
VT_NAGISA = {
  [CHAR_SOUND_ATTACKED] = { 'nagisa_dmg3.mp3', 'nagisa_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'nagisa_eh1.mp3',                                                    -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'nagisa_dead1.mp3', 'nagisa_dead2.mp3' },
  [CHAR_SOUND_HAHA] = { 'nagisa_laugh1.mp3' },                                            -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'nagisa_star2.mp3', 'nagisa_star1.mp3' },                   -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'nagisa_atk5.mp3' },                                            -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                           -- Object Pick-up
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'nagisa_atk4.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'nagisa_ls1.mp3' },                                          -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'nagisa_levelexit.mp3' },                                     -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'nagisa_burn.mp3' },                                           -- Touch Fire
  [CHAR_SOUND_OOOF] = 'nagisa_ara1.mp3',                                                  -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'nagisa_dmg1.mp3',                                                 -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'nagisa_atk3.mp3' },                                         -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'nagisa_atk2.mp3',                                             -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'nagisa_atk1.mp3',                                             -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'nagisa_bthrow1.mp3' },                                -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                                   -- Boing
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                                                -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'nagisa_atk1.mp3' },                                               -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                                        -- Falling
  [CHAR_SOUND_WAH2] = { 'nagisa_throw1.mp3', 'nagisa_throw2.mp3' },                       -- Throw Object
  [CHAR_SOUND_WHOA] = 'nagisa_ara2.mp3',                                                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'nagisa_longjump.mp3' },                                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'nagisa_atk4.mp3', 'nagisa_longjump.mp3' },          -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'nagisa_atk1.mp3', 'nagisa_atk6.mp3', 'nagisa_atk7.mp3' }, -- 1st Jump(s)
}

VT_MIKA = {
  [CHAR_SOUND_ATTACKED] = { 'mika_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'mika_are2.mp3',                                               -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'mika_dead1.mp3' },
  [CHAR_SOUND_HAHA] = { 'mika_laugh.mp3' },                                         -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'mika_star1.mp3', 'mika_star2.mp3' },                 -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'mika_atk5.mp3' },                                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                     -- Object Pick-up
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'mika_atk2.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'mika_ls1.mp3' },                                      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'mika_wow.mp3' },                                       -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'mika_burn.mp3' },                                       -- Touch Fire
  [CHAR_SOUND_OOOF] = 'mika_hmm.mp3',                                               -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'mika_dmg2.mp3',                                             -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'mika_atk2.mp3' },                                     -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'mika_atk3.mp3',                                         -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'mika_atk1.mp3',                                         -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'mika_useless.mp3' },                            -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                             -- Boing
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                                          -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'mika_atk1.mp3' },                                           -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'mika_burn.mp3',                                          -- Falling
  [CHAR_SOUND_WAH2] = { 'mika_throw.mp3' },                                         -- Throw Object
  [CHAR_SOUND_WHOA] = 'mika_are1.mp3',                                              -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'mika_longjump.mp3' },                                     -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'mika_longjump.mp3' },                         -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'mika_atk1.mp3', 'mika_atk3.mp3', 'mika_atk4.mp3' }, -- 1st Jump(s)
}
VT_HIFUMI = {
  [CHAR_SOUND_ATTACKED] = { 'hifumi_dmg2.mp3', 'hifumi_dmg4.mp3' },
  [CHAR_SOUND_DOH] = 'hifumi_eh1.mp3',              -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'hifumi_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'hifumi_slowclimb.mp3' },   -- Slow Get up from ledge
  [CHAR_SOUND_HAHA] = { 'hifumi_ahaha.mp3' },       -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'hifumi_star1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'hifumi_atk4.mp3' },      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',     -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'hifumi_tired.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'hifumi_atk2.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'hifumi_ls.mp3' },                                           -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'hifumi_levelexit.mp3' },                                     -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'hifumi_dmg3.mp3' },                                           -- Touch Fire
  [CHAR_SOUND_OOOF] = 'hifumi_are1.mp3',                                                  -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'hifumi_dmg1.mp3',                                                 -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'hifumi_atk2.mp3' },                                         -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'hifumi_atk4.mp3',                                             -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'hifumi_atk3.mp3',                                             -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'hifumi_longjump.mp3' },                               -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                                   -- Boing
  [CHAR_SOUND_UH] = 'hifumi_wah1.mp3',                                                    -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'hifumi_atk3.mp3' },                                               -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'hifumi_fall.mp3',                                              -- Falling
  [CHAR_SOUND_WAH2] = { 'hifumi_atk1.mp3' },                                              -- Throw Object
  [CHAR_SOUND_WHOA] = 'hifumi_wah2.mp3',                                                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'hifumi_longjump.mp3' },                                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'hifumi_atk2.mp3' },                                 -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'hifumi_atk3.mp3', 'hifumi_atk6.mp3', 'hifumi_atk5.mp3' }, -- 1st Jump(s)
}

VT_KOHARU = {
  [CHAR_SOUND_ATTACKED] = { 'koharu_dmg4.mp3', 'koharu_dmg6.mp3' },
  [CHAR_SOUND_DOH] = 'koharu_eh1.mp3',                                  -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'koharu_dead1.mp3', 'koharu_dead2.mp3' },
  [CHAR_SOUND_HAHA] = { 'koharu_laugh.mp3' },                           -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'koharu_star1.mp3', 'koharu_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'koharu_atk4.mp3' },                          -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                         -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'koharu_tired.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'koharu_atk5.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'koharu_ls1.mp3' },                              -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'koharu_deathpenalty.mp3' },                      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'koharu_dmg3.mp3' },                               -- Touch Fire
  [CHAR_SOUND_OOOF] = 'koharu_are1.mp3',                                      -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'koharu_dmg1.mp3',                                     -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'koharu_atk5.mp3' },                             -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'koharu_atk3.mp3',                                 -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'koharu_atk1.mp3',                                 -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'koharu_bthrow.mp3' },                     -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                       -- Boing
  [CHAR_SOUND_UH] = 'koharu_are1.mp3',                                        -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'koharu_atk1.mp3' },                                   -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'koharu_fall.mp3',                                  -- Falling
  [CHAR_SOUND_WAH2] = { 'koharu_echidame.mp3' },                              -- Throw Object
  [CHAR_SOUND_WHOA] = 'koharu_eh1.mp3',                                       -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'koharu_jump2.mp3' },                                -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'koharu_jump1.mp3', 'koharu_atk6.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'koharu_atk1.mp3', 'koharu_atk3.mp3' },        -- 1st Jump(s)
}

VT_HANAKO = {
  [CHAR_SOUND_ATTACKED] = { 'hanako_dmg1.mp3', 'hanako_dmg2.mp3', 'hanako_dmg5.mp3' },
  [CHAR_SOUND_DOH] = 'hanako_ah.mp3',                                                       -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'hanako_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'hanako_slowclimb.mp3' },                                           -- Slow Get up from ledge
  [CHAR_SOUND_HAHA] = { 'hanako_laugh.mp3' },                                               -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'hanako_star1.mp3', 'hanako_star2.mp3', 'hanako_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'hanako_atk2.mp3' },                                              -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                             -- Object Pick-up
  --[CHAR_SOUND_IMA_TIRED] = 'kisaki_rest.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'hanako_atk7.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'hanako_ls1.mp3' },                       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'hanako_begentle.mp3' },                   -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'hanako_dmg6.mp3' },                        -- Touch Fire
  [CHAR_SOUND_OOOF] = 'hanako_ara1.mp3',                               -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'hanako_ara3.mp3',                              -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'hanako_atk3.mp3' },                      -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'hanako_atk4.mp3',                          -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'hanako_atk1.mp3',                          -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'hanako_bthrow.mp3' },              -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                -- Boing
  [CHAR_SOUND_UH] = 'hanako_eh.mp3',                                   -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'hanako_atk1.mp3' },                            -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'hanako_gasp.mp3',                           -- Falling
  [CHAR_SOUND_WAH2] = { 'hanako_atk5.mp3' },                           -- Throw Object
  [CHAR_SOUND_WHOA] = 'hanako_ara2.mp3',                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'hanako_atk6.mp3' },                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'hanako_atk5.mp3' },              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'hanako_atk1.mp3', 'hanako_atk8.mp3' }, -- 1st Jump(s)
}
VT_AIRI = {
  [CHAR_SOUND_ATTACKED] = { 'airi_ehh.mp3' },
  [CHAR_SOUND_DOH] = 'airi_eh1.mp3',                                 -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'airi_defeat1.mp3' },
  [CHAR_SOUND_HAHA] = { 'airi_laugh1.mp3' },                         -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'airi_star1.mp3', 'airi_star2.mp3' },  -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'airi_atk3.mp3' },                         -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'airi_hm1.mp3',                                -- Object Pick-up
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'airi_atk1.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'airi_ls1.mp3' },                       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'airi_levelexit.mp3', 'airi_pout.mp3' }, -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                    -- Touch Fire
  [CHAR_SOUND_OOOF] = 'airi_ah1.mp3',                                -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'airi_dmg1.mp3',                              -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'airi_atk3.mp3' },                      -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'airi_atk6.mp3',                          -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'airi_atk5.mp3',                          -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'airi_bthrow.mp3' },              -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },              -- Boing
  [CHAR_SOUND_UH] = 'airi_eh2.mp3',                                  -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'airi_atk4.mp3' },                            -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'airi_fall.mp3',                           -- Falling
  [CHAR_SOUND_WAH2] = { 'airi_throw1.mp3' },                         -- Throw Object
  [CHAR_SOUND_WHOA] = 'airi_hm1.mp3',                                -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'airi_atk2.mp3' },                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'airi_atk2.mp3' },              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'airi_atk5.mp3', 'airi_atk1.mp3' },   -- 1st Jump(s)
}

VT_YOSHIMI = {
  [CHAR_SOUND_ATTACKED] = { 'yosh_dmg3.mp3', 'yosh_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'yosh_ah1.mp3',                                                  -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'sfx_smb3_down.mp3' },
  [CHAR_SOUND_HAHA] = { 'yosh_heh.mp3' },                                             -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'yosh_star1.mp3', 'yosh_star2.mp3', 'yosh_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'yosh_atk2.mp3' },                                          -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'yosh_hm2.mp3',                                                 -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'yosh_tired.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'yosh_atk6.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'yosh_ls1.mp3' },                                      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'yosh_levelexit1.mp3', 'yosh_levelexit2.mp3' },         -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                                   -- Touch Fire
  [CHAR_SOUND_OOOF] = 'yosh_grabbed.mp3',                                           -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'yosh_dmg3.mp3',                                             -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'yosh_atk3.mp3' },                                     -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'yosh_atk5.mp3',                                         -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'yosh_atk7.mp3',                                         -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'yosh_bthrow1.mp3' },                            -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                             -- Boing
  [CHAR_SOUND_UH] = 'yosh_hm2.mp3',                                                 -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'yosh_atk4.mp3' },                                           -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'yosh_fall.mp3',                                          -- Falling
  [CHAR_SOUND_WAH2] = { 'yosh_throw1.mp3' },                                        -- Throw Object
  [CHAR_SOUND_WHOA] = 'yosh_are1.mp3',                                              -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'yosh_atk3.mp3' },                                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'yosh_atk3.mp3' },                             -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'yosh_atk4.mp3', 'yosh_atk5.mp3', 'yosh_atk7.mp3' }, -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'yosh_yawn.mp3' },
}

VT_HASUMI = {
  [CHAR_SOUND_ATTACKED] = { 'hasumi_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'hasumi_are1.mp3',                                -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'hasumi_dying.mp3' },
  [CHAR_SOUND_HAHA] = { 'hasumi_laugh.mp3' },                          -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'hasumi_star.mp3', 'hasumi_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'hasumi_jump2_1.mp3' },                      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                        -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'hasumi_hm.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'hasumi_groundPound.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'hasumi_letsGo.mp3' },                       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'hasumi_levelFail.mp3' },                     -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'hasumi_burn.mp3' },                           -- Touch Fire
  [CHAR_SOUND_OOOF] = 'hasumi_ah1.mp3',                                   -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'hasumi_dmg1.mp3',                                 -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'hasumi_punch2.mp3' },                       -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'hasumi_kick.mp3',                             -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'hasumi_kick.mp3',                             -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'hasumi_bowser.mp3' },                 -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                   -- Boing
  [CHAR_SOUND_UH] = 'hasumi_ah1.mp3',                                     -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'hasumi_jump1_2.mp3' },                            -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                        -- Falling
  [CHAR_SOUND_WAH2] = { 'hasumi_punch2.mp3', 'hasumi_bowser.mp3' },       -- Throw Object
  [CHAR_SOUND_WHOA] = 'hasumi_are1.mp3',                                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'hasumi_yahoo.mp3' },                            -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'hasumi_yahoo.mp3' },                -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'hasumi_kick.mp3', 'hasumi_jump1_2.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'hasumi_yawn.mp3'},
}
VT_SEIA = {
  [CHAR_SOUND_ATTACKED] = { 'seia_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'seia_dmg2.mp3',                                                 -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'seia_dead1.mp3' },
  [CHAR_SOUND_HAHA] = { 'seia_subarashi.mp3' },                                       -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'seia_star1.mp3', 'seia_star2.mp3', 'seia_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'seia_atk2.mp3' },                                          -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                       -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'seia_hm2.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'seia_atk2.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'seia_ls1.mp3' },                                      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'seia_levelexit.mp3' },                                 -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                                   -- Touch Fire
  [CHAR_SOUND_OOOF] = 'seia_hm1.mp3',                                               -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'seia_dmg2.mp3',                                             -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'seia_atk1.mp3' },                                     -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'seia_atk5.mp3',                                         -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'seia_atk6.mp3',                                         -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'seia_useless.mp3' },                            -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                             -- Boing
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                                          -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'seia_atk2.mp3' },                                           -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                                  -- Falling
  [CHAR_SOUND_WAH2] = { 'sfx_ssb64_itemthrow.mp3', 'seia_kys.mp3' },                -- Throw Object
  [CHAR_SOUND_WHOA] = 'seia_hm1.mp3',                                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'seia_atk3.mp3' },                                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'seia_atk3.mp3', 'seia_atk1.mp3' },            -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'seia_atk1.mp3', 'seia_atk5.mp3', 'seia_atk7.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'serika_yawn.mp3'},
}
VT_SUZUMI = {
  [CHAR_SOUND_ATTACKED] = { 'suzumi_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'suzumi_dmg2.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'suzumi_dead1.mp3', 'suzumi_dead2.mp3' },
  --[CHAR_SOUND_HAHA] = {'seia_subarashi.mp3'}, -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'suzumi_star1.mp3', 'suzumi_star2.mp3', 'suzumi_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'suzumi_atk2.mp3' },                                              -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                             -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'suzumi_humu.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'suzumi_atk1.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'suzumi_ls1.mp3' },           -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'suzumi_dead3.mp3' },          -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },          -- Touch Fire
  --[CHAR_SOUND_OOOF] = 'seia_hm1.mp3', -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'suzumi_dmg2.mp3',                  -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'suzumi_atk5.mp3' },          -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'suzumi_atk2.mp3',              -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'suzumi_atk3.mp3',              -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'suzumi_bthrow1.mp3' }, -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },    -- Boing
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                 -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'suzumi_atk1.mp3' },                -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',         -- Falling
  [CHAR_SOUND_WAH2] = { 'suzumi_bthrow2.mp3' },            -- Throw Object
  [CHAR_SOUND_WHOA] = 'sfx_ssb64_ledge.mp3',               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'suzumi_atk5.mp3' },              -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'suzumi_atk5.mp3' },  -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'suzumi_atk1.mp3' },        -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'serika_yawn.mp3'},
}
