-- BA Pack 3 [Trinity-Arius]
-- Character Voice Tables

-- ================================================================
-- Example
-- ================================================================
-- local VT_CHARNAME = {
--   [CHAR_SOUND_OKEY_DOKEY] = 'CharStartGame.ogg',                                       -- Starting game
--   [CHAR_SOUND_LETS_A_GO] = 'CharStartLevel.ogg',                                       -- Starting level
--   [CHAR_SOUND_GAME_OVER] = 'CharGameOver.ogg',                                         -- Game Overed
--   [CHAR_SOUND_PUNCH_YAH] = 'CharPunch1.ogg',                                           -- Punch 1
--   [CHAR_SOUND_PUNCH_WAH] = 'CharPunch2.ogg',                                           -- Punch 2
--   [CHAR_SOUND_PUNCH_HOO] = 'CharPunch3.ogg',                                           -- Punch 3
--   [CHAR_SOUND_YAH_WAH_HOO] = { 'CharJump1.ogg', 'CharJump2.ogg', 'CharJump3.ogg' },    -- First Jump Sounds
--   [CHAR_SOUND_HOOHOO] = 'CharDoubleJump.ogg',                                          -- Second jump sound
--   [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'CharTripleJump1.ogg', 'CharTripleJump2.ogg' },   -- Triple jump sounds
--   [CHAR_SOUND_UH] = 'CharBonk.ogg',                                                    -- Soft wall bonk
--   [CHAR_SOUND_UH2] = 'CharLedgeGetUp.ogg',                                             -- Quick ledge get up
--   [CHAR_SOUND_UH2_2] = 'CharLongJumpLand.ogg',                                         -- Landing after long jump
--   [CHAR_SOUND_DOH] = 'CharBonk.ogg',                                                   -- Hard wall bonk
--   [CHAR_SOUND_OOOF] = 'CharBonk.ogg',                                                  -- Attacked in air
--   [CHAR_SOUND_OOOF2] = 'CharBonk.ogg',                                                 -- Land from hard bonk
--   [CHAR_SOUND_HAHA] = 'CharTripleJumpLand.ogg',                                        -- Landing triple jump
--   [CHAR_SOUND_HAHA_2] = 'CharWaterLanding.ogg',                                        -- Landing in water from big fall
--   [CHAR_SOUND_YAHOO] = 'CharLongJump.ogg',                                             -- Long jump
--   [CHAR_SOUND_DOH] = 'CharBonk.ogg',                                                   -- Long jump wall bonk
--   [CHAR_SOUND_WHOA] = 'CharGrabLedge.ogg',                                             -- Grabbing ledge
--   [CHAR_SOUND_EEUH] = 'CharClimbLedge.ogg',                                            -- Climbing over ledge
--   [CHAR_SOUND_WAAAOOOW] = 'CharFalling.ogg',                                           -- Falling a long distance
--   [CHAR_SOUND_TWIRL_BOUNCE] = 'CharFlowerBounce.ogg',                                  -- Bouncing off of a flower spring
--   [CHAR_SOUND_GROUND_POUND_WAH] = 'CharGroundPound.ogg',                               -- Ground Pound after startup
--   [CHAR_SOUND_WAH2] = 'CharThrow.ogg',                                                 -- Throwing something
--   [CHAR_SOUND_HRMM] = 'CharLift.ogg',                                                  -- Lifting something
--   [CHAR_SOUND_HERE_WE_GO] = 'CharGetStar.ogg',                                         -- Star get
--   [CHAR_SOUND_SO_LONGA_BOWSER] = 'CharThrowBowser.ogg',                                -- Throwing Bowser
--   --DAMAGE
--   [CHAR_SOUND_ATTACKED] = 'CharDamaged.ogg',                                           -- Damaged
--   [CHAR_SOUND_PANTING] = 'CharPanting.ogg',                                            -- Low health
--   [CHAR_SOUND_PANTING_COLD] = 'CharPanting.ogg',                                       -- Getting cold
--   [CHAR_SOUND_ON_FIRE] = 'CharBurned.ogg',                                             -- Burned
--   --SLEEP SOUNDS
--   [CHAR_SOUND_IMA_TIRED] = 'CharTired.ogg',                                            -- Mario feeling tired
--   [CHAR_SOUND_YAWNING] = 'CharYawn.ogg',                                               -- Mario yawning before he sits down to sleep
--   [CHAR_SOUND_SNORING1] = 'CharSnore.ogg',                                             -- Snore Inhale
--   [CHAR_SOUND_SNORING2] = 'CharExhale.ogg',                                            -- Exhale
--   [CHAR_SOUND_SNORING3] = 'CharSleepTalk.ogg',                                         -- Sleep talking / mumbling
--   --COUGHING (USED IN THE GAS MAZE)
--   [CHAR_SOUND_COUGHING1] = 'CharCough1.ogg',                                           -- Cough take 1
--   [CHAR_SOUND_COUGHING2] = 'CharCough2.ogg',                                           -- Cough take 2
--   [CHAR_SOUND_COUGHING3] = 'CharCough3.ogg',                                           -- Cough take 3
--   --DEATH
--   [CHAR_SOUND_DYING] = 'CharDying.ogg',                                                -- Dying from damage
--   [CHAR_SOUND_DROWNING] = 'CharDrowning.ogg',                                          -- Running out of air underwater
--   [CHAR_SOUND_MAMA_MIA] = 'CharLeaveLevel.ogg'                                         -- Booted out of level
-- }

-- ================================================================
-- NPC Voices
-- Files are in Main
-- ================================================================

VT_NOVOICE = {
  [CHAR_SOUND_ATTACKED] = { 'sfx_smrpg_hit1.mp3', 'sfx_smrpg_shell.mp3', 'sfx_smw_bossstun.mp3' },
  [CHAR_SOUND_DOH] = 'sfx_ml_bump.mp3',                                              -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'sfx_smb3_down.mp3' },
  [CHAR_SOUND_HERE_WE_GO] = { 'sfx_alttp_item.mp3', 'sfx_smrpg_specialflower.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_LETS_A_GO] = { 'sfx_smb3_levelselect.mp3' },                           -- Level Select
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                      -- Object Pick-up
  [CHAR_SOUND_HOOHOO] = { 'sfx_smw_jump.mp3' },                                      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                                    -- Touch Fire
  [CHAR_SOUND_OOOF] = 'sfx_pm64_what.mp3',                                           -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'sfx_smrpg_drop.mp3',                                         -- Landing After a Bonk + Thrown out of level + Also Bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'sfx_ssb64_atk3.mp3' },                                 -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'sfx_ssb64_atk2.mp3',                                     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'sfx_ssb64_atk1.mp3',                                     -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'sfx_smrpg_fireball.mp3' },                       -- Bowser Throw
  [CHAR_SOUND_WAH2] = { 'sfx_ssb64_itemthrow.mp3' },                                 -- Throw Object
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                                           -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                                   -- Falling
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                              -- Boing
  [CHAR_SOUND_WHOA] = 'sfx_ssb64_ledge.mp3',                                         -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'sfx_ssb64_superjump.mp3' },                                -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'sfx_ssb64_superjump.mp3' },                    -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'sfx_smw_jump.mp3' },                                 -- 1st Jump(s)
}

-- ================================================================
-- Voice Tables
-- ================================================================

VT_MARI = {
  [CHAR_SOUND_ATTACKED] = { 'spmari_hurt3.mp3', 'spmari_hurt5.mp3', 'spmari_hurt2.mp3' },
  [CHAR_SOUND_DOH] = 'spmari_ah.mp3',               -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'spmari_dead.mp3' },
  [CHAR_SOUND_EEUH] = { 'spmari_ledgegetup.mp3', }, -- Slow Get up from ledge
  --[CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  --[CHAR_SOUND_GROUND_POUND_WAH] = {'silent.mp3'},
  [CHAR_SOUND_HAHA] = 'spmari_laugh.mp3', -- Landing after backflip
  --[CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  --[CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'spmari_subarashi.mp3', }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'spmari_attack6.mp3',            -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'spmari_pickup.mp3',               -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'spmari_pant.mp3',
  [CHAR_SOUND_LETS_A_GO] = 'spmari_levelselect.mp3',     -- Level Select
  --[CHAR_SOUND_MAMA_MIA] = 'silent.mp3', -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'spmari_hurt1.mp3', },        -- Touch Fire
  [CHAR_SOUND_OOOF] = 'spmari_ah.mp3',
  [CHAR_SOUND_OOOF2] = 'spmari_hurt4.mp3',               -- Landing After a Bonk + Thrown out of level
  --[CHAR_SOUND_PANTING] = {'silent.mp3',}, -- Low Health
  --[CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  --[CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'spmari_attack5.mp3', }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'spmari_attack6.mp3',      --2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'spmari_attack1.mp3',      -- 1st Punch
  --[CHAR_SOUND_SNORING1] = 'silent.mp3',
  --[CHAR_SOUND_SNORING2] = 'silent.mp3',
  --[CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'spmari_rip.mp3' },                                             --Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'spmari_laugh.mp3' },                                              -- Boing
  [CHAR_SOUND_UH] = 'spmari_uh1.mp3',                                                              --Drop off of ledge
  [CHAR_SOUND_UH2] = { 'spmari_attack7.mp3', },                                                    -- Quick Ledge Get-Up
  [CHAR_SOUND_UH2_2] = 'spmari_attack9.mp3',                                                       -- Landing after Long Jump
  --[CHAR_SOUND_WAAAOOOW] = 'silent.mp3', -- Falling
  [CHAR_SOUND_WAH2] = 'spmari_attack5.mp3',                                                        -- Throw Object
  [CHAR_SOUND_WHOA] = 'spmari_uh1.mp3',                                                            -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'spmari_attack3.mp3', },                                                  -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'spmari_attack3.mp3', },                                      -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'spmari_attack7.mp3', 'spmari_attack1.mp3', 'spmari_attack8.mp3' }, -- 1st Jump(s)
  --[CHAR_SOUND_YAWNING] = 'silent.mp3',
}
VT_KAZUSA = {
  [CHAR_SOUND_ATTACKED] = { 'kazusa_dmg1.mp3', 'kazusa_dmg3.mp3' },
  [CHAR_SOUND_DOH] = 'kazusa_what.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'kazusa_dead.mp3' },
  --[CHAR_SOUND_EEUH] = nil, -- Slow Get up from ledge
  --[CHAR_SOUND_GAME_OVER] = nil,
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'kazusa_groundpound.mp3' },
  --[CHAR_SOUND_HAHA] = nil, -- Landing after backflip
  --[CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  --[CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'kazusa_sugoi.mp3', 'kazusa_star1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'kazusa_jump4.mp3',                             -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'kazusa_pickup.mp3',                              -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'kazusa_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = 'kazusa_levelselect.mp3',                    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'kazusa_levelexit.mp3',                       -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'kazusa_what.mp3' },                         -- Touch Fire
  [CHAR_SOUND_OOOF] = 'kazusa_eh1.mp3',                                 -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'kazusa_dmg2.mp3',                               -- Landing After a Bonk + Thrown out of level
  --[CHAR_SOUND_PANTING] = nil, -- Low Health
  --[CHAR_SOUND_PANTING_COLD] = nil,
  --[CHAR_SOUND_PRESS_START_TO_PLAY] = nil,
  [CHAR_SOUND_PUNCH_HOO] = { 'kazusa_ora.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'kazusa_atk4.mp3',    -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'kazusa_atk1.mp3',    -- 1st Punch
  --[CHAR_SOUND_SNORING1] = nil,
  --[CHAR_SOUND_SNORING2] = nil,
  --[CHAR_SOUND_SNORING3] = nil,
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'kazusa_bowserthrow.mp3' },       -- Bowser Throw
  --[CHAR_SOUND_TWIRL_BOUNCE] = nil, -- Boing
  [CHAR_SOUND_UH] = 'kazusa_eh2.mp3',                                -- Drop off of ledge
  [CHAR_SOUND_UH2] = { 'kazusa_jump2.mp3' },                         -- Quick Ledge Get-Up
  --[CHAR_SOUND_UH2_2] = nil, -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = { 'kazusa_fall.mp3', 'kazusa_fall2.mp3' }, -- Falling
  [CHAR_SOUND_WAH2] = 'kazusa_ora.mp3',                              -- Throw Object
  [CHAR_SOUND_WHOA] = 'kazusa_wah2.mp3',                             -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'kazusa_jump3.mp3' },                       -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'kazusa_jump3.mp3' },           -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = {
    'kazusa_jump1.mp3', 'kazusa_jump5.mp3', 'kazusa_jump2.mp3'
  }, -- 1st Jump(s)
  --[CHAR_SOUND_YAWNING] = nil,
}
VT_AZUSA = {
  [CHAR_SOUND_ATTACKED] = { 'azusa_dmg3.mp3', 'azusa_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'azusa_eh1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'azusa_dead1.mp3', 'azusa_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {'nil',}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'nil'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'azusa_atk3.mp3' },
  [CHAR_SOUND_HAHA] = 'azusa_grab.mp3', -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'hiyori_really.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'nil',
  [CHAR_SOUND_HERE_WE_GO] = { 'azusa_starget1.mp3', 'azusa_vanitas2.mp3' }, -- Star Get + Obtaining Power-up + Bowser Throw when not full speed
  [CHAR_SOUND_HOOHOO] = 'azusa_atk5.mp3',                                   -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'azusa_grab.mp3',                                     -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'nil',
  [CHAR_SOUND_LETS_A_GO] = { 'azusa_ls1.mp3', 'azusa_vanitas3.mp3' },       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'azusa_getup.mp3',                                -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'azusa_dmg4.mp3' },                              -- Touch Fire
  [CHAR_SOUND_OOOF] = 'azusa_ah1.mp3',                                      -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'azusa_dmg5.mp3',                                    -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'nil',}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'nil',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'nil', 'nil'},
  [CHAR_SOUND_PUNCH_HOO] = { 'azusa_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'azusa_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'azusa_atk1.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'nil',
  -- [CHAR_SOUND_SNORING2] = 'nil',
  -- [CHAR_SOUND_SNORING3] = {'nil', 'nil'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'azusa_bowserthrow1.mp3' },                        -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'nil'}, -- Boing
  [CHAR_SOUND_UH] = 'azusa_ah2.mp3',                                                  -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'azusa_atk6.mp3' },                                            -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'nil', -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = { 'azusa_falling1.mp3' },                                   -- Falling
  [CHAR_SOUND_WAH2] = 'azusa_throw.mp3',                                              -- Throw Object
  [CHAR_SOUND_WHOA] = 'azusa_are1.mp3',                                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'azusa_vanitas1.mp3' },                                      -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'azusa_atk3.mp3' },                              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'azusa_atk4.mp3', 'azusa_atk5.mp3', 'azusa_atk1.mp3' } -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = 'nil',
}
VT_HIYORI = {
  [CHAR_SOUND_ATTACKED] = { 'hiyori_hurt2.mp3', 'hiyori_hurt1.mp3' },
  [CHAR_SOUND_DOH] = 'hiyori_hai.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'hiyori_dead1.mp3', 'hiyori_dead2.mp3', 'hiyori_dead3.mp3' },
  -- [CHAR_SOUND_EEUH] = {'nil',}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'nil'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'hiyori_atk4.mp3' },
  [CHAR_SOUND_HAHA] = 'hiyori_laugh1.mp3',                                    -- Landing after backflip
  [CHAR_SOUND_HAHA_2] = 'hiyori_laugh2.mp3',                                  -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'nil',
  [CHAR_SOUND_HERE_WE_GO] = { 'hiyori_starget1.mp3', 'hiyori_starget2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'hiyori_atk5.mp3',                                    -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'hiyori_pickup.mp3',                                    -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'hiyori_um.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'hiyori_ls1.mp3' },                              -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'hiyori_sorry.mp3',                                 -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'hiyori_fire.mp3' },                               -- Touch Fire
  [CHAR_SOUND_OOOF] = 'hiyori_eh1.mp3',                                       -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'hiyori_hurt2.mp3',                                    -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'nil',}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'nil',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'nil', 'nil'},
  [CHAR_SOUND_PUNCH_HOO] = { 'hiyori_atk1.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'hiyori_atk6.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'hiyori_atk3.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'nil',
  -- [CHAR_SOUND_SNORING2] = 'nil',
  -- [CHAR_SOUND_SNORING3] = {'nil', 'nil'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'hiyori_bowserthrow1.mp3' },                            -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'hiyori_laugh1.mp3' },                                     -- Boing
  [CHAR_SOUND_UH] = 'hiyori_hurt3.mp3',                                                    -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'hiyori_atk5.mp3' },                                                -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'nil', -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'hiyori_falling1.mp3',                                           -- Falling
  [CHAR_SOUND_WAH2] = 'hiyori_throw.mp3',                                                  -- Throw Object
  [CHAR_SOUND_WHOA] = 'hiyori_eh1.mp3',                                                    -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'hiyori_longjump.mp3' },                                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'hiyori_longjump.mp3' },                              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'hiyori_note1.mp3', 'hiyori_atk7.mp3', 'hiyori_atk2.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = 'nil',
}
VT_ATSUKO = {
  [CHAR_SOUND_ATTACKED] = { 'atsk_dmg1.mp3', 'atsk_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'atsk_eh1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'atsk_dead1.mp3', 'atsk_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {'chise_slowclimb.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'chise_note1.mp3'},
  -- [CHAR_SOUND_HAHA] = {'saya_laugh2.mp3'}, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'atsk_star1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'atsk_jump1.mp3' },     -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'atsk_atk1.mp3',            -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'atsk_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'atsk_ls1.mp3' },    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'atsk_getup.mp3',       -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'atsk_dmg2.mp3' },     -- Touch Fire
  [CHAR_SOUND_OOOF] = 'atsk_hm1.mp3',             -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'atsk_dmg2.mp3',           -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3',}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'atsk_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'atsk_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'atsk_atk2.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'atsk_muda.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'atsk_ah1.mp3',                   -- Drop off of ledge + Fall off Ledge
  -- [CHAR_SOUND_UH2] = {'chise_uh3.mp3'}, -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = 'chise_fall.mp3', -- Falling
  [CHAR_SOUND_WAH2] = 'atsk_atk1.mp3',                                              -- Throw Object
  [CHAR_SOUND_WHOA] = 'atsk_ah1.mp3',                                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'atsk_atk3.mp3' },                                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'atsk_atk3.mp3' },                             -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'atsk_atk6.mp3', 'atsk_atk5.mp3', 'atsk_atk4.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'chise_yawn.mp3'},
}
VT_MISAKI = {
  [CHAR_SOUND_ATTACKED] = { 'misaki_hurt1.mp3', 'misaki_hurt2.mp3' },
  [CHAR_SOUND_DOH] = 'misaki_eh1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'misaki_dead1.mp3', 'misaki_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {'misaki_ledgeclimb.mp3',}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'misaki_atk5.mp3' },
  -- [CHAR_SOUND_HAHA] = {'silent.mp3'}, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'misaki_star1.mp3' },                   -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'misaki_atk2.mp3' },                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'misaki_grab.mp3',                              -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'silent.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'misaki_levelselect3.mp3' },             -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'misaki_sorry.mp3', 'misaki_getup.mp3' }, -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'misaki_hurt1.mp3' },                      -- Touch Fire
  [CHAR_SOUND_OOOF] = 'misaki_what.mp3',                              -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'misaki_hurt2.mp3',                            -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = 'misaki_atk3.mp3', -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'misaki_atk2.mp3', -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'misaki_atk4.mp3', -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'misaki_bthrow1.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'misaki_eh1.mp3',                      -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'misaki_atk2.mp3' },                -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = 'misaki_fall.mp3', -- Falling
  [CHAR_SOUND_WAH2] = 'misaki_atk5.mp3',                                -- Throw Object
  [CHAR_SOUND_WHOA] = 'misaki_eh1.mp3',                                 -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'misaki_atk3.mp3' },                           -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'misaki_atk3.mp3' },               -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'misaki_atk2.mp3', 'misaki_jump1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'silent.mp3'},
}
VT_SAORI = {
  [CHAR_SOUND_ATTACKED] = { 'saori_hurt1.mp3', 'saori_hurt2.mp3', 'saori_hurt3.mp3' },
  [CHAR_SOUND_DOH] = 'saori_hurt1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'saori_dead1.mp3' },
  -- [CHAR_SOUND_EEUH] = {'saori_naruhodo.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'saori_note2.mp3'},
  [CHAR_SOUND_HAHA] = { 'saori_omoshiroi.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'saori_starget1.mp3', 'saori_starget3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'saori_atk2.mp3' },                               -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'saori_yes.mp3',                                      -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'silent.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'saori_levelselect1.mp3' },                    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'saori_sorry.mp3',                                -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'saori_hurt3.mp3' },                             -- Touch Fire
  [CHAR_SOUND_OOOF] = 'saori_what.mp3',                                     -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'saori_hurt2.mp3',                                   -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'saori_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'saori_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'saori_atk1.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'saori_bthrow1.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'saori_drop.mp3',                     -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'saori_jump1.mp3' },               -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = 'saori_fall.mp3', -- Falling
  [CHAR_SOUND_WAH2] = 'saori_throw.mp3',                                   -- Throw Object
  [CHAR_SOUND_WHOA] = 'saori_ledgegrab.mp3',                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'saori_longjump1.mp3', 'saori_atk4.mp3' },        -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'saori_atk3.mp3', 'saori_atk4.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'saori_jump1.mp3', 'saori_atk1.mp3' },      -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'silent.mp3'},
}
VT_NATSU = {
  [CHAR_SOUND_ATTACKED] = { 'natsu_dmg1.mp3', 'natsu_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'natsu_are1.mp3',           -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'natsu_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'natsu_slowclimb.mp3' }, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'natsu_atk3.mp3' },
  [CHAR_SOUND_HAHA] = { 'natsu_sugoi.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'natsu_star1.mp3', 'natsu_star2.mp3', 'natsu_star3.mp3', 'natsu_star4.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'natsu_jump2.mp3' },                                                              -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'natsu_grab.mp3',                                                                     -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'natsu_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'natsu_ls1.mp3', 'natsu_ls2.mp3' },                                            -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'natsu_getup.mp3' },                                                            -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'natsu_dmg3.mp3' },                                                              -- Touch Fire
  [CHAR_SOUND_OOOF] = 'natsu_hm1.mp3',                                                                      -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'natsu_dmg2.mp3',                                                                    -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'natsu_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'natsu_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'natsu_atk1.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'natsu_bthrow1.mp3' },             -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'natsu_sugoi.mp3' },                  -- Boing
  [CHAR_SOUND_UH] = 'natsu_dmg1.mp3',                                 -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'natsu_atk2.mp3' },                            -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'natsu_falling.mp3',                        -- Falling
  [CHAR_SOUND_WAH2] = { 'natsu_bthrow1.mp3' },                        -- Throw Object
  [CHAR_SOUND_WHOA] = 'natsu_are1.mp3',                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'natsu_atk4.mp3' },                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'natsu_atk4.mp3' },              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'natsu_jump1.mp3', 'natsu_atk1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'silent.mp3'},
}
