-- BA Pack 1
-- Character Voice Tables





VT_KOKONA = {
  [CHAR_SOUND_ATTACKED] = { 'kokona_dmg4.mp3', 'kokona_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'kokona_ah2.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'kokona_dead1.mp3' },
  --[CHAR_SOUND_EEUH] = nil, -- Slow Get up from ledge
  --[CHAR_SOUND_GAME_OVER] = nil,
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'kokona_atk6.mp3' },
  [CHAR_SOUND_HAHA] = 'kokona_laugh.mp3', -- Landing after backflip
  --[CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  --[CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'kokona_starget1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'kokona_jump2.mp3',            -- 2nd Jump + Dive Attack
  --[CHAR_SOUND_HRMM] = nil, -- Object Pick-up
  --[CHAR_SOUND_IMA_TIRED] = nil,
  [CHAR_SOUND_LETS_A_GO] = 'kokona_levelselect.mp3', -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'kokona_daijobu.mp3',      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'kokona_onfire.mp3' },    -- Touch Fire
  [CHAR_SOUND_OOOF] = 'kokona_eh1.mp3',
  [CHAR_SOUND_OOOF2] = 'kokona_dmg2.mp3',            -- Landing After a Bonk + Thrown out of level
  --[CHAR_SOUND_PANTING] = nil, -- Low Health
  --[CHAR_SOUND_PANTING_COLD] = nil,
  --[CHAR_SOUND_PRESS_START_TO_PLAY] = nil,
  [CHAR_SOUND_PUNCH_HOO] = { 'kokona_atk1.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'kokona_atk3.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'kokona_atk2.mp3',     -- 1st Punch
  --[CHAR_SOUND_SNORING1] = nil,
  --[CHAR_SOUND_SNORING2] = nil,
  --[CHAR_SOUND_SNORING3] = nil,
  [CHAR_SOUND_SO_LONGA_BOWSER] = 'kokona_atk1.mp3', -- Bowser Throw
  --[CHAR_SOUND_TWIRL_BOUNCE] = nil, -- Boing
  [CHAR_SOUND_UH] = 'kokona_ah1.mp3',               -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'kokona_atk2.mp3' },         -- Quick Ledge Get-Up
  --[CHAR_SOUND_UH2_2] = nil, -- Landing after Long Jump
  --[CHAR_SOUND_WAAAOOOW] = nil, -- Falling
  [CHAR_SOUND_WAH2] = 'kokona_atk2.mp3',                                                   -- Throw Object
  [CHAR_SOUND_WHOA] = 'kokona_ah1.mp3',                                                    -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'kokona_atk1.mp3' },                                              -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'kokona_atk3.mp3' },                                  -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'kokona_jump7.mp3', 'kokona_atk6.mp3', 'kokona_atk5.mp3' }, -- 1st Jump(s)
  --[CHAR_SOUND_YAWNING] = nil,
}

VT_IZUNA = {
  [CHAR_SOUND_ATTACKED] = { 'izuna_dmg1.mp3', 'izuna_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'izuna_uu1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'izuna_dead1.mp3' },
  -- [CHAR_SOUND_EEUH] = nil, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = nil,
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'himari_atk1.mp3'},
  [CHAR_SOUND_HAHA] = 'izuna_desu.mp3', -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'izuna_star.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'izuna_jump2.mp3',        -- 2nd Jump + Dive Attack
  -- [CHAR_SOUND_HRMM] = 'himari_pickup.mp3', -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = nil,
  [CHAR_SOUND_LETS_A_GO] = 'izuna_nin2.mp3',   -- Level Select
  -- [CHAR_SOUND_MAMA_MIA] = 'kokona_daijobu.mp3', -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'izuna_fire.mp3' }, -- Touch Fire
  [CHAR_SOUND_OOOF] = 'izuna_eh1.mp3',         -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'izuna_dmg3.mp3',       -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {nil,}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = nil,
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = nil,
  [CHAR_SOUND_PUNCH_HOO] = { 'izuna_atk2.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'izuna_atk4.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'izuna_atk3.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = nil,
  -- [CHAR_SOUND_SNORING2] = nil,
  -- [CHAR_SOUND_SNORING3] = nil,
  [CHAR_SOUND_SO_LONGA_BOWSER] = 'izuna_atk2.mp3', -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = nil, -- Boing
  [CHAR_SOUND_UH] = 'izuna_uu1.mp3',               -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'izuna_quickledge.mp3' },   -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = nil, -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'izuna_ehh.ogg', -- Falling
  [CHAR_SOUND_WAH2] = 'izuna_atk1.mp3',                                    -- Throw Object
  [CHAR_SOUND_WHOA] = 'izuna_ah1.mp3',                                     -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'izuna_nin1.mp3' },                               -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'izuna_nin1.mp3', 'izuna_atk2.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'izuna_atk1.mp3', 'izuna_jump4.mp3' }       -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = nil,
}
VT_TSUKUYO = {
  [CHAR_SOUND_ATTACKED] = { 'tsukuyo_dmg4.mp3', 'tsukuyo_dmg2.mp3', 'tsukuyo_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'tsukuyo_ah1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'tsukuyo_dead.mp3' },
  -- [CHAR_SOUND_EEUH] = {nil,}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = nil,
  -- [CHAR_SOUND_GROUND_POUND_WAH] = nil,
  [CHAR_SOUND_HAHA] = 'tsukuyo_laugh.mp3', -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'tsukuyo_star.mp3' },                 -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'tsukuyo_jump2.mp3',                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'tsukuyo_pickup.mp3',                         -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = nil,
  [CHAR_SOUND_LETS_A_GO] = 'tsukuyo_levelselect1.mp3',              -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'tsukuyo_getup.mp3',                      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'tsukuyo_dmg3.mp3', 'tsukuyo_ah3.mp3' }, -- Touch Fire
  [CHAR_SOUND_OOOF] = 'tsukuyo_ah4.mp3',                            -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'tsukuyo_dmg1.mp3',                          -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {nil,}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = nil,
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = nil,
  [CHAR_SOUND_PUNCH_HOO] = { 'tsukuyo_atk1.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'tsukuyo_atk4.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'tsukuyo_atk3.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = nil,
  -- [CHAR_SOUND_SNORING2] = nil,
  -- [CHAR_SOUND_SNORING3] = nil,
  [CHAR_SOUND_SO_LONGA_BOWSER] = 'tsukuyo_atk1.mp3', -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = nil, -- Boing
  [CHAR_SOUND_UH] = 'tsukuyo_ah2.mp3',               -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'tsukuyo_atk2.mp3' },         -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = nil, -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = nil, -- Falling
  [CHAR_SOUND_WAH2] = 'tsukuyo_throw.mp3',                                                   -- Throw Object
  [CHAR_SOUND_WHOA] = 'tsukuyo_ah4.mp3',                                                     -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'tsukuyo_nin1.mp3' },                                               -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'tsukuyo_atk1.mp3' },                                   -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'tsukuyo_atk5.mp3', 'tsukuyo_atk6.mp3', 'tsukuyo_jump1.mp3' } -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = nil,
}
VT_MICHIRU = {
  [CHAR_SOUND_ATTACKED] = { 'michiru_dmg1.mp3', 'michiru_hua.mp3' },
  [CHAR_SOUND_DOH] = 'michiru_eh1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'michiru_dead1.mp3', 'michiru_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {nil,}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = nil,
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'michiru_atk7.mp3' },
  [CHAR_SOUND_HAHA] = 'michiru_laugh.mp3', -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'michiru_star.mp3' },                    -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'michiru_jump2.mp3',                           -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'michiru_pickup.mp3',                            -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = nil,
  [CHAR_SOUND_LETS_A_GO] = { 'michiru_levelselect1.mp3' },             -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'michiru_getup.mp3',                         -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'michiru_fire1.mp3', 'michiru_fire2.mp3' }, -- Touch Fire
  [CHAR_SOUND_OOOF] = 'michiru_eh1.mp3',                               -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'michiru_dmg2.mp3',                             -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {nil,}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = nil,
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = nil,
  [CHAR_SOUND_PUNCH_HOO] = { 'michiru_atk4.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'michiru_atk7.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'michiru_atk5.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = nil,
  -- [CHAR_SOUND_SNORING2] = nil,
  -- [CHAR_SOUND_SNORING3] = nil,
  [CHAR_SOUND_SO_LONGA_BOWSER] = 'michiru_atk2.mp3',                                          -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'michiru_huhn.mp3' },                                         -- Boing
  [CHAR_SOUND_UH] = 'michiru_ah1.mp3',                                                        -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'michiru_atk1.mp3' },                                                  -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = nil, -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'michiru_fall.mp3',                                                 -- Falling
  [CHAR_SOUND_WAH2] = 'michiru_throw.mp3',                                                    -- Throw Object
  [CHAR_SOUND_WHOA] = 'michiru_are1.mp3',                                                     -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'michiru_shuba.mp3' },                                               -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'michiru_atk2.mp3' },                                    -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'michiru_jump1.mp3', 'michiru_atk1.mp3', 'michiru_jump3.mp3' } -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = nil,
}





VT_CHISE = {
  [CHAR_SOUND_ATTACKED] = { 'chise_dmg1.mp3', 'chise_dmg2.mp3', 'chise_dmg3.mp3' },
  [CHAR_SOUND_DOH] = 'chise_uh1.mp3',            -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'chise_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'chise_slowclimb.mp3' }, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'chise_note1.mp3'},
  [CHAR_SOUND_HAHA] = { 'chise_note2.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'chise_star1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'chise_atk-jump1.mp3' }, -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'chise_grab.mp3',            -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'silent.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'chise_ls1.mp3' },    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'chise_getup.mp3',       -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'chise_fire1.mp3' },    -- Touch Fire
  [CHAR_SOUND_OOOF] = 'chise_uh2.mp3',             -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'chise_dmg3.mp3',           -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3',}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'chise_atk1.mp3' },  -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'chise_atk2.mp3',      -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'chise_atk-jump2.mp3', -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'chise_bthrow1.mp3', 'chise_bthrow2.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'chise_eh1.mp3',                                           -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'chise_uh3.mp3' },                                      -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'chise_fall.mp3',                                    -- Falling
  [CHAR_SOUND_WAH2] = 'chise_throw1.mp3',                                      -- Throw Object
  [CHAR_SOUND_WHOA] = 'chise_uh3.mp3',                                         -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'chise_longjump.mp3' },                               -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'chise_jump2.mp3' },                      -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'chise_jump1.mp3', 'chise_atk-jump2.mp3' },     -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'chise_yawn.mp3' },
}

VT_SAYA = {
  [CHAR_SOUND_ATTACKED] = { 'saya_dmg1.mp3', 'saya_dmg2.mp3', 'saya_dmg3.mp3' },
  [CHAR_SOUND_DOH] = 'saya_are1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'saya_dead1.mp3', 'saya_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {'chise_slowclimb.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'chise_note1.mp3'},
  [CHAR_SOUND_HAHA] = { 'saya_laugh2.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'saya_star1.mp3', 'saya_laugh1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'saya_jump4.mp3' },                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'saya_grab.mp3',                               -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'silent.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'saya_ls1.mp3' },                       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'saya_getup.mp3',                          -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'saya_dmg2.mp3' },                        -- Touch Fire
  [CHAR_SOUND_OOOF] = 'saya_hm1.mp3',                                -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'saya_dmg3.mp3',                              -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3',}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'saya_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'saya_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'saya_atk1.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'saya_bthrow1.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'saya_are1.mp3',                     -- Drop off of ledge + Fall off Ledge
  -- [CHAR_SOUND_UH2] = {'chise_uh3.mp3'}, -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = 'chise_fall.mp3', -- Falling
  [CHAR_SOUND_WAH2] = 'saya_throw.mp3',                                                -- Throw Object
  [CHAR_SOUND_WHOA] = 'saya_ledgegrab.mp3',                                            -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'saya_longjump.mp3' },                                        -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'saya_atk3.mp3' },                                -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'saya_jump1.mp3', 'saya_jump2.mp3', 'saya_jump3.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'chise_yawn.mp3'},
}



VT_SHIGURE = {
  [CHAR_SOUND_ATTACKED] = { 'shigure_dmg1.mp3', 'shigure_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'shigure_ah1.mp3',            -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'shigure_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'shigure_slowclimb.mp3' }, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'shigure_atk1.mp3' },
  [CHAR_SOUND_HAHA] = { 'shigure_laugh.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'shigure_star1.mp3', 'shigure_star2.mp3', 'shigure_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'shigure_jump4.mp3' },                                               -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'shigure_slowclimb.mp3',                                                 -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'shigure_hm2.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'shigure_ls1.mp3' },                                              -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'shigure_getup1.mp3', 'shigure_getup2.mp3' },                      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'shigure_dmg3.mp3' },                                               -- Touch Fire
  [CHAR_SOUND_OOOF] = 'shigure_eh1.mp3',                                                       -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'shigure_dmg1.mp3',                                                     -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'shigure_atk2.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'shigure_jump3.mp3',    -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'shigure_atk1.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'shigure_star2.mp3', 'shigure_wontwork.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'shigure_huh1.mp3',                                           -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'shigure_jump1.mp3' },                                     -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = 'saori_fall.mp3', -- Falling
  [CHAR_SOUND_WAH2] = { 'shigure_throw1.mp3', 'shigure_throw2.mp3' },      -- Throw Object
  [CHAR_SOUND_WHOA] = 'shigure_hm1.mp3',                                   -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'shigure_longjump.mp3' },                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'shigure_longjump.mp3' },             -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'shigure_jump1.mp3', 'shigure_jump3.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'silent.mp3'},
}
