-- BA Pack 1
-- Character Voice Tables



VT_MARI = {
  [CHAR_SOUND_ATTACKED] = { 'spmari_hurt3.mp3', 'spmari_hurt5.mp3', 'spmari_hurt2.mp3' },
  [CHAR_SOUND_DOH] = 'spmari_ah.mp3',               -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'spmari_dead.mp3' },
  [CHAR_SOUND_EEUH] = { 'spmari_ledgegetup.mp3', }, -- Slow Get up from ledge
  --[CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  --[CHAR_SOUND_GROUND_POUND_WAH] = {'silent.mp3'},
  [CHAR_SOUND_HAHA] = 'spmari_laugh.mp3', -- Landing after backflip
  --[CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  --[CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'spmari_subarashi.mp3', }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'spmari_attack6.mp3',            -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'spmari_pickup.mp3',               -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'spmari_pant.mp3',
  [CHAR_SOUND_LETS_A_GO] = 'spmari_levelselect.mp3',     -- Level Select
  --[CHAR_SOUND_MAMA_MIA] = 'silent.mp3', -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'spmari_hurt1.mp3', },        -- Touch Fire
  [CHAR_SOUND_OOOF] = 'spmari_ah.mp3',
  [CHAR_SOUND_OOOF2] = 'spmari_hurt4.mp3',               -- Landing After a Bonk + Thrown out of level
  --[CHAR_SOUND_PANTING] = {'silent.mp3',}, -- Low Health
  --[CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  --[CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'spmari_attack5.mp3', }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'spmari_attack6.mp3',      --2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'spmari_attack1.mp3',      -- 1st Punch
  --[CHAR_SOUND_SNORING1] = 'silent.mp3',
  --[CHAR_SOUND_SNORING2] = 'silent.mp3',
  --[CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'spmari_rip.mp3' },                                             --Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'spmari_laugh.mp3' },                                              -- Boing
  [CHAR_SOUND_UH] = 'spmari_uh1.mp3',                                                              --Drop off of ledge
  [CHAR_SOUND_UH2] = { 'spmari_attack7.mp3', },                                                    -- Quick Ledge Get-Up
  [CHAR_SOUND_UH2_2] = 'spmari_attack9.mp3',                                                       -- Landing after Long Jump
  --[CHAR_SOUND_WAAAOOOW] = 'silent.mp3', -- Falling
  [CHAR_SOUND_WAH2] = 'spmari_attack5.mp3',                                                        -- Throw Object
  [CHAR_SOUND_WHOA] = 'spmari_uh1.mp3',                                                            -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'spmari_attack3.mp3', },                                                  -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'spmari_attack3.mp3', },                                      -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'spmari_attack7.mp3', 'spmari_attack1.mp3', 'spmari_attack8.mp3' }, -- 1st Jump(s)
  --[CHAR_SOUND_YAWNING] = 'silent.mp3',
}
VT_KAZUSA = {
  [CHAR_SOUND_ATTACKED] = { 'kazusa_dmg1.mp3', 'kazusa_dmg3.mp3' },
  [CHAR_SOUND_DOH] = 'kazusa_what.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'kazusa_dead.mp3' },
  --[CHAR_SOUND_EEUH] = nil, -- Slow Get up from ledge
  --[CHAR_SOUND_GAME_OVER] = nil,
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'kazusa_groundpound.mp3' },
  --[CHAR_SOUND_HAHA] = nil, -- Landing after backflip
  --[CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  --[CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'kazusa_sugoi.mp3', 'kazusa_star1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'kazusa_jump4.mp3',                             -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'kazusa_pickup.mp3',                              -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'kazusa_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = 'kazusa_levelselect.mp3',                    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'kazusa_levelexit.mp3',                       -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'kazusa_what.mp3' },                         -- Touch Fire
  [CHAR_SOUND_OOOF] = 'kazusa_eh1.mp3',                                 -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'kazusa_dmg2.mp3',                               -- Landing After a Bonk + Thrown out of level
  --[CHAR_SOUND_PANTING] = nil, -- Low Health
  --[CHAR_SOUND_PANTING_COLD] = nil,
  --[CHAR_SOUND_PRESS_START_TO_PLAY] = nil,
  [CHAR_SOUND_PUNCH_HOO] = { 'kazusa_ora.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'kazusa_atk4.mp3',    -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'kazusa_atk1.mp3',    -- 1st Punch
  --[CHAR_SOUND_SNORING1] = nil,
  --[CHAR_SOUND_SNORING2] = nil,
  --[CHAR_SOUND_SNORING3] = nil,
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'kazusa_bowserthrow.mp3' },       -- Bowser Throw
  --[CHAR_SOUND_TWIRL_BOUNCE] = nil, -- Boing
  [CHAR_SOUND_UH] = 'kazusa_eh2.mp3',                                -- Drop off of ledge
  [CHAR_SOUND_UH2] = { 'kazusa_jump2.mp3' },                         -- Quick Ledge Get-Up
  --[CHAR_SOUND_UH2_2] = nil, -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = { 'kazusa_fall.mp3', 'kazusa_fall2.mp3' }, -- Falling
  [CHAR_SOUND_WAH2] = 'kazusa_ora.mp3',                              -- Throw Object
  [CHAR_SOUND_WHOA] = 'kazusa_wah2.mp3',                             -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'kazusa_jump3.mp3' },                       -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'kazusa_jump3.mp3' },           -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = {
    'kazusa_jump1.mp3', 'kazusa_jump5.mp3', 'kazusa_jump2.mp3'
  }, -- 1st Jump(s)
  --[CHAR_SOUND_YAWNING] = nil,
}

VT_KOKONA = {
  [CHAR_SOUND_ATTACKED] = { 'kokona_dmg4.mp3', 'kokona_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'kokona_ah2.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'kokona_dead1.mp3' },
  --[CHAR_SOUND_EEUH] = nil, -- Slow Get up from ledge
  --[CHAR_SOUND_GAME_OVER] = nil,
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'kokona_atk6.mp3' },
  [CHAR_SOUND_HAHA] = 'kokona_laugh.mp3', -- Landing after backflip
  --[CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  --[CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'kokona_starget1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'kokona_jump2.mp3',            -- 2nd Jump + Dive Attack
  --[CHAR_SOUND_HRMM] = nil, -- Object Pick-up
  --[CHAR_SOUND_IMA_TIRED] = nil,
  [CHAR_SOUND_LETS_A_GO] = 'kokona_levelselect.mp3', -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'kokona_daijobu.mp3',      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'kokona_onfire.mp3' },    -- Touch Fire
  [CHAR_SOUND_OOOF] = 'kokona_eh1.mp3',
  [CHAR_SOUND_OOOF2] = 'kokona_dmg2.mp3',            -- Landing After a Bonk + Thrown out of level
  --[CHAR_SOUND_PANTING] = nil, -- Low Health
  --[CHAR_SOUND_PANTING_COLD] = nil,
  --[CHAR_SOUND_PRESS_START_TO_PLAY] = nil,
  [CHAR_SOUND_PUNCH_HOO] = { 'kokona_atk1.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'kokona_atk3.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'kokona_atk2.mp3',     -- 1st Punch
  --[CHAR_SOUND_SNORING1] = nil,
  --[CHAR_SOUND_SNORING2] = nil,
  --[CHAR_SOUND_SNORING3] = nil,
  [CHAR_SOUND_SO_LONGA_BOWSER] = 'kokona_atk1.mp3', -- Bowser Throw
  --[CHAR_SOUND_TWIRL_BOUNCE] = nil, -- Boing
  [CHAR_SOUND_UH] = 'kokona_ah1.mp3',               -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'kokona_atk2.mp3' },         -- Quick Ledge Get-Up
  --[CHAR_SOUND_UH2_2] = nil, -- Landing after Long Jump
  --[CHAR_SOUND_WAAAOOOW] = nil, -- Falling
  [CHAR_SOUND_WAH2] = 'kokona_atk2.mp3',                                                   -- Throw Object
  [CHAR_SOUND_WHOA] = 'kokona_ah1.mp3',                                                    -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'kokona_atk1.mp3' },                                              -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'kokona_atk3.mp3' },                                  -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'kokona_jump7.mp3', 'kokona_atk6.mp3', 'kokona_atk5.mp3' }, -- 1st Jump(s)
  --[CHAR_SOUND_YAWNING] = nil,
}

VT_IZUNA = {
  [CHAR_SOUND_ATTACKED] = { 'izuna_dmg1.mp3', 'izuna_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'izuna_uu1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'izuna_dead1.mp3' },
  -- [CHAR_SOUND_EEUH] = nil, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = nil,
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'himari_atk1.mp3'},
  [CHAR_SOUND_HAHA] = 'izuna_desu.mp3', -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'izuna_star.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'izuna_jump2.mp3',        -- 2nd Jump + Dive Attack
  -- [CHAR_SOUND_HRMM] = 'himari_pickup.mp3', -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = nil,
  [CHAR_SOUND_LETS_A_GO] = 'izuna_nin2.mp3',   -- Level Select
  -- [CHAR_SOUND_MAMA_MIA] = 'kokona_daijobu.mp3', -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'izuna_fire.mp3' }, -- Touch Fire
  [CHAR_SOUND_OOOF] = 'izuna_eh1.mp3',         -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'izuna_dmg3.mp3',       -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {nil,}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = nil,
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = nil,
  [CHAR_SOUND_PUNCH_HOO] = { 'izuna_atk2.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'izuna_atk4.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'izuna_atk3.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = nil,
  -- [CHAR_SOUND_SNORING2] = nil,
  -- [CHAR_SOUND_SNORING3] = nil,
  [CHAR_SOUND_SO_LONGA_BOWSER] = 'izuna_atk2.mp3', -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = nil, -- Boing
  [CHAR_SOUND_UH] = 'izuna_uu1.mp3',               -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'izuna_quickledge.mp3' },   -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = nil, -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'izuna_ehh.ogg', -- Falling
  [CHAR_SOUND_WAH2] = 'izuna_atk1.mp3',                                    -- Throw Object
  [CHAR_SOUND_WHOA] = 'izuna_ah1.mp3',                                     -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'izuna_nin1.mp3' },                               -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'izuna_nin1.mp3', 'izuna_atk2.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'izuna_atk1.mp3', 'izuna_jump4.mp3' }       -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = nil,
}
VT_TSUKUYO = {
  [CHAR_SOUND_ATTACKED] = { 'tsukuyo_dmg4.mp3', 'tsukuyo_dmg2.mp3', 'tsukuyo_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'tsukuyo_ah1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'tsukuyo_dead.mp3' },
  -- [CHAR_SOUND_EEUH] = {nil,}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = nil,
  -- [CHAR_SOUND_GROUND_POUND_WAH] = nil,
  [CHAR_SOUND_HAHA] = 'tsukuyo_laugh.mp3', -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'tsukuyo_star.mp3' },                 -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'tsukuyo_jump2.mp3',                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'tsukuyo_pickup.mp3',                         -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = nil,
  [CHAR_SOUND_LETS_A_GO] = 'tsukuyo_levelselect1.mp3',              -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'tsukuyo_getup.mp3',                      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'tsukuyo_dmg3.mp3', 'tsukuyo_ah3.mp3' }, -- Touch Fire
  [CHAR_SOUND_OOOF] = 'tsukuyo_ah4.mp3',                            -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'tsukuyo_dmg1.mp3',                          -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {nil,}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = nil,
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = nil,
  [CHAR_SOUND_PUNCH_HOO] = { 'tsukuyo_atk1.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'tsukuyo_atk4.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'tsukuyo_atk3.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = nil,
  -- [CHAR_SOUND_SNORING2] = nil,
  -- [CHAR_SOUND_SNORING3] = nil,
  [CHAR_SOUND_SO_LONGA_BOWSER] = 'tsukuyo_atk1.mp3', -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = nil, -- Boing
  [CHAR_SOUND_UH] = 'tsukuyo_ah2.mp3',               -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'tsukuyo_atk2.mp3' },         -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = nil, -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = nil, -- Falling
  [CHAR_SOUND_WAH2] = 'tsukuyo_throw.mp3',                                                   -- Throw Object
  [CHAR_SOUND_WHOA] = 'tsukuyo_ah4.mp3',                                                     -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'tsukuyo_nin1.mp3' },                                               -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'tsukuyo_atk1.mp3' },                                   -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'tsukuyo_atk5.mp3', 'tsukuyo_atk6.mp3', 'tsukuyo_jump1.mp3' } -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = nil,
}
VT_MICHIRU = {
  [CHAR_SOUND_ATTACKED] = { 'michiru_dmg1.mp3', 'michiru_hua.mp3' },
  [CHAR_SOUND_DOH] = 'michiru_eh1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'michiru_dead1.mp3', 'michiru_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {nil,}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = nil,
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'michiru_atk7.mp3' },
  [CHAR_SOUND_HAHA] = 'michiru_laugh.mp3', -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = nil, -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = nil,
  [CHAR_SOUND_HERE_WE_GO] = { 'michiru_star.mp3' },                    -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'michiru_jump2.mp3',                           -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'michiru_pickup.mp3',                            -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = nil,
  [CHAR_SOUND_LETS_A_GO] = { 'michiru_levelselect1.mp3' },             -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'michiru_getup.mp3',                         -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'michiru_fire1.mp3', 'michiru_fire2.mp3' }, -- Touch Fire
  [CHAR_SOUND_OOOF] = 'michiru_eh1.mp3',                               -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'michiru_dmg2.mp3',                             -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {nil,}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = nil,
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = nil,
  [CHAR_SOUND_PUNCH_HOO] = { 'michiru_atk4.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'michiru_atk7.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'michiru_atk5.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = nil,
  -- [CHAR_SOUND_SNORING2] = nil,
  -- [CHAR_SOUND_SNORING3] = nil,
  [CHAR_SOUND_SO_LONGA_BOWSER] = 'michiru_atk2.mp3',                                          -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'michiru_huhn.mp3' },                                         -- Boing
  [CHAR_SOUND_UH] = 'michiru_ah1.mp3',                                                        -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'michiru_atk1.mp3' },                                                  -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = nil, -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'michiru_fall.mp3',                                                 -- Falling
  [CHAR_SOUND_WAH2] = 'michiru_throw.mp3',                                                    -- Throw Object
  [CHAR_SOUND_WHOA] = 'michiru_are1.mp3',                                                     -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'michiru_shuba.mp3' },                                               -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'michiru_atk2.mp3' },                                    -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'michiru_jump1.mp3', 'michiru_atk1.mp3', 'michiru_jump3.mp3' } -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = nil,
}


VT_AZUSA = {
  [CHAR_SOUND_ATTACKED] = { 'azusa_dmg3.mp3', 'azusa_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'azusa_eh1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'azusa_dead1.mp3', 'azusa_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {'nil',}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'nil'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'azusa_atk3.mp3' },
  [CHAR_SOUND_HAHA] = 'azusa_grab.mp3', -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'hiyori_really.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'nil',
  [CHAR_SOUND_HERE_WE_GO] = { 'azusa_starget1.mp3', 'azusa_vanitas2.mp3' }, -- Star Get + Obtaining Power-up + Bowser Throw when not full speed
  [CHAR_SOUND_HOOHOO] = 'azusa_atk5.mp3',                                   -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'azusa_grab.mp3',                                     -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'nil',
  [CHAR_SOUND_LETS_A_GO] = { 'azusa_ls1.mp3', 'azusa_vanitas3.mp3' },       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'azusa_getup.mp3',                                -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'azusa_dmg4.mp3' },                              -- Touch Fire
  [CHAR_SOUND_OOOF] = 'azusa_ah1.mp3',                                      -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'azusa_dmg5.mp3',                                    -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'nil',}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'nil',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'nil', 'nil'},
  [CHAR_SOUND_PUNCH_HOO] = { 'azusa_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'azusa_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'azusa_atk1.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'nil',
  -- [CHAR_SOUND_SNORING2] = 'nil',
  -- [CHAR_SOUND_SNORING3] = {'nil', 'nil'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'azusa_bowserthrow1.mp3' },                        -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'nil'}, -- Boing
  [CHAR_SOUND_UH] = 'azusa_ah2.mp3',                                                  -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'azusa_atk6.mp3' },                                            -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'nil', -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = { 'azusa_falling1.mp3' },                                   -- Falling
  [CHAR_SOUND_WAH2] = 'azusa_throw.mp3',                                              -- Throw Object
  [CHAR_SOUND_WHOA] = 'azusa_are1.mp3',                                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'azusa_vanitas1.mp3' },                                      -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'azusa_atk3.mp3' },                              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'azusa_atk4.mp3', 'azusa_atk5.mp3', 'azusa_atk1.mp3' } -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = 'nil',
}
VT_HIYORI = {
  [CHAR_SOUND_ATTACKED] = { 'hiyori_hurt2.mp3', 'hiyori_hurt1.mp3' },
  [CHAR_SOUND_DOH] = 'hiyori_hai.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'hiyori_dead1.mp3', 'hiyori_dead2.mp3', 'hiyori_dead3.mp3' },
  -- [CHAR_SOUND_EEUH] = {'nil',}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'nil'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'hiyori_atk4.mp3' },
  [CHAR_SOUND_HAHA] = 'hiyori_laugh1.mp3',                                    -- Landing after backflip
  [CHAR_SOUND_HAHA_2] = 'hiyori_laugh2.mp3',                                  -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'nil',
  [CHAR_SOUND_HERE_WE_GO] = { 'hiyori_starget1.mp3', 'hiyori_starget2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = 'hiyori_atk5.mp3',                                    -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'hiyori_pickup.mp3',                                    -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'hiyori_um.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'hiyori_ls1.mp3' },                              -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'hiyori_sorry.mp3',                                 -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'hiyori_fire.mp3' },                               -- Touch Fire
  [CHAR_SOUND_OOOF] = 'hiyori_eh1.mp3',                                       -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'hiyori_hurt2.mp3',                                    -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'nil',}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'nil',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'nil', 'nil'},
  [CHAR_SOUND_PUNCH_HOO] = { 'hiyori_atk1.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'hiyori_atk6.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'hiyori_atk3.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'nil',
  -- [CHAR_SOUND_SNORING2] = 'nil',
  -- [CHAR_SOUND_SNORING3] = {'nil', 'nil'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'hiyori_bowserthrow1.mp3' },                            -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'hiyori_laugh1.mp3' },                                     -- Boing
  [CHAR_SOUND_UH] = 'hiyori_hurt3.mp3',                                                    -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'hiyori_atk5.mp3' },                                                -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'nil', -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'hiyori_falling1.mp3',                                           -- Falling
  [CHAR_SOUND_WAH2] = 'hiyori_throw.mp3',                                                  -- Throw Object
  [CHAR_SOUND_WHOA] = 'hiyori_eh1.mp3',                                                    -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'hiyori_longjump.mp3' },                                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'hiyori_longjump.mp3' },                              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'hiyori_note1.mp3', 'hiyori_atk7.mp3', 'hiyori_atk2.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = 'nil',
}

VT_JUNKO = {
  [CHAR_SOUND_ATTACKED] = { 'junko_dmg1.mp3', 'junko_dmg4.mp3', 'junko_dmg5.mp3' },
  [CHAR_SOUND_DOH] = 'junko_ah1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'junko_dead1.mp3' },
  --[CHAR_SOUND_EEUH] = {'junko_ledgeclimb.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'junko_atk5.mp3' },
  [CHAR_SOUND_HAHA] = { 'junko_laugh1.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'junko_star1.mp3', 'junko_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'junko_jump2.mp3' },                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'junko_pickup.mp3',                             -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'junko_tired2.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'junko_ls1.mp3' },                       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'junko_getup1.mp3',                         -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'junko_dmg3.mp3' },                        -- Touch Fire
  [CHAR_SOUND_OOOF] = 'junko_grabbed.mp3',                            -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'junko_dmg1.mp3',                              -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3',}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'junko_atk4.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'junko_atk1.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'junko_atk2.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'junko_bthrow1.mp3' },             -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'junko_ueh.mp3',                                  -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'junko_atk2.mp3' },                            -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'junko_dead2.mp3',                          -- Falling
  [CHAR_SOUND_WAH2] = 'junko_atk5.mp3',                               -- Throw Object
  [CHAR_SOUND_WHOA] = 'junko_ledgegrab.mp3',                          -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'junko_yaho.mp3' },                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'junko_atk4.mp3' },              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'junko_atk2.mp3', 'junko_jump1.mp3' }, -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'junko_tired1.mp3' },
}
VT_CHISE = {
  [CHAR_SOUND_ATTACKED] = { 'chise_dmg1.mp3', 'chise_dmg2.mp3', 'chise_dmg3.mp3' },
  [CHAR_SOUND_DOH] = 'chise_uh1.mp3',            -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'chise_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'chise_slowclimb.mp3' }, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'chise_note1.mp3'},
  [CHAR_SOUND_HAHA] = { 'chise_note2.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'chise_star1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'chise_atk-jump1.mp3' }, -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'chise_grab.mp3',            -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'silent.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'chise_ls1.mp3' },    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'chise_getup.mp3',       -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'chise_fire1.mp3' },    -- Touch Fire
  [CHAR_SOUND_OOOF] = 'chise_uh2.mp3',             -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'chise_dmg3.mp3',           -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3',}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'chise_atk1.mp3' },  -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'chise_atk2.mp3',      -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'chise_atk-jump2.mp3', -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'chise_bthrow1.mp3', 'chise_bthrow2.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'chise_eh1.mp3',                                           -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'chise_uh3.mp3' },                                      -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'chise_fall.mp3',                                    -- Falling
  [CHAR_SOUND_WAH2] = 'chise_throw1.mp3',                                      -- Throw Object
  [CHAR_SOUND_WHOA] = 'chise_uh3.mp3',                                         -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'chise_longjump.mp3' },                               -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'chise_jump2.mp3' },                      -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'chise_jump1.mp3', 'chise_atk-jump2.mp3' },     -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'chise_yawn.mp3' },
}

VT_SAYA = {
  [CHAR_SOUND_ATTACKED] = { 'saya_dmg1.mp3', 'saya_dmg2.mp3', 'saya_dmg3.mp3' },
  [CHAR_SOUND_DOH] = 'saya_are1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'saya_dead1.mp3', 'saya_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {'chise_slowclimb.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'chise_note1.mp3'},
  [CHAR_SOUND_HAHA] = { 'saya_laugh2.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'saya_star1.mp3', 'saya_laugh1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'saya_jump4.mp3' },                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'saya_grab.mp3',                               -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'silent.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'saya_ls1.mp3' },                       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'saya_getup.mp3',                          -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'saya_dmg2.mp3' },                        -- Touch Fire
  [CHAR_SOUND_OOOF] = 'saya_hm1.mp3',                                -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'saya_dmg3.mp3',                              -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3',}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'saya_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'saya_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'saya_atk1.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'saya_bthrow1.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'saya_are1.mp3',                     -- Drop off of ledge + Fall off Ledge
  -- [CHAR_SOUND_UH2] = {'chise_uh3.mp3'}, -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = 'chise_fall.mp3', -- Falling
  [CHAR_SOUND_WAH2] = 'saya_throw.mp3',                                                -- Throw Object
  [CHAR_SOUND_WHOA] = 'saya_ledgegrab.mp3',                                            -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'saya_longjump.mp3' },                                        -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'saya_atk3.mp3' },                                -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'saya_jump1.mp3', 'saya_jump2.mp3', 'saya_jump3.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'chise_yawn.mp3'},
}
VT_ARU = {
  [CHAR_SOUND_ATTACKED] = { 'aru_dmg1.mp3', 'aru_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'aru_dmg1.mp3',
  [CHAR_SOUND_DYING] = 'aru_dying.mp3',
  [CHAR_SOUND_PUNCH_HOO] = 'aru_kick.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = 'aru_yahoo.mp3',
  [CHAR_SOUND_HAHA] = 'aru_laugh.mp3',
  [CHAR_SOUND_HAHA_2] = 'aru_laugh.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'aru_letsGo.mp3', 'aru_letsGo2.mp3' },
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'aru_yahoo.mp3' },
  [CHAR_SOUND_HOOHOO] = 'aru_jump2.mp3',
  [CHAR_SOUND_YAHOO] = 'aru_yahoo.mp3',
  [CHAR_SOUND_EEUH] = 'aru_ledgeUp.mp3',
  [CHAR_SOUND_MAMA_MIA] = { 'aru_levelFail.mp3', 'aru_levelFail2.mp3' },
  [CHAR_SOUND_HRMM] = 'aru_hmm.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'aru_star.mp3', 'aru_bowser2.mp3' },
  [CHAR_SOUND_UH] = 'aru_eh.mp3',
  -- [CHAR_SOUND_UH2] = 'aru_jump1_2.mp3',
  [CHAR_SOUND_OOOF] = 'aru_dmg1.mp3',
  [CHAR_SOUND_YAH_WAH_HOO] = { 'aru_jump1.mp3', 'aru_jump1_2.mp3' },
  [CHAR_SOUND_OOOF2] = 'aru_dmg2.mp3',
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = 'aru_jump3.mp3',
  [CHAR_SOUND_PUNCH_YAH] = 'aru_punch2.mp3',
  [CHAR_SOUND_PUNCH_WAH] = 'aru_punch1.mp3',
  [CHAR_SOUND_WAAAOOOW] = 'aru_falling.mp3',
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'aru_bowser.mp3' },
  [CHAR_SOUND_WHOA] = 'aru_ledgeGrab.mp3',
  [CHAR_SOUND_ON_FIRE] = 'aru_burn.mp3',
  [CHAR_SOUND_IMA_TIRED] = 'aru_yawn.mp3',
}
VT_ATSUKO = {
  [CHAR_SOUND_ATTACKED] = { 'atsk_dmg1.mp3', 'atsk_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'atsk_eh1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'atsk_dead1.mp3', 'atsk_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {'chise_slowclimb.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'chise_note1.mp3'},
  -- [CHAR_SOUND_HAHA] = {'saya_laugh2.mp3'}, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'atsk_star1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'atsk_jump1.mp3' },     -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'atsk_atk1.mp3',            -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'atsk_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'atsk_ls1.mp3' },    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'atsk_getup.mp3',       -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'atsk_dmg2.mp3' },     -- Touch Fire
  [CHAR_SOUND_OOOF] = 'atsk_hm1.mp3',             -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'atsk_dmg2.mp3',           -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3',}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'atsk_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'atsk_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'atsk_atk2.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'atsk_muda.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'atsk_ah1.mp3',                   -- Drop off of ledge + Fall off Ledge
  -- [CHAR_SOUND_UH2] = {'chise_uh3.mp3'}, -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = 'chise_fall.mp3', -- Falling
  [CHAR_SOUND_WAH2] = 'atsk_atk1.mp3',                                              -- Throw Object
  [CHAR_SOUND_WHOA] = 'atsk_ah1.mp3',                                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'atsk_atk3.mp3' },                                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'atsk_atk3.mp3' },                             -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'atsk_atk6.mp3', 'atsk_atk5.mp3', 'atsk_atk4.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'chise_yawn.mp3'},
}
VT_MISAKI = {
  [CHAR_SOUND_ATTACKED] = { 'misaki_hurt1.mp3', 'misaki_hurt2.mp3'},
  [CHAR_SOUND_DOH] = 'misaki_eh1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'misaki_dead1.mp3', 'misaki_dead2.mp3' },
  -- [CHAR_SOUND_EEUH] = {'misaki_ledgeclimb.mp3',}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'misaki_atk5.mp3' },
  -- [CHAR_SOUND_HAHA] = {'silent.mp3'}, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'misaki_star1.mp3' },                   -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'misaki_atk2.mp3' },                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'misaki_grab.mp3',                              -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'silent.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'misaki_levelselect3.mp3' },             -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'misaki_sorry.mp3', 'misaki_getup.mp3' }, -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'misaki_hurt1.mp3' },                      -- Touch Fire
  [CHAR_SOUND_OOOF] = 'misaki_what.mp3',                              -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'misaki_hurt2.mp3',                            -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = 'misaki_atk3.mp3', -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'misaki_atk2.mp3', -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'misaki_atk4.mp3', -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'misaki_bthrow1.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'misaki_eh1.mp3',                      -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'misaki_atk2.mp3' },                -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = 'misaki_fall.mp3', -- Falling
  [CHAR_SOUND_WAH2] = 'misaki_atk5.mp3',                                -- Throw Object
  [CHAR_SOUND_WHOA] = 'misaki_eh1.mp3',                                 -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'misaki_atk3.mp3' },                           -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'misaki_atk3.mp3' },               -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'misaki_atk2.mp3', 'misaki_jump1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'silent.mp3'},
}
VT_SAORI = {
  [CHAR_SOUND_ATTACKED] = { 'saori_hurt1.mp3', 'saori_hurt2.mp3', 'saori_hurt3.mp3' },
  [CHAR_SOUND_DOH] = 'saori_hurt1.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'saori_dead1.mp3' },
  -- [CHAR_SOUND_EEUH] = {'saori_naruhodo.mp3'}, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'saori_note2.mp3'},
  [CHAR_SOUND_HAHA] = { 'saori_omoshiroi.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'saori_starget1.mp3', 'saori_starget3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'saori_atk2.mp3' },                               -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'saori_yes.mp3',                                      -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'silent.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'saori_levelselect1.mp3' },                    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = 'saori_sorry.mp3',                                -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'saori_hurt3.mp3' },                             -- Touch Fire
  [CHAR_SOUND_OOOF] = 'saori_what.mp3',                                     -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'saori_hurt2.mp3',                                   -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'saori_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'saori_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'saori_atk1.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'saori_bthrow1.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'saori_drop.mp3',                     -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'saori_jump1.mp3' },               -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = 'saori_fall.mp3', -- Falling
  [CHAR_SOUND_WAH2] = 'saori_throw.mp3',                                   -- Throw Object
  [CHAR_SOUND_WHOA] = 'saori_ledgegrab.mp3',                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'saori_longjump1.mp3', 'saori_atk4.mp3' },        -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'saori_atk3.mp3', 'saori_atk4.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'saori_jump1.mp3', 'saori_atk1.mp3' },      -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'silent.mp3'},
}
VT_SHOSHINO = {
  [CHAR_SOUND_ATTACKED] = { 'shoshino_dmg1.mp3', 'shoshino_dmg2.mp3' },
  [CHAR_SOUND_DYING] = 'shoshino_dying.mp3',
  [CHAR_SOUND_DOH] = 'shoshino_dmg1.mp3',
  [CHAR_SOUND_PUNCH_HOO] = 'shoshino_kick.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = 'shoshino_yahoo.mp3',
  [CHAR_SOUND_HAHA] = 'shoshino_laugh.mp3',
  [CHAR_SOUND_HAHA_2] = 'shoshino_laugh.mp3',
  [CHAR_SOUND_LETS_A_GO] = 'shoshino_letsGo.mp3',
  [CHAR_SOUND_HOOHOO] = { 'shoshino_jump2.mp3' },
  [CHAR_SOUND_YAHOO] = 'shoshino_yahoo.mp3',
  [CHAR_SOUND_EEUH] = 'shoshino_ledgeUp.mp3',
  [CHAR_SOUND_MAMA_MIA] = 'shoshino_levelFail.mp3',
  [CHAR_SOUND_HRMM] = 'shoshino_hmm.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'shoshino_star.mp3', 'shoshino_star2.mp3' },
  [CHAR_SOUND_UH] = 'shoshino_eh.mp3',
  [CHAR_SOUND_OOOF] = 'shoshino_dmg1.mp3',
  [CHAR_SOUND_YAH_WAH_HOO] = { 'shoshino_jump1.mp3', 'shoshino_jump4.mp3', 'shoshino_punch1.mp3' },
  [CHAR_SOUND_OOOF2] = 'shoshino_dmg2.mp3',
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = 'shoshino_jump3.mp3',
  [CHAR_SOUND_PUNCH_WAH] = 'shoshino_punch1.mp3',
  [CHAR_SOUND_PUNCH_YAH] = 'shoshino_punch2.mp3',
  [CHAR_SOUND_WAAAOOOW] = 'shoshino_falling.mp3',
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'shoshino_bowser.mp3' },
  [CHAR_SOUND_WHOA] = 'shoshino_oh.mp3',
  [CHAR_SOUND_ON_FIRE] = 'shoshino_burn.mp3',
  [CHAR_SOUND_IMA_TIRED] = 'shoshino_sleepy.mp3',
}
VT_SHIGURE = {
  [CHAR_SOUND_ATTACKED] = { 'shigure_dmg1.mp3', 'shigure_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'shigure_ah1.mp3',            -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'shigure_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'shigure_slowclimb.mp3' }, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'shigure_atk1.mp3' },
  [CHAR_SOUND_HAHA] = { 'shigure_laugh.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'shigure_star1.mp3', 'shigure_star2.mp3', 'shigure_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'shigure_jump4.mp3' },                                               -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'shigure_slowclimb.mp3',                                                 -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'shigure_hm2.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'shigure_ls1.mp3' },                                              -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'shigure_getup1.mp3', 'shigure_getup2.mp3' },                      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'shigure_dmg3.mp3' },                                               -- Touch Fire
  [CHAR_SOUND_OOOF] = 'shigure_eh1.mp3',                                                       -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'shigure_dmg1.mp3',                                                     -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'shigure_atk2.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'shigure_jump3.mp3',    -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'shigure_atk1.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'shigure_star2.mp3', 'shigure_wontwork.mp3' }, -- Bowser Throw
  -- [CHAR_SOUND_TWIRL_BOUNCE] = {'silent.mp3'}, -- Boing
  [CHAR_SOUND_UH] = 'shigure_huh1.mp3',                                           -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'shigure_jump1.mp3' },                                     -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = 'saori_fall.mp3', -- Falling
  [CHAR_SOUND_WAH2] = { 'shigure_throw1.mp3', 'shigure_throw2.mp3' },      -- Throw Object
  [CHAR_SOUND_WHOA] = 'shigure_hm1.mp3',                                   -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'shigure_longjump.mp3' },                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'shigure_longjump.mp3' },             -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'shigure_jump1.mp3', 'shigure_jump3.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'silent.mp3'},
}
VT_NATSU = {
  [CHAR_SOUND_ATTACKED] = { 'natsu_dmg1.mp3', 'natsu_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'natsu_are1.mp3',           -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'natsu_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'natsu_slowclimb.mp3' }, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'natsu_atk3.mp3' },
  [CHAR_SOUND_HAHA] = { 'natsu_sugoi.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'natsu_star1.mp3', 'natsu_star2.mp3', 'natsu_star3.mp3', 'natsu_star4.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'natsu_jump2.mp3' },                                                              -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'natsu_grab.mp3',                                                                     -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'natsu_tired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'natsu_ls1.mp3', 'natsu_ls2.mp3' },                                            -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'natsu_getup.mp3' },                                                            -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'natsu_dmg3.mp3' },                                                              -- Touch Fire
  [CHAR_SOUND_OOOF] = 'natsu_hm1.mp3',                                                                      -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'natsu_dmg2.mp3',                                                                    -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'natsu_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'natsu_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'natsu_atk1.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'natsu_bthrow1.mp3' },             -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'natsu_sugoi.mp3' },                  -- Boing
  [CHAR_SOUND_UH] = 'natsu_dmg1.mp3',                                 -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'natsu_atk2.mp3' },                            -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  [CHAR_SOUND_WAAAOOOW] = 'natsu_falling.mp3',                        -- Falling
  [CHAR_SOUND_WAH2] = { 'natsu_bthrow1.mp3' },                        -- Throw Object
  [CHAR_SOUND_WHOA] = 'natsu_are1.mp3',                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'natsu_atk4.mp3' },                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'natsu_atk4.mp3' },              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'natsu_jump1.mp3', 'natsu_atk1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'silent.mp3'},
}
