PACK_ID = 2
TEXT_MOD_NAME = "Blue Archive Vol " .. PACK_ID

-- ================================================================
-- Custom Models
-- ================================================================
E_MODEL_MOMOI = smlua_model_util_get_id("momoi_geo")
E_MODEL_MOMOI2 = smlua_model_util_get_id("momoi2_geo")
E_MODEL_MOMOI3 = smlua_model_util_get_id("momoi3_geo")
E_MODEL_MIDORI = smlua_model_util_get_id("midori_geo")
E_MODEL_MIDORI2 = smlua_model_util_get_id("midori2_geo")
E_MODEL_MIDORI3 = smlua_model_util_get_id("midori3_geo")
E_MODEL_YUZU = smlua_model_util_get_id("yuzu_geo")
E_MODEL_YUZU2 = smlua_model_util_get_id("yuzu2_geo")
E_MODEL_YUZU3 = smlua_model_util_get_id("yuzu3_geo")
E_MODEL_ALICE = smlua_model_util_get_id("alice_geo")
E_MODEL_ALICE2 = smlua_model_util_get_id("alice2_geo")
E_MODEL_ALICE3 = smlua_model_util_get_id("alice3_geo")
E_MODEL_HIMARI = smlua_model_util_get_id("himari_geo")
E_MODEL_HIMARI2NW = smlua_model_util_get_id("himari2nw_geo")
E_MODEL_YUUKA = smlua_model_util_get_id("yuuka_geo")
E_MODEL_KOYUKI = smlua_model_util_get_id("koyuki_geo")
E_MODEL_KOYUKI2 = smlua_model_util_get_id("koyuki2_geo")
E_MODEL_HARE = smlua_model_util_get_id("hare_geo")
E_MODEL_HARE_CAMP = smlua_model_util_get_id("hare_camp_geo")
E_MODEL_NERU = smlua_model_util_get_id("neru_geo")
E_MODEL_NERU2 = smlua_model_util_get_id("neru2_geo")
E_MODEL_TOKI = smlua_model_util_get_id("tokimaidkzh_geo")
E_MODEL_TOKI_COMBAT = smlua_model_util_get_id("tokicombatkzh_geo")
E_MODEL_TOKI_BUNNY = smlua_model_util_get_id("tokibunnykzh_geo")
E_MODEL_TOKI_MAID = smlua_model_util_get_id("tokimaid2kzh_geo")
E_MODEL_TOKI_SCHOOL = smlua_model_util_get_id("tokischoolkzh_geo")
E_MODEL_HIBIKI = smlua_model_util_get_id("hibiki_geo")
E_MODEL_HIBIKI2 = smlua_model_util_get_id("hibiki_cheer_geo")
E_MODEL_KEI = smlua_model_util_get_id("kei_geo")
E_MODEL_KEI2 = smlua_model_util_get_id("kei2_geo")
-- ================================================================
-- Custom Texture Icons
-- ================================================================
TEX_MOMOI = get_texture_info("Momoi_Icon")
TEX_MOMOI2 = get_texture_info("maidmomoiicon")
TEX_MOMOI3 = get_texture_info("bunnymoiicon")
TEX_MIDORI = get_texture_info("Midori_Icon")
TEX_MIDORI2 = get_texture_info("maidmidori_icon")
TEX_MIDORI3 = get_texture_info("bmidori_icon")
TEX_YUZU = get_texture_info("Yuzu_Icon")
TEX_YUZU2 = get_texture_info("maidyuzu_icon")
TEX_YUZU3 = get_texture_info("byuzu_icon")
TEX_ALICE = get_texture_info("Portrait_Arisu")
TEX_ALICE2 = get_texture_info("maidaliceicon")
TEX_ALICE3 = get_texture_info("alice3_icon")
TEX_HIMARI = get_texture_info("Himari_Icon")
TEX_YUUKA = get_texture_info("Yuuka_Icon")
TEX_KOYUKI = get_texture_info("Koyuki_Icon")
TEX_KOYUKI2 = get_texture_info("koyuki_bun_icon")
TEX_HARE = get_texture_info("Hare_Icon")
TEX_HARECMP = get_texture_info("Hare_Camp_Icon")
TEX_NERU = get_texture_info("Neru_Icon")
TEX_NERU2 = get_texture_info("neru_bun_icon")
TEX_TOKI = get_texture_info("Toki_Icon")
TEX_TOKI2 = get_texture_info("tokicombat_icon")
TEX_TOKI3 = get_texture_info("tokibunnyicon")
TEX_TOKI4 = get_texture_info("tokischool_icon")
TEX_HIBIKI = get_texture_info("hibiki_icon")
TEX_HIBIKI2 = get_texture_info("Hibiki_Cheerleader_Icon")
TEX_KEI = get_texture_info("keiicon")
TEX_KEI2 = get_texture_info("kei2icon")
