-- BA Pack 3
-- Character Voice Tables

VT_CHERINO = {
  [CHAR_SOUND_ATTACKED] = { 'cherino_dmg1.mp3', 'cherino_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'cherino_dmg1.mp3',                    -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'cherino_dying.mp3' },
  [CHAR_SOUND_HRMM] = 'cherino_grab.mp3',                   -- Object Pick-up
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'cherino_groundPound.mp3' },
  [CHAR_SOUND_HAHA] = { 'cherino_laugh.mp3' },              -- Landing after backflip
  [CHAR_SOUND_HAHA_2] = 'cherino_laugh.mp3',                -- Landing on Water after a fall
  [CHAR_SOUND_HERE_WE_GO] = { 'cherino_star.mp3' },         -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'cherino_jump2.mp3' },            -- 2nd Jump + Dive Attack
  [CHAR_SOUND_LETS_A_GO] = { 'cherino_letsGo.mp3' },        -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'cherino_levelFail.mp3' },      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'cherino_burn.mp3' },            -- Touch Fire
  [CHAR_SOUND_OOOF] = 'cherino_hanase.mp3',                 -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'cherino_dmg2.mp3',                  -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'cherino_kick.mp3' },          -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'cherino_punch2.mp3',            -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'cherino_punch1.mp3',            -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'cherino_bowser.mp3' },  -- Bowser Throw
  [CHAR_SOUND_UH] = 'cherino_eh.mp3',                       -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'cherino_jump1.mp3' },               -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'cherino_burn.mp3',               -- Falling
  [CHAR_SOUND_WAH2] = { 'cherino_jump1.mp3' },              -- Throw Object
  [CHAR_SOUND_WHOA] = 'cherino_grab.mp3',                   -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'cherino_yahoo.mp3' },             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'cherino_yahoo.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'cherino_jump1.mp3' },       -- 1st Jump(s)
}

VT_TOMOE = {
  [CHAR_SOUND_ATTACKED] = { 'tomoe_dmg1.mp3', 'tomoe_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'tomoe_dmg1.mp3',                                   -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'tomoe_dying.mp3' },
  [CHAR_SOUND_HRMM] = 'tomoe_grab.mp3',                                  -- Object Pick-up
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'tomoe_groundPound.mp3' },
  [CHAR_SOUND_HAHA] = { 'tomoe_laugh.mp3' },                             -- Landing after backflip
  [CHAR_SOUND_HAHA_2] = 'tomoe_laugh.mp3',                               -- Landing on Water after a fall
  [CHAR_SOUND_HERE_WE_GO] = { 'tomoe_star.mp3', 'tomoe_star2.mp3' },     -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'tomoe_jump2.mp3' },                           -- 2nd Jump + Dive Attack
  [CHAR_SOUND_LETS_A_GO] = { 'tomoe_letsGo.mp3' },                       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'tomoe_levelFail.mp3' },                     -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'tomoe_dmg2.mp3' },                           -- Touch Fire
  [CHAR_SOUND_OOOF] = 'tomoe_ara.mp3',                                   -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'tomoe_dmg2.mp3',                                 -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'tomoe_yahoo.mp3' },                        -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'tomoe_punch2.mp3',                           -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'tomoe_punch1.mp3',                           -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'tomoe_bowser.mp3' },                 -- Bowser Throw
  [CHAR_SOUND_UH] = 'tomoe_ara.mp3',                                     -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'tomoe_jump1.mp3' },                              -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'tomoe_ara.mp3',                               -- Falling
  [CHAR_SOUND_WAH2] = { 'tomoe_jump1.mp3' },                             -- Throw Object
  [CHAR_SOUND_WHOA] = 'tomoe_grab.mp3',                                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'tomoe_yahoo.mp3' },                            -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'tomoe_yahoo.mp3' },                -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'tomoe_jump1.mp3', 'tomoe_jump1_1.mp3' }, -- 1st Jump(s)
}

VT_MARINA = {
  [CHAR_SOUND_ATTACKED] = { 'marina_dmg1.mp3', 'marina_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'marina_dmg1.mp3',                                    -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'marina_dying.mp3' },
  [CHAR_SOUND_HRMM] = 'marina_oh.mp3',                                     -- Object Pick-up
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'marina_groundPound.mp3' },
  [CHAR_SOUND_HAHA] = { 'marina_laugh.mp3' },                              -- Landing after backflip
  [CHAR_SOUND_HAHA_2] = 'marina_laugh.mp3',                                -- Landing on Water after a fall
  [CHAR_SOUND_HERE_WE_GO] = { 'marina_star.mp3' },                         -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'marina_jump2.mp3' },                            -- 2nd Jump + Dive Attack
  [CHAR_SOUND_LETS_A_GO] = { 'marina_letsGo.mp3' },                        -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'marina_levelFail.mp3' },                      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'marina_dmg2.mp3' },                            -- Touch Fire
  [CHAR_SOUND_OOOF] = 'marina_oh.mp3',                                     -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'marina_dmg2.mp3',                                  -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'marina_kick.mp3' },                          -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'marina_punch2.mp3',                            -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'marina_punch1.mp3',                            -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'marina_bowser.mp3' },                  -- Bowser Throw
  [CHAR_SOUND_UH] = 'marina_oh.mp3',                                       -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'marina_jump1.mp3' },                               -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'marina_falling.mp3',                            -- Falling
  [CHAR_SOUND_WAH2] = { 'marina_jump1.mp3' },                              -- Throw Object
  [CHAR_SOUND_WHOA] = 'marina_oh.mp3',                                     -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'marina_yahoo.mp3' },                             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'marina_yahoo.mp3' },                 -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'marina_jump1.mp3', 'marina_jump1_1.mp3' }, -- 1st Jump(s)
}

VT_KISAKI = {
  [CHAR_SOUND_ATTACKED] = { 'sfx_smrpg_hit1.mp3' },
  [CHAR_SOUND_DOH] = 'kisaki_oh.mp3',               -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'kisaki_dead1.mp3' },
  [CHAR_SOUND_HAHA] = { 'kisaki_nanoja.mp3' },      -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'kisaki_star1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'kisaki_atk5.mp3' },      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',     -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'kisaki_rest.mp3',
  --[CHAR_SOUND_GROUND_POUND_WAH] = {'nagisa_atk4.mp3'},
  [CHAR_SOUND_LETS_A_GO] = { 'kisaki_ls1.mp3' },                       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'kisaki_levelexit.mp3' },                  -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                      -- Touch Fire
  [CHAR_SOUND_OOOF] = 'kisaki_hm2.mp3',                                -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'sfx_smrpg_hit1.mp3',                           -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'kisaki_throw.mp3' },                     -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'kisaki_atk2.mp3',                          -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'kisaki_atk3.mp3',                          -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'kisaki_throw.mp3' },               -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                -- Boing
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                             -- Drop off of ledge + Fall off Ledge
  --[CHAR_SOUND_UH2] = {'nagisa_atk1.mp3'}, -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'kisaki_what.mp3',                           -- Falling
  [CHAR_SOUND_WAH2] = { 'kisaki_throw.mp3' },                          -- Throw Object
  [CHAR_SOUND_WHOA] = 'kisaki_oh.mp3',                                 -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'kisaki_atk4.mp3' },                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'kisaki_atk4.mp3' },              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'kisaki_atk1.mp3', 'kisaki_atk3.mp3' }, -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'kisaki_hm1.mp3' },
}

VT_HIFUMI = {
  [CHAR_SOUND_ATTACKED] = { 'hifumi_dmg2.mp3', 'hifumi_dmg4.mp3' },
  [CHAR_SOUND_DOH] = 'hifumi_eh1.mp3',              -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'hifumi_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'hifumi_slowclimb.mp3' },   -- Slow Get up from ledge
  --[CHAR_SOUND_HAHA] = {'kisaki_nanoja.mp3'}, -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'hifumi_star1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'hifumi_atk4.mp3' },      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',     -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'hifumi_tired.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'hifumi_atk2.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'hifumi_ls.mp3' },                                           -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'hifumi_levelexit.mp3' },                                     -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'hifumi_dmg3.mp3' },                                           -- Touch Fire
  [CHAR_SOUND_OOOF] = 'hifumi_are1.mp3',                                                  -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'hifumi_dmg1.mp3',                                                 -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'hifumi_atk2.mp3' },                                         -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'hifumi_atk4.mp3',                                             -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'hifumi_atk3.mp3',                                             -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'hifumi_longjump.mp3' },                               -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                                   -- Boing
  [CHAR_SOUND_UH] = 'hifumi_wah1.mp3',                                                    -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'hifumi_atk3.mp3' },                                               -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'hifumi_fall.mp3',                                              -- Falling
  [CHAR_SOUND_WAH2] = { 'hifumi_atk1.mp3' },                                              -- Throw Object
  [CHAR_SOUND_WHOA] = 'hifumi_wah2.mp3',                                                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'hifumi_longjump.mp3' },                                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'hifumi_atk2.mp3' },                                 -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'hifumi_atk3.mp3', 'hifumi_atk6.mp3', 'hifumi_atk5.mp3' }, -- 1st Jump(s)
}

VT_KOHARU = {
  [CHAR_SOUND_ATTACKED] = { 'koharu_dmg4.mp3', 'koharu_dmg6.mp3' },
  [CHAR_SOUND_DOH] = 'koharu_eh1.mp3',                                  -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'koharu_dead1.mp3', 'koharu_dead2.mp3' },
  [CHAR_SOUND_HAHA] = { 'koharu_laugh.mp3' },                           -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'koharu_star1.mp3', 'koharu_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'koharu_atk4.mp3' },                          -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                         -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'koharu_tired.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'koharu_atk5.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'koharu_ls1.mp3' },                              -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'koharu_deathpenalty.mp3' },                      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'koharu_dmg3.mp3' },                               -- Touch Fire
  [CHAR_SOUND_OOOF] = 'koharu_are1.mp3',                                      -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'koharu_dmg1.mp3',                                     -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'koharu_atk5.mp3' },                             -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'koharu_atk3.mp3',                                 -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'koharu_atk1.mp3',                                 -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'koharu_bthrow.mp3' },                     -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                       -- Boing
  [CHAR_SOUND_UH] = 'koharu_are1.mp3',                                        -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'koharu_atk1.mp3' },                                   -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'koharu_fall.mp3',                                  -- Falling
  [CHAR_SOUND_WAH2] = { 'koharu_echidame.mp3' },                              -- Throw Object
  [CHAR_SOUND_WHOA] = 'koharu_eh1.mp3',                                       -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'koharu_jump2.mp3' },                                -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'koharu_jump1.mp3', 'koharu_atk6.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'koharu_atk1.mp3', 'koharu_atk3.mp3' },        -- 1st Jump(s)
}

VT_HANAKO = {
  [CHAR_SOUND_ATTACKED] = { 'hanako_dmg1.mp3', 'hanako_dmg2.mp3', 'hanako_dmg5.mp3' },
  [CHAR_SOUND_DOH] = 'hanako_ah.mp3',                                                       -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'hanako_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'hanako_slowclimb.mp3' },                                           -- Slow Get up from ledge
  [CHAR_SOUND_HAHA] = { 'hanako_laugh.mp3' },                                               -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'hanako_star1.mp3', 'hanako_star2.mp3', 'hanako_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'hanako_atk2.mp3' },                                              -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                             -- Object Pick-up
  --[CHAR_SOUND_IMA_TIRED] = 'kisaki_rest.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'hanako_atk7.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'hanako_ls1.mp3' },                       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'hanako_begentle.mp3' },                   -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'hanako_dmg6.mp3' },                        -- Touch Fire
  [CHAR_SOUND_OOOF] = 'hanako_ara1.mp3',                               -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'hanako_ara3.mp3',                              -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'hanako_atk3.mp3' },                      -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'hanako_atk4.mp3',                          -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'hanako_atk1.mp3',                          -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'hanako_bthrow.mp3' },              -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                -- Boing
  [CHAR_SOUND_UH] = 'hanako_eh.mp3',                                   -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'hanako_atk1.mp3' },                            -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'hanako_gasp.mp3',                           -- Falling
  [CHAR_SOUND_WAH2] = { 'hanako_atk5.mp3' },                           -- Throw Object
  [CHAR_SOUND_WHOA] = 'hanako_ara2.mp3',                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'hanako_atk6.mp3' },                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'hanako_atk5.mp3' },              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'hanako_atk1.mp3', 'hanako_atk8.mp3' }, -- 1st Jump(s)
}

VT_REIJO = {
  [CHAR_SOUND_ATTACKED] = { 'reijo_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'reijo_dmg1.mp3',                                -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'reijo_dead1.mp3' },
  [CHAR_SOUND_HAHA] = { 'reijo_hisatsu.mp3' },                        -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'reijo_star1.mp3', 'reijo_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'reijo_atk10.mp3' },                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                       -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'reijo_rest.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'reijo_atk5.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'reijo_ls1.mp3' },                                        -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'reijo_getup.mp3' },                                       -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                                      -- Touch Fire
  [CHAR_SOUND_OOOF] = 'reijo_eh.mp3',                                                  -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'reijo_dmg3.mp3',                                               -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'reijo_atk11.mp3' },                                      -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'reijo_atk7.mp3',                                           -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'reijo_atk6.mp3',                                           -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'reijo_bthrow1.mp3', 'reijo_bthrow2.mp3' },         -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                                -- Boing
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                                             -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'reijo_atk1.mp3' },                                             -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                                     -- Falling
  [CHAR_SOUND_WAH2] = { 'reijo_takethis.mp3', 'reijo_howsthis.mp3' },                  -- Throw Object
  [CHAR_SOUND_WHOA] = 'reijo_eh.mp3',                                                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'reijo_longjump.mp3' },                                       -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'reijo_atk11.mp3' },                              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'reijo_atk2.mp3', 'reijo_atk4.mp3', 'reijo_atk8.mp3' }, -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'reijo_yawn.mp3' },
}

VT_AIRI = {
  [CHAR_SOUND_ATTACKED] = { 'airi_ehh.mp3' },
  [CHAR_SOUND_DOH] = 'airi_eh1.mp3',                                 -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'airi_defeat1.mp3' },
  [CHAR_SOUND_HAHA] = { 'airi_laugh1.mp3' },                         -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'airi_star1.mp3', 'airi_star2.mp3' },  -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'airi_atk3.mp3' },                         -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'airi_hm1.mp3',                                -- Object Pick-up
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'airi_atk1.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'airi_ls1.mp3' },                       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'airi_levelexit.mp3', 'airi_pout.mp3' }, -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                    -- Touch Fire
  [CHAR_SOUND_OOOF] = 'airi_ah1.mp3',                                -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'airi_dmg1.mp3',                              -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'airi_atk3.mp3' },                      -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'airi_atk6.mp3',                          -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'airi_atk5.mp3',                          -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'airi_bthrow.mp3' },             -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },              -- Boing
  [CHAR_SOUND_UH] = 'airi_eh2.mp3',                                  -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'airi_atk4.mp3' },                            -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'airi_fall.mp3',                           -- Falling
  [CHAR_SOUND_WAH2] = { 'airi_throw1.mp3' },                         -- Throw Object
  [CHAR_SOUND_WHOA] = 'airi_hm1.mp3',                                -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'airi_atk2.mp3' },                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'airi_atk2.mp3' },              -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'airi_atk5.mp3', 'airi_atk1.mp3' },   -- 1st Jump(s)
}

VT_YOSHIMI = {
  [CHAR_SOUND_ATTACKED] = { 'yosh_dmg3.mp3', 'yosh_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'yosh_ah1.mp3',                                                  -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'sfx_smb3_down.mp3' },
  [CHAR_SOUND_HAHA] = { 'yosh_heh.mp3' },                                             -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'yosh_star1.mp3', 'yosh_star2.mp3', 'yosh_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'yosh_atk2.mp3' },                                          -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'yosh_hm2.mp3',                                                 -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'yosh_tired.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'yosh_atk6.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'yosh_ls1.mp3' },                                      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'yosh_levelexit1.mp3', 'yosh_levelexit2.mp3' },         -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                                   -- Touch Fire
  [CHAR_SOUND_OOOF] = 'yosh_grabbed.mp3',                                           -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'yosh_dmg3.mp3',                                             -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'yosh_atk3.mp3' },                                     -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'yosh_atk5.mp3',                                         -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'yosh_atk7.mp3',                                         -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'yosh_bthrow1.mp3' },                            -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                             -- Boing
  [CHAR_SOUND_UH] = 'yosh_hm2.mp3',                                                 -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'yosh_atk4.mp3' },                                           -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'yosh_fall.mp3',                                          -- Falling
  [CHAR_SOUND_WAH2] = { 'yosh_throw1.mp3' },                                        -- Throw Object
  [CHAR_SOUND_WHOA] = 'yosh_are1.mp3',                                              -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'yosh_atk3.mp3' },                                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'yosh_atk3.mp3' },                             -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'yosh_atk4.mp3', 'yosh_atk5.mp3', 'yosh_atk7.mp3' }, -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'yosh_yawn.mp3' },
}

VT_HASUMI = {
  [CHAR_SOUND_ATTACKED] = { 'hasumi_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'hasumi_are1.mp3',                                 -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'hasumi_dying.mp3' },
  [CHAR_SOUND_HAHA] = { 'hasumi_laugh.mp3' },                           -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'hasumi_star.mp3', 'hasumi_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'hasumi_jump2_1.mp3' },                       -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                         -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'hasumi_hm.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'hasumi_groundPound.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'hasumi_letsGo.mp3' },                       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'hasumi_levelFail.mp3' },                     -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'hasumi_burn.mp3' },                           -- Touch Fire
  [CHAR_SOUND_OOOF] = 'hasumi_ah1.mp3',                                   -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'hasumi_dmg1.mp3',                                 -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'hasumi_punch2.mp3' },                       -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'hasumi_kick.mp3',                             -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'hasumi_kick.mp3',                             -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'hasumi_bowser.mp3' },                 -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                   -- Boing
  [CHAR_SOUND_UH] = 'hasumi_ah1.mp3',                                     -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'hasumi_jump1_2.mp3' },                            -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                        -- Falling
  [CHAR_SOUND_WAH2] = { 'hasumi_punch2.mp3', 'hasumi_bowser.mp3' },       -- Throw Object
  [CHAR_SOUND_WHOA] = 'hasumi_are1.mp3',                                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'hasumi_yahoo.mp3' },                            -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'hasumi_yahoo.mp3' },                -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'hasumi_kick.mp3', 'hasumi_jump1_2.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'hasumi_yawn.mp3'},
}

VT_SHIZUKO = {
  [CHAR_SOUND_ATTACKED] = { 'shizuko_dmg2.mp3', 'shizuko_wah.mp3' },
  [CHAR_SOUND_DOH] = 'shizuko_eh.mp3',                                   -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'shizuko_dying.mp3' },
  [CHAR_SOUND_HAHA] = { 'shizuko_waai.mp3' },                            -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'shizuko_star.mp3', 'shizuko_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'shizuko_jump2_1.mp3' },                       -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'shizuko_grab.mp3',                                -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'shizuko_sleep.mp3',
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'shizuko_atk6.mp3'},
  [CHAR_SOUND_LETS_A_GO] = { 'shizuko_letsGo.mp3' },                       -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'shizuko_levelFail.mp3' },                     -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'shizuko_burn.mp3' },                           -- Touch Fire
  [CHAR_SOUND_OOOF] = 'shizuko_eh.mp3',                                    -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'shizuko_dmg1.mp3',                                 -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'shizuko_kick.mp3' },                         -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'shizuko_punch2.mp3',                           -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'shizuko_atk1.mp3',                             -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'shizuko_bowser.mp3' },                 -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                    -- Boing
  [CHAR_SOUND_UH] = 'shizuko_eh.mp3',                                      -- Drop off of ledge + Fall off Ledge
  -- [CHAR_SOUND_UH2] = {'shizuko_atk4.mp3'}, -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'shizuko_burn.mp3',                              -- Falling
  [CHAR_SOUND_WAH2] = { 'shizuko_throw1.mp3' },                            -- Throw Object
  [CHAR_SOUND_WHOA] = 'shizuko_wah.mp3',                                   -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'shizuko_yahoo.mp3' },                            -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'shizuko_yahoo.mp3' },                -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'shizuko_punch1.mp3', 'shizuko_atk1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'shizuko_yawn.mp3'},
}

VT_SERIKA = {
  [CHAR_SOUND_ATTACKED] = { 'serika_dmg1.mp3', 'serika_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'serika_eh.mp3',                                   -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'serika_dead1.mp3' },
  [CHAR_SOUND_HAHA] = { 'serika_nyan.mp3' },                            -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'serika_star1.mp3', 'serika_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'serika_atk5.mp3' },                          -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                         -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'serika_tired.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'serika_atk5.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'serika_ls1.mp3' },                                          -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'serika_getup.mp3' },                                         -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'serika_dmg3.mp3' },                                           -- Touch Fire
  [CHAR_SOUND_OOOF] = 'serika_cho.mp3',                                                   -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'serika_dmg1.mp3',                                                 -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'serika_atk6.mp3' },                                         -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'serika_atk1.mp3',                                             -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'serika_atk8.mp3',                                             -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'serika_bthrow1.mp3', 'serika_bthrow2.mp3' },          -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                                   -- Boing
  [CHAR_SOUND_UH] = 'serika_eh.mp3',                                                      -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'serika_atk8.mp3' },                                               -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'serika_fall1.mp3',                                             -- Falling
  [CHAR_SOUND_WAH2] = { 'serika_atk6.mp3' },                                              -- Throw Object
  [CHAR_SOUND_WHOA] = 'serika_eh.mp3',                                                    -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'serika_longjump.mp3' },                                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'serika_atk2.mp3', 'serika_longjump2.mp3' },         -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'serika_atk7.mp3', 'serika_atk8.mp3', 'serika_atk1.mp3' }, -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'serika_yawn.mp3' },
}

VT_AKARI = {
  [CHAR_SOUND_ATTACKED] = { 'akari_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'akari_ara.mp3',              -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'akari_dead1.mp3' },
  [CHAR_SOUND_HAHA] = { 'akari_giggle.mp3' },      -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'akari_star1.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'akari_jump1.mp3' },     -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',    -- Object Pick-up
  --[CHAR_SOUND_IMA_TIRED] = 'serika_tired.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'akari_atk1.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'akari_ls1.mp3' },                                        -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'akari_levelexit.mp3' },                                   -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'akari_burn.mp3' },                                         -- Touch Fire
  [CHAR_SOUND_OOOF] = 'akari_ara.mp3',                                                 -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'akari_dmg1.mp3',                                               -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'akari_kick.mp3' },                                       -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'akari_atk2.mp3',                                           -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'akari_atk1.mp3',                                           -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'akari_throw1.mp3' },                               -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                                -- Boing
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                                             -- Drop off of ledge + Fall off Ledge
  --[CHAR_SOUND_UH2] = {'serika_atk8.mp3'}, -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                                     -- Falling
  [CHAR_SOUND_WAH2] = { 'akari_throw1.mp3' },                                          -- Throw Object
  [CHAR_SOUND_WHOA] = 'akari_ara.mp3',                                                 -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'akari_longjump.mp3' },                                       -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'akari_kick.mp3', 'akari_longjump.mp3' },         -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'akari_atk3.mp3', 'akari_atk4.mp3', 'akari_atk1.mp3' }, -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'akari_yawn.mp3' },
}

VT_AYANE = {
  [CHAR_SOUND_ATTACKED] = { 'ayane_dmg2.mp3', 'ayane_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'ayane_eh.mp3',              -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'ayane_dying.mp3' },
  [CHAR_SOUND_HAHA] = { 'ayane_laugh.mp3' },      -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'ayane_star.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'ayane_jump2.mp3' },    -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'ayane_grab.mp3',           -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'ayane_sleep.mp3',
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'ayane_atk6.mp3'},
  [CHAR_SOUND_LETS_A_GO] = { 'ayane_letsGo.mp3' },        -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'ayane_levelFail.mp3' },      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'ayane_burn.mp3' },            -- Touch Fire
  [CHAR_SOUND_OOOF] = 'ayane_eh.mp3',                     -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'ayane_dmg1.mp3',                  -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'ayane_kick.mp3' },          -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'ayane_punch2.mp3',            -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'ayane_punch1.mp3',            -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'ayane_bowser.mp3' },  -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },   -- Boing
  [CHAR_SOUND_UH] = 'ayane_eh.mp3',                       -- Drop off of ledge + Fall off Ledge
  -- [CHAR_SOUND_UH2] = {'ayane_atk4.mp3'}, -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'ayane_falling.mp3',            -- Falling
  -- [CHAR_SOUND_WAH2] = {'ayane_throw1.mp3'},-- Throw Object
  [CHAR_SOUND_WHOA] = 'ayane_grab.mp3',                   -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'ayane_yahoo.mp3' },             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'ayane_yahoo.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'ayane_jump1.mp3' },       -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'ayane_yawn.mp3'},
}

VT_NONOMI = {
  [CHAR_SOUND_ATTACKED] = { 'nonomi_dmg2.mp3', 'nonomi_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'nonomi_dmg2.mp3',            -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'nonomi_dying.mp3' },
  [CHAR_SOUND_HAHA] = { 'nonomi_laugh.mp3' },      -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'nonomi_star.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'nonomi_jump2.mp3' },    -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'nonomi_grab.mp3',           -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'nonomi_sleepy.mp3',
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'nonomi_atk6.mp3'},
  [CHAR_SOUND_LETS_A_GO] = { 'nonomi_letsGo.mp3' },        -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'nonomi_levelFail.mp3' },      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'nonomi_burn.mp3' },            -- Touch Fire
  [CHAR_SOUND_OOOF] = 'nonomi_ara.mp3',                    -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'nonomi_dmg1.mp3',                  -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'nonomi_kick.mp3' },          -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'nonomi_punch2.mp3',            -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'nonomi_punch1.mp3',            -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'nonomi_bowser.mp3' },  -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },    -- Boing
  [CHAR_SOUND_UH] = 'nonomi_ara.mp3',                      -- Drop off of ledge + Fall off Ledge
  -- [CHAR_SOUND_UH2] = {'nonomi_atk4.mp3'}, -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'nonomi_falling.mp3',            -- Falling
  -- [CHAR_SOUND_WAH2] = {'nonomi_throw1.mp3'},-- Throw Object
  [CHAR_SOUND_WHOA] = 'nonomi_grab.mp3',                   -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'nonomi_yahoo.mp3' },             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'nonomi_yahoo.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'nonomi_jump1.mp3' },       -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'nonomi_yawn.mp3'},
}
VT_NOA = {
  [CHAR_SOUND_ATTACKED] = { 'noa_dmg2.mp3', 'noa_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'noa_ara.mp3',             -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'noa_dying.mp3' },
  [CHAR_SOUND_HAHA] = { 'noa_laugh.mp3' },      -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'noa_star.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'noa_jump2.mp3' },    -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'noa_grab.mp3',           -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'noa_sleepy.mp3',
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'noa_atk6.mp3'},
  [CHAR_SOUND_LETS_A_GO] = { 'noa_letsGo.mp3' },                                      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'noa_levelFail.mp3' },                                    -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'noa_falling.mp3' },                                       -- Touch Fire
  [CHAR_SOUND_OOOF] = 'noa_ara.mp3',                                                  -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'noa_dmg1.mp3',                                                -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'noa_kick.mp3' },                                        -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'noa_punch2.mp3',                                          -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'noa_punch1.mp3',                                          -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'noa_bowser.mp3' },                                -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                               -- Boing
  [CHAR_SOUND_UH] = 'noa_ara.mp3',                                                    -- Drop off of ledge + Fall off Ledge
  -- [CHAR_SOUND_UH2] = {'noa_atk4.mp3'}, -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'noa_falling.mp3',                                          -- Falling
  -- [CHAR_SOUND_WAH2] = {'noa_throw1.mp3'},-- Throw Object
  [CHAR_SOUND_WHOA] = 'noa_grab.mp3',                                                 -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'noa_kick.mp3' },                                            -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'noa_yahoo.mp3' },                               -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'noa_jump1.mp3', 'noa_punch2.mp3', 'noa_punch1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'noa_yawn.mp3'},
}

VT_SEIA = {
  [CHAR_SOUND_ATTACKED] = { 'seia_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'seia_dmg2.mp3',                                                 -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'seia_dead1.mp3' },
  [CHAR_SOUND_HAHA] = { 'seia_subarashi.mp3' },                                       -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'seia_star1.mp3', 'seia_star2.mp3', 'seia_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'seia_atk2.mp3' },                                          -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                       -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'seia_hm2.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'seia_atk2.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'seia_ls1.mp3' },                                      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'seia_levelexit.mp3' },                                 -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                                   -- Touch Fire
  [CHAR_SOUND_OOOF] = 'seia_hm1.mp3',                                               -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'seia_dmg2.mp3',                                             -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'seia_atk1.mp3' },                                     -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'seia_atk5.mp3',                                         -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'seia_atk6.mp3',                                         -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'seia_useless.mp3' },                            -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                             -- Boing
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                                          -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'seia_atk2.mp3' },                                           -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                                  -- Falling
  [CHAR_SOUND_WAH2] = { 'sfx_ssb64_itemthrow.mp3', 'seia_kys.mp3' },                -- Throw Object
  [CHAR_SOUND_WHOA] = 'seia_hm1.mp3',                                               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'seia_atk3.mp3' },                                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'seia_atk3.mp3', 'seia_atk1.mp3' },                             -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'seia_atk1.mp3', 'seia_atk5.mp3', 'seia_atk7.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'serika_yawn.mp3'},
}

VT_NERD = {
  [CHAR_SOUND_ATTACKED] = { 'sfx_smrpg_hit1.mp3', 'sfx_smrpg_shell.mp3', 'sfx_smw_bossstun.mp3' },
  [CHAR_SOUND_DOH] = 'sfx_ml_bump.mp3',                                              -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'sfx_smb3_down.mp3' },
  [CHAR_SOUND_HERE_WE_GO] = { 'sfx_alttp_item.mp3', 'sfx_smrpg_specialflower.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_LETS_A_GO] = { 'sfx_smb3_levelselect.mp3' },                           -- Level Select
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                      -- Object Pick-up
  [CHAR_SOUND_HOOHOO] = { 'sfx_smw_jump.mp3' },                                      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                                    -- Touch Fire
  [CHAR_SOUND_OOOF] = 'sfx_pm64_what.mp3',                                           -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'sfx_smrpg_drop.mp3',                                         -- Landing After a Bonk + Thrown out of level + Also Bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'sfx_ssb64_atk3.mp3' },                                 -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'sfx_ssb64_atk2.mp3',                                     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'sfx_ssb64_atk1.mp3',                                     -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'sfx_smrpg_fireball.mp3' },                       -- Bowser Throw
  [CHAR_SOUND_WAH2] = { 'sfx_ssb64_itemthrow.mp3' },                                 -- Throw Object
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                                           -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                                   -- Falling
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                              -- Boing
  [CHAR_SOUND_WHOA] = 'sfx_ssb64_ledge.mp3',                                         -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'sfx_ssb64_superjump.mp3' },                                -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'sfx_ssb64_superjump.mp3' },                    -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'sfx_smw_jump.mp3' },                                 -- 1st Jump(s)
}

VT_RIO = {
  [CHAR_SOUND_ATTACKED] = { 'sfx_smrpg_hit1.mp3', 'sfx_smrpg_shell.mp3', 'sfx_smw_bossstun.mp3' },
  [CHAR_SOUND_DOH] = 'sfx_ml_bump.mp3',                                          -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'sfx_smb3_down.mp3' },
  [CHAR_SOUND_HERE_WE_GO] = { 'rio_star1.mp3' },                                 -- Star Get + Obtaining Power-up
  [CHAR_SOUND_LETS_A_GO] = { 'rio_ls1.mp3' },                                    -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'rio_levelexit.mp3' },                               -- Getting up after thrown out of level
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                  -- Object Pick-up
  [CHAR_SOUND_HOOHOO] = { 'rio_atk5.mp3' },                                      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                                -- Touch Fire
  [CHAR_SOUND_OOOF] = 'rio_what.mp3',                                            -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'sfx_smrpg_drop.mp3',                                     -- Landing After a Bonk + Thrown out of level + Also Bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'sfx_ssb64_atk3.mp3' },                             -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'rio_atk4.mp3',                                       -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'rio_atk1.mp3',                                       -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'rio_bthrow1.mp3' },                          -- Bowser Throw
  [CHAR_SOUND_WAH2] = { 'rio_denied.mp3' },                                      -- Throw Object
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                                       -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                               -- Falling
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                          -- Boing
  [CHAR_SOUND_WHOA] = 'sfx_ssb64_ledge.mp3',                                     -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'sfx_ssb64_superjump.mp3' },                            -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'sfx_ssb64_superjump.mp3' },                -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'rio_atk1.mp3', 'rio_atk3.mp3', 'rio_atk6.mp3' }, -- 1st Jump(s)
}

VT_IROHA = {
  [CHAR_SOUND_ATTACKED] = { 'sfx_smrpg_hit1.mp3', 'sfx_smrpg_shell.mp3', 'sfx_smw_bossstun.mp3' },
  [CHAR_SOUND_DOH] = 'iroha_eh.mp3',                                                     -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'iroha_dead1.mp3' },
  [CHAR_SOUND_HAHA] = { 'iroha_laugh.mp3' },                                             -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'iroha_star1.mp3', 'iroha_star2.mp3', 'iroha_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_LETS_A_GO] = { 'iroha_ls1.mp3' },                                          -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'iroha_levelexit1.mp3' },                                    -- Getting up after thrown out of level
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                          -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'iroha_sigh.mp3',
  [CHAR_SOUND_HOOHOO] = { 'iroha_atk6.mp3' },                                            -- 2nd Jump + Dive Attack
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                                        -- Touch Fire
  [CHAR_SOUND_OOOF] = 'sfx_pm64_what.mp3',                                               -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'sfx_smrpg_drop.mp3',                                             -- Landing After a Bonk + Thrown out of level + Also Bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'iroha_atk5.mp3' },                                         -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'iroha_atk3.mp3',                                             -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'iroha_atk8.mp3',                                             -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'iroha_attack.mp3' },                                 -- Bowser Throw
  [CHAR_SOUND_WAH2] = { 'iroha_throw1.mp3' },                                            -- Throw Object
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                                               -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'iroha_annoying.mp3',                                          -- Falling
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                                  -- Boing
  [CHAR_SOUND_WHOA] = 'sfx_ssb64_ledge.mp3',                                             -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'iroha_atk5.mp3' },                                             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'iroha_atk5.mp3' },                                 -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'iroha_atk8.mp3', 'iroha_atk7.mp3', 'iroha_atk1.mp3' },   -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'iroha_yawn.mp3' },
}

VT_SUZUMI = {
  [CHAR_SOUND_ATTACKED] = { 'suzumi_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'suzumi_dmg2.mp3', -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'suzumi_dead1.mp3', 'suzumi_dead2.mp3' },
  --[CHAR_SOUND_HAHA] = {'seia_subarashi.mp3'}, -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'suzumi_star1.mp3', 'suzumi_star2.mp3', 'suzumi_star3.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'suzumi_atk2.mp3' },                                              -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                             -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'suzumi_humu.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'suzumi_atk1.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'suzumi_ls1.mp3' },           -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'suzumi_dead3.mp3' },          -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },          -- Touch Fire
  --[CHAR_SOUND_OOOF] = 'seia_hm1.mp3', -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'suzumi_dmg2.mp3',                  -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'suzumi_atk5.mp3' },          -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'suzumi_atk2.mp3',              -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'suzumi_atk3.mp3',              -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'suzumi_bthrow1.mp3' }, -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },    -- Boing
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                 -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'suzumi_atk1.mp3' },                -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',         -- Falling
  [CHAR_SOUND_WAH2] = { 'suzumi_bthrow2.mp3' },            -- Throw Object
  [CHAR_SOUND_WHOA] = 'sfx_ssb64_ledge.mp3',               -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'suzumi_atk5.mp3' },              -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'suzumi_atk5.mp3' },  -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'suzumi_atk1.mp3' },        -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'serika_yawn.mp3'},
}

VT_SUMIRE = {
  [CHAR_SOUND_ATTACKED] = { 'sumire_dmg2.mp3', 'sumire_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'sumire_are.mp3',                                  -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'sumire_dead1.mp3', 'sumire_dead2.mp3' },
  [CHAR_SOUND_HAHA] = { 'sumire_laugh.mp3' },                           -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'sumire_star1.mp3', 'sumire_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'sumire_jump2.mp3' },                         -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sumire_grab.mp3',                                -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'sumire_sleepy.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'sumire_yahoo2.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'sumire_letsGo.mp3' },                                           -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'sumire_levelFail.mp3' },                                         -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'sumire_dmg2.mp3' },                                               -- Touch Fire
  [CHAR_SOUND_OOOF] = 'sumire_are.mp3',                                                       -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'sumire_dmg1.mp3',                                                     -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'sumire_kick.mp3' },                                             -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'sumire_punch2.mp3',                                               -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'sumire_punch1.mp3',                                               -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'sumire_bowser.mp3' },                                     -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                                       -- Boing
  [CHAR_SOUND_UH] = 'sumire_are.mp3',                                                         -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'sumire_punch1.mp3' },                                                 -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'sumire_falling.mp3',                                               -- Falling
  -- [CHAR_SOUND_WAH2] = {'sumire_throw1.mp3'},-- Throw Object
  [CHAR_SOUND_WHOA] = 'sumire_grab.mp3',                                                      -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'sumire_yahoo1.mp3', 'sumire_yahoo2.mp3' },                          -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'sumire_jump3.mp3' },                                    -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'sumire_jump4.mp3', 'sumire_punch1.mp3', 'sumire_jump1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'sumire_yawn.mp3'},
}

VT_MEGU = {
  [CHAR_SOUND_ATTACKED] = { 'megu_dmg1.mp3', 'megu_dmg3.mp3', 'megu_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'megu_bonk2.mp3',                              -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'megu_defeat.mp3' },
  [CHAR_SOUND_HAHA] = { 'megu_laugh1.mp3' },                        -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'megu_star1.mp3', 'megu_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_LETS_A_GO] = { 'megu_ls1.mp3' },                      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'megu_levelexit.mp3' },                 -- Getting up after thrown out of level
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                     -- Object Pick-up
  [CHAR_SOUND_HOOHOO] = { 'megu_atk2.mp3' },                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                   -- Touch Fire
  [CHAR_SOUND_OOOF] = 'megu_bonk.mp3',                             -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'megu_dmg1.mp3',                             -- Landing After a Bonk + Thrown out of level + Also Bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'megu_atk4.mp3' },                     -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'megu_atk2.mp3',                         -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'megu_atk3.mp3',                         -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'megu_bthrow.mp3' },             -- Bowser Throw
  [CHAR_SOUND_WAH2] = { 'megu_throw.mp3' },                         -- Throw Object
  [CHAR_SOUND_UH] = 'megu_drop.mp3',                                -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'megu_fall.mp3',                          -- Falling
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },             -- Boing
  [CHAR_SOUND_WHOA] = 'megu_ledgegrab.mp3',                         -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'megu_longjump.mp3' },                     -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'megu_laugh2.mp3' },           -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'megu_atk1.mp3' },                   -- 1st Jump(s)
}

VT_IORI = {
  [CHAR_SOUND_ATTACKED] = { 'iori_dmg1.mp3', 'iori_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'iori_bonk.mp3',                               -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'iori_defeat1.mp3', 'iori_defeat2.mp3' },
  [CHAR_SOUND_HERE_WE_GO] = { 'iori_star1.mp3', 'iori_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_LETS_A_GO] = { 'iori_ls1.mp3' },                      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'iori_levelexit.mp3' },
  [CHAR_SOUND_HRMM] = 'iori_grab.mp3',                              -- Object Pick-up
  [CHAR_SOUND_HOOHOO] = { 'iori_atk2.mp3' },                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_ON_FIRE] = { 'iori_dmg2.mp3' },                       -- Touch Fire
  [CHAR_SOUND_OOOF] = 'iori_grabbed.mp3',                           -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'iori_dmg3.mp3',                             -- Landing After a Bonk + Thrown out of level + Also Bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'iori_atk3.mp3' },                     -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'iori_atk2.mp3',                         -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'iori_atk1.mp3',                         -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'iori_bthrow1.mp3' },            -- Bowser Throw
  [CHAR_SOUND_WAH2] = { 'iori_throw1.mp3' },                        -- Throw Object
  [CHAR_SOUND_UH] = 'iori_bonk.mp3',                                -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'iori_fall.mp3',                          -- Falling
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },             -- Boing
  [CHAR_SOUND_WHOA] = 'sfx_ssb64_ledge.mp3',                        -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'iori_atk3.mp3' },                         -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'iori_atk3.mp3' },             -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'iori_atk1.mp3' },                   -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'iori_sigh.mp3' },
}

VT_EIMI = {
  [CHAR_SOUND_ATTACKED] = { 'eimi_dmg1.mp3', 'eimi_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'eimi_huh1.mp3',                                               -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'eimi_defeat1.mp3', 'eimi_defeat2.mp3' },
  [CHAR_SOUND_HERE_WE_GO] = { 'eimi_star1.mp3' },                                   -- Star Get + Obtaining Power-up
  [CHAR_SOUND_LETS_A_GO] = { 'eimi_ls1.mp3' },                                      -- Level Select
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                     -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'eimi_sleepy.mp3',
  [CHAR_SOUND_HOOHOO] = { 'eimi_atk2.mp3' },                                        -- 2nd Jump + Dive Attack
  [CHAR_SOUND_ON_FIRE] = { 'eimi_dmg3.mp3' },                                       -- Touch Fire
  [CHAR_SOUND_OOOF] = 'eimi_hmmm1.mp3',                                             -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'eimi_dmg1.mp3',                                             -- Landing After a Bonk + Thrown out of level + Also Bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'eimi_atk5.mp3' },                                     -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'eimi_atk2.mp3',                                         -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'eimi_atk1.mp3',                                         -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'eimi_bthrow1.mp3' },                            -- Bowser Throw
  [CHAR_SOUND_WAH2] = { 'eimi_throw1.mp3' },                                        -- Throw Object
  [CHAR_SOUND_UH] = 'eimi_hmmm3.mp3',                                               -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'eimi_hmmm2.mp3',                                         -- Falling
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                             -- Boing
  [CHAR_SOUND_WHOA] = 'eimi_huh1.mp3',                                              -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'sfx_ssb64_superjump.mp3' },                               -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'sfx_ssb64_superjump.mp3' },                   -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'eimi_atk4.mp3', 'eimi_atk5.mp3', 'eimi_atk3.mp3' }, -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'eimi_sigh.mp3' },
}

VT_ASUNA = {
  [CHAR_SOUND_ATTACKED] = { 'asuna_dmg2.mp3', 'asuna_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'asuna_ooh.mp3',             -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'asuna_dying.mp3' },
  [CHAR_SOUND_HAHA] = { 'asuna_jaan.mp3' },       -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'asuna_star.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'asuna_punch1.mp3' },   -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'asuna_grab.mp3',           -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'asuna_sleepy.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'asuna_kick.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'asuna_letsGo.mp3' },        -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'asuna_levelFail.mp3' },      -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'asuna_dmg2.mp3' },            -- Touch Fire
  [CHAR_SOUND_OOOF] = 'asuna_grab.mp3',                    -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'asuna_dmg2.mp3',                  -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'asuna_kick.mp3' },          -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'asuna_punch2.mp3',            -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'asuna_punch1.mp3',            -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'asuna_bowser.mp3' },  -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },   -- Boing
  -- [CHAR_SOUND_UH] = 'asuna_are.mp3', -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'asuna_punch1.mp3' },              -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'asuna_falling.mp3',            -- Falling
  -- [CHAR_SOUND_WAH2] = {'asuna_throw1.mp3'},-- Throw Object
  [CHAR_SOUND_WHOA] = 'asuna_grab.mp3',                   -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'asuna_yahoo.mp3' },             -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'asuna_yahoo.mp3' }, -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'asuna_punch2.mp3' },      -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'sumire_yawn.mp3'},
}

VT_KARIN = {
  [CHAR_SOUND_ATTACKED] = { 'karin_dmg2.mp3', 'karin_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'karin_ugh.mp3',             -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'karin_dying.mp3' },
  [CHAR_SOUND_HAHA] = { 'karin_un.mp3' },         -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'karin_star.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'karin_jump2.mp3' },    -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'karin_grab.mp3',           -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'karin_sleepy.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'karin_yahoo.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'karin_letsGo.mp3' },                      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'karin_levelFail.mp3' },                    -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'karin_dmg2.mp3' },                          -- Touch Fire
  [CHAR_SOUND_OOOF] = 'karin_ugh.mp3',                                  -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'karin_dmg1.mp3',                                -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'karin_kick.mp3' },                        -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'karin_punch2.mp3',                          -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'karin_punch1.mp3',                          -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'karin_bowser.mp3' },                -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                 -- Boing
  -- [CHAR_SOUND_UH] = 'karin_are.mp3', 								-- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'karin_punch1.mp3' },                            -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'karin_ugh.mp3',                              -- Falling
  -- [CHAR_SOUND_WAH2] = {'karin_throw1.mp3'},							-- Throw Object
  [CHAR_SOUND_WHOA] = 'karin_grab.mp3',                                 -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'karin_yahoo.mp3' },                           -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'karin_yahoo.mp3' },               -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'karin_punch1.mp3', 'karin_jump1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'karin_yawn.mp3'},
}

VT_AKANE = {
  [CHAR_SOUND_ATTACKED] = { 'akane_dmg2.mp3', 'akane_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'akane_ara.mp3',             -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'akane_dying.mp3' },
  [CHAR_SOUND_HAHA] = { 'akane_laugh.mp3' },      -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'akane_star.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'akane_jump2.mp3' },    -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'akane_ara.mp3',            -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = 'akane_sleepy.mp3',
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'akane_yahoo2.mp3'},
  [CHAR_SOUND_LETS_A_GO] = { 'akane_letsGo.mp3' },                      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'akane_levelFail.mp3' },                    -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'akane_dmg2.mp3' },                          -- Touch Fire
  [CHAR_SOUND_OOOF] = 'akane_ara.mp3',                                  -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'akane_dmg1.mp3',                                -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'akane_kick.mp3' },                        -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'akane_jump2.mp3',                           -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'akane_punch1.mp3',                          -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'akane_bowser.mp3' },                -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                 -- Boing
  [CHAR_SOUND_UH] = 'akane_ara.mp3',                                    -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'akane_punch1.mp3' },                            -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'akane_falling.mp3',                          -- Falling
  -- [CHAR_SOUND_WAH2] = {'akane_throw1.mp3'},-- Throw Object
  [CHAR_SOUND_WHOA] = 'akane_ara.mp3',                                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'akane_yahoo.mp3' },                           -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'akane_yahoo.mp3' },               -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'akane_jump1.mp3', 'akane_punch1.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'akane_yawn.mp3'},
}

VT_MAKI = {
  [CHAR_SOUND_ATTACKED] = { 'maki_dmg1.mp3' },
  [CHAR_SOUND_DYING] = 'maki_dying.mp3',
  [CHAR_SOUND_DOH] = 'maki_dmg1.mp3',
  [CHAR_SOUND_PUNCH_HOO] = 'maki_kick.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = 'maki_kick.mp3',
  [CHAR_SOUND_HAHA] = 'maki_laugh.mp3',
  [CHAR_SOUND_HAHA_2] = 'maki_laugh.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'maki_letsGo.mp3' },
  [CHAR_SOUND_HOOHOO] = { 'maki_jump2.mp3' },
  [CHAR_SOUND_YAHOO] = 'maki_yahoo.mp3',
  [CHAR_SOUND_MAMA_MIA] = { 'maki_levelFail.mp3' },
  [CHAR_SOUND_HRMM] = 'maki_grab.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'maki_star.mp3' },
  [CHAR_SOUND_UH] = 'maki_ueh.mp3',
  [CHAR_SOUND_OOOF] = 'maki_ueh.mp3',
  [CHAR_SOUND_YAH_WAH_HOO] = { 'maki_jump1.mp3' },
  [CHAR_SOUND_OOOF2] = 'maki_ueh.mp3',
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = 'maki_jump3.mp3',
  [CHAR_SOUND_PUNCH_YAH] = 'maki_jump1.mp3',
  [CHAR_SOUND_PUNCH_WAH] = 'maki_punch2.mp3',
  [CHAR_SOUND_WAAAOOOW] = 'maki_falling.mp3',
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'maki_bowser.mp3', 'maki_bowser2.mp3' },
  [CHAR_SOUND_WHOA] = 'maki_ledgeGrab.mp3',
  [CHAR_SOUND_ON_FIRE] = 'maki_falling.mp3',
}

VT_HIKARI = {
  [CHAR_SOUND_ATTACKED] = { 'hikari_dmg1.mp3' },
  [CHAR_SOUND_DOH] = 'hikari_bonk.mp3',                                                 -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'hikari_dead2.mp3', 'hikari_dead1.mp3' },
  [CHAR_SOUND_HAHA] = { 'hikari_jan.mp3' },                                             -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'hikari_star1.mp3', 'hikari_star2.mp3', 'hikari_star3.mp3', 'hikari_star4.mp3' },                   -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'hikari_jump1.mp3' },                                           -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'hikari_pickup.mp3',                                         -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'hikari_tired.mp3',
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'hikari_atk3.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'hikari_levelselect.mp3' },                                          -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'hikari_getup1.mp3', 'hikari_getup2.mp3', 'hikari_levelexit.mp3'},                                    -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'hikari_dmg2.mp3' },                                          -- Touch Fire
  [CHAR_SOUND_OOOF] = 'hikari_drop.mp3',                                                   -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'hikari_bonk.mp3',                                                -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'hikari_atk3.mp3' },                                        -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'hikari_atk2.mp3',                                            -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'hikari_atk1.mp3',                                            -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'hikari_bthrow.mp3' },                                -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                                 -- Boing
  [CHAR_SOUND_UH] = 'hikari_drop.mp3',                                                  -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'hikari_atk2.mp3' },                                             -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'hikari_fall.mp3',                                             -- Falling
  [CHAR_SOUND_WAH2] = { 'hikari_throw.mp3' },                                            -- Throw Object
  --[CHAR_SOUND_WHOA] = 'ibuki_ah1.mp3',                                                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'hikari_longjump.mp3' },                                        -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'hikari_longjump.mp3' },                            -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'hikari_atk1.mp3', 'hikari_jump2.mp3', 'hikari_atk2.mp3' }, -- 1st Jump(s)
}

VT_NOZOMI = {
  [CHAR_SOUND_ATTACKED] = { 'nozomi_dmg1.mp3', 'nozomi_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'nozomi_bonk2.mp3',                                                 -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'nozomi_dead1.mp3' },
  [CHAR_SOUND_HAHA] = { 'nozomi_laugh2.mp3' },                                             -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'nozomi_star1.mp3', 'nozomi_star2.mp3' },                   -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'nozomi_atk5.mp3' },                                           -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'nozomi_grab.mp3',                                         -- Object Pick-up
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'nozomi_atk3.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'nozomi_ls1.mp3' },                                          -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'nozomi_getup.mp3' },                                    -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'nozomi_fire.mp3' },                                          -- Touch Fire
  [CHAR_SOUND_OOOF] = 'nozomi_bonk3.mp3',                                                   -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'nozomi_geh.mp3',                                                -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'nozomi_atk2.mp3' },                                        -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'nozomi_atk4.mp3',                                            -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'nozomi_atk1.mp3',                                            -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'nozomi_bthrow.mp3' },                                -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                                 -- Boing
  [CHAR_SOUND_UH] = 'nozomi_bonk1.mp3',                                                  -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'nozomi_atk5.mp3' },                                             -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'nozomi_fall.mp3',                                             -- Falling
  [CHAR_SOUND_WAH2] = { 'nozomi_laugh3.mp3' },                                            -- Throw Object
  [CHAR_SOUND_WHOA] = 'nozomi_bonk3.mp3',                                                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'nozomi_laugh1.mp3' },                                        -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'nozomi_longjump.mp3', 'nozomi_atk3.mp3' },                            -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'nozomi_atk1.mp3', 'nozomi_atk4.mp3' }, -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'nozomi_yawn.mp3' },
}

VT_AOBA = {
  [CHAR_SOUND_ATTACKED] = { 'aoba_dmg1.mp3', 'aoba_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'aoba_bonk.mp3',                                               -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'aoba_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'aoba_push.mp3' }, 											--Ledge Climb
  [CHAR_SOUND_HAHA] = { 'aoba_heehee.mp3' },                                             -- Landing after backflip
  [CHAR_SOUND_HERE_WE_GO] = { 'aoba_star1.mp3', 'aoba_star2.mp3' },                   -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'aoba_atk3.mp3' },                                           -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                         -- Object Pick-up
  [CHAR_SOUND_GROUND_POUND_WAH] = { 'aoba_atk4.mp3' },
  [CHAR_SOUND_LETS_A_GO] = { 'aoba_ls1.mp3' },                                          -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'aoba_thissucks.mp3' },                                    -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'aoba_fall.mp3' },                                          -- Touch Fire
  [CHAR_SOUND_OOOF] = 'aoba_dmg4.mp3',                                                   -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'aoba_dmg3.mp3',                                                -- Landing After a Bonk + Thrown out of level + Also bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'aoba_atk2.mp3' },                                        -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'aoba_atk6.mp3',                                            -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'aoba_atk5.mp3',                                            -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'aoba_atk4.mp3' },                                -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                                 -- Boing
  [CHAR_SOUND_UH] = 'aoba_eh.mp3',                                                  -- Drop off of ledge + Fall off Ledge
  --[CHAR_SOUND_UH2] = { 'nozomi_atk5.mp3' },                                             -- Quick Ledge Get-Up
  [CHAR_SOUND_WAAAOOOW] = 'aoba_fall.mp3',                                             -- Falling
  [CHAR_SOUND_WAH2] = { 'aoba_throw.mp3' },                                            -- Throw Object
  [CHAR_SOUND_WHOA] = 'aoba_eh.mp3',                                                  -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'aoba_atk4.mp3' },                                        -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'aoba_atk4.mp3' },                            -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'aoba_atk1.mp3', 'aoba_jump1.mp3' }, -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'aoba_yawn.mp3' },
}

VT_SHUN = {
  [CHAR_SOUND_ATTACKED] = { 'shun_dmg1.mp3', 'shun_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'shun_ara1.mp3',           -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'shun_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'shun_slowclimb.mp3' }, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'.mp3'},
  [CHAR_SOUND_HAHA] = { 'shun_laugh1.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'shun_star1.mp3', 'shun_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'shun_jump4.mp3' },                       -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'shun_ara2.mp3',                              -- Object Pick-up
  -- [CHAR_SOUND_IMA_TIRED] = '.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'shun_ls1.mp3', 'shun_ls2.mp3' },      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'shun_levelexit.mp3' },                 -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'shun_dmg3.mp3' },                       -- Touch Fire
  [CHAR_SOUND_OOOF] = 'shun_dmg1.mp3',                              -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'shun_dmg2.mp3',                             -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'shun_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'shun_atk2.mp3',     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'shun_jump1.mp3',    -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'shun_bthrow1.mp3', 'shun_bthrow2.mp3' }, -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'shun_laugh2.mp3' },                         -- Boing
  [CHAR_SOUND_UH] = 'shun_ara1.mp3',                                         -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'shun_jump1.mp3' },                                   -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = '.mp3', -- Falling
  [CHAR_SOUND_WAH2] = { 'shun_bthrow1.mp3' },                       -- Throw Object
  [CHAR_SOUND_WHOA] = 'shun_ara1.mp3',                              -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'shun_laugh2.mp3' },                       -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'shun_laugh2.mp3' },           -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'shun_atk1.mp3', 'shun_jump3.mp3' }, -- 1st Jump(s)
  [CHAR_SOUND_YAWNING] = { 'shun_yawn.mp3' },
}

VT_CHILD_SHUN = {
  [CHAR_SOUND_ATTACKED] = { 'young_dmg1.mp3', 'young_dmg2.mp3' },
  [CHAR_SOUND_DOH] = 'young_are1.mp3',           -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'young_dead1.mp3' },
  [CHAR_SOUND_EEUH] = { 'young_slowclimb.mp3' }, -- Slow Get up from ledge
  -- [CHAR_SOUND_GAME_OVER] = {'silent.mp3'},
  -- [CHAR_SOUND_GROUND_POUND_WAH] = {'.mp3'},
  [CHAR_SOUND_HAHA] = { 'young_laugh1.mp3' }, -- Landing after backflip
  -- [CHAR_SOUND_HAHA_2] = 'silent.mp3', -- Landing on Water after a fall
  -- [CHAR_SOUND_HELLO] = 'silent.mp3',
  [CHAR_SOUND_HERE_WE_GO] = { 'young_star1.mp3', 'young_star2.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_HOOHOO] = { 'young_atk2.mp3' },                         -- 2nd Jump + Dive Attack
  [CHAR_SOUND_HRMM] = 'young_heavy.mp3',                              -- Object Pick-up
  [CHAR_SOUND_IMA_TIRED] = 'young_imatired.mp3',
  [CHAR_SOUND_LETS_A_GO] = { 'young_ls1.mp3', 'young_ls2.mp3' },      -- Level Select
  [CHAR_SOUND_MAMA_MIA] = { 'young_levelexit.mp3' },                  -- Getting up after thrown out of level
  [CHAR_SOUND_ON_FIRE] = { 'young_onfire.mp3' },                      -- Touch Fire
  [CHAR_SOUND_OOOF] = 'young_are1.mp3',                               -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'young_dmg2.mp3',                              -- Landing After a Bonk + Thrown out of level
  -- [CHAR_SOUND_PANTING] = {'silent.mp3'}, -- Low Health
  -- [CHAR_SOUND_PANTING_COLD] = 'silent.mp3',
  -- [CHAR_SOUND_PRESS_START_TO_PLAY] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_PUNCH_HOO] = { 'young_atk3.mp3' }, -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'young_jump2.mp3',    -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'young_atk2.mp3',     -- 1st Punch
  -- [CHAR_SOUND_SNORING1] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING2] = 'silent.mp3',
  -- [CHAR_SOUND_SNORING3] = {'silent.mp3', 'silent.mp3'},
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'young_bthrow1.mp3' }, -- Bowser Throw
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'young_laugh1.mp3' },     -- Boing
  [CHAR_SOUND_UH] = 'young_idk.mp3',                      -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_UH2] = { 'young_atk2.mp3' },                -- Quick Ledge Get-Up
  -- [CHAR_SOUND_UH2_2] = 'silent.mp3', -- Landing after Long Jump
  -- [CHAR_SOUND_WAAAOOOW] = '.mp3', -- Falling
  [CHAR_SOUND_WAH2] = { 'young_atk1.mp3' },                            -- Throw Object
  [CHAR_SOUND_WHOA] = 'young_are1.mp3',                                -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'young_longjump.mp3' },                       -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'young_longjump.mp3' },           -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'young_jump1.mp3', 'young_jump2.mp3' }, -- 1st Jump(s)
  -- [CHAR_SOUND_YAWNING] = {'shun_yawn.mp3'},
}

VT_NOVOICE = {
  [CHAR_SOUND_ATTACKED] = { 'sfx_smrpg_hit1.mp3', 'sfx_smrpg_shell.mp3', 'sfx_smw_bossstun.mp3' },
  [CHAR_SOUND_DOH] = 'sfx_ml_bump.mp3',                                              -- Bonk into walls
  [CHAR_SOUND_DYING] = { 'sfx_smb3_down.mp3' },
  [CHAR_SOUND_HERE_WE_GO] = { 'sfx_alttp_item.mp3', 'sfx_smrpg_specialflower.mp3' }, -- Star Get + Obtaining Power-up
  [CHAR_SOUND_LETS_A_GO] = { 'sfx_smb3_levelselect.mp3' },                           -- Level Select
  [CHAR_SOUND_HRMM] = 'sfx_ssb64_itemgrab.mp3',                                      -- Object Pick-up
  [CHAR_SOUND_HOOHOO] = { 'sfx_smw_jump.mp3' },                                      -- 2nd Jump + Dive Attack
  [CHAR_SOUND_ON_FIRE] = { 'sfx_smrpg_hot.mp3' },                                    -- Touch Fire
  [CHAR_SOUND_OOOF] = 'sfx_pm64_what.mp3',                                           -- Grabbed by Chuckya
  [CHAR_SOUND_OOOF2] = 'sfx_smrpg_drop.mp3',                                         -- Landing After a Bonk + Thrown out of level + Also Bonk into walls?
  [CHAR_SOUND_PUNCH_HOO] = { 'sfx_ssb64_atk3.mp3' },                                 -- Kick
  [CHAR_SOUND_PUNCH_WAH] = 'sfx_ssb64_atk2.mp3',                                     -- 2nd Punch
  [CHAR_SOUND_PUNCH_YAH] = 'sfx_ssb64_atk1.mp3',                                     -- 1st Punch
  [CHAR_SOUND_SO_LONGA_BOWSER] = { 'sfx_smrpg_fireball.mp3' },                       -- Bowser Throw
  [CHAR_SOUND_WAH2] = { 'sfx_ssb64_itemthrow.mp3' },                                 -- Throw Object
  [CHAR_SOUND_UH] = 'sfx_smrpg_throw.mp3',                                           -- Drop off of ledge + Fall off Ledge
  [CHAR_SOUND_WAAAOOOW] = 'sfx_ssb64_falling.mp3',                                   -- Falling
  [CHAR_SOUND_TWIRL_BOUNCE] = { 'sfx_smw_spring.mp3' },                              -- Boing
  [CHAR_SOUND_WHOA] = 'sfx_ssb64_ledge.mp3',                                         -- Ledge Grab
  [CHAR_SOUND_YAHOO] = { 'sfx_ssb64_superjump.mp3' },                                -- Long Jump
  [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = { 'sfx_ssb64_superjump.mp3' },                    -- 3rd Jump(s)
  [CHAR_SOUND_YAH_WAH_HOO] = { 'sfx_smw_jump.mp3' },                                 -- 1st Jump(s)
}